//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by New Setup.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NEWSETUP_DIALOG             102
#define IDS_Gp2Dir                      107
#define IDS_ExtDir                      110
#define IDR_MAINFRAME                   128
#define IDD_Quit                        132
#define IDD_TrackPos                    135
#define IDD_DIALOG1                     137
#define IDD_DIALOG2                     138
#define IDC_Icon                        1001
#define IDC_Exit                        1002
#define IDC_Resume                      1003
#define IDC_Next                        1004
#define IDC_Back                        1005
#define IDC_MainIcon                    1010
#define IDC_TypeOfSetup                 1012
#define IDC_Typical                     1013
#define IDC_Custom                      1014
#define IDC_TypicalText                 1015
#define IDC_CustomText                  1016
#define IDC_Dir                         1018
#define IDC_Browse                      1020
#define IDC_PathFrame                   1021
#define IDC_View                        1022
#define IDC_Full                        1042
#define IDC_FullInstall                 1044
#define IDC_TrackPos                    1048
#define IDC_Change                      1050
#define IDC_WelcomeText                 1051
#define IDC_Welcome                     1052

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
