//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by New Track Install.rc
//
#define IDS_Welcome                     1
#define IDS_Summary                     2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_ExitWizard                  100
#define IDS_ABOUTBOX                    101
#define IDD_NEWTRACKINSTALL_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDR_TrackSetupMenu              133
#define IDD_About                       134
#define IDD_TrackInfo                   135
#define IDC_Next                        1000
#define IDC_Back                        1001
#define IDC_Cancel                      1002
#define IDC_Exit                        1003
#define IDC_Resume                      1004
#define IDC_InstallLogo                 1005
#define IDC_Split                       1006
#define IDC_WelcomeText                 1007
#define IDC_SetupFrame                  1008
#define IDC_Gp2DirFrame                 1009
#define IDC_Gp2Dir                      1010
#define IDC_Gp2DirBrowse                1012
#define IDC_SetupFile                   1013
#define IDC_SetupBrowse                 1014
#define IDC_AddTrack                    1015
#define IDC_RemoveGp2Form               1016
#define IDC_AddGp2Form                  1017
#define IDC_Gp2form                     1018
#define IDC_JamFiles                    1019
#define IDC_AddJam                      1020
#define IDC_RemoveJam                   1021
#define IDC_RemoveAll                   1022
#define IDC_Summary                     1023
#define IDC_Ok                          1024
#define IDC_Name                        1025
#define IDC_Country                     1026
#define IDC_Laps                        1027
#define IDC_TrackFile2                  1028
#define IDC_Len                         1028
#define IDC_RemoveTrack2                1029
#define IDC_Adjective                   1029
#define ID_FILE_EXIT                    32771
#define ID_HELP_HELP                    32772
#define ID_HELP_ABOUT                   32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
