//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Adressbok.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ADRESSBOK_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDR_MAINMENU                    129
#define IDD_SEARCH                      130
#define IDI_PHONE                       131
#define IDC_NEWCONTACT                  1000
#define IDC_FIRSTNAME                   1001
#define IDC_ADDRESS                     1002
#define IDC_CITY                        1003
#define IDC_LASTNAME                    1004
#define IDC_CONTACT_LIST                1005
#define IDC_EDIT_FIRSTNAME              1008
#define IDC_EDIT_LASTNAME               1009
#define IDC_EDIT_ADDRESS                1010
#define IDC_EDIT_POSTNR                 1011
#define IDC_EDIT_CITY                   1012
#define IDC_EDIT_PHONE                  1013
#define IDC_BUTTON_ADD                  1014
#define IDC_BUTTON_REMOVE               1015
#define IDC_BUTTON_SAVE                 1016
#define IDC_BUTTON_SEARCH               1017
#define IDC_CHECK_FIRSTNAME             1022
#define IDC_CHECK_ADDRESS               1023
#define IDC_CHECK_LASTNAME              1024
#define IDC_CHECK_POSTNR                1025
#define IDC_CHECK_CITY                  1026
#define IDC_CHECK_PHONE                 1027
#define IDC_FRAME_LIST                  1030
#define IDC_BUTTON_CANCEL               1031
#define IDC_BUTTON_SHOWALL              1032
#define IDC_BUTTON2                     1033
#define ID_FILE_NY                      32773
#define ID_FILE_SPARASOM                32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
