//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GP1 Lap.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GP1LAP_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       132
#define IDR_MENU1                       133
#define IDC_Import                      1000
#define IDC_EDIT1                       1001
#define IDC_Export                      1002
#define IDC_FileName                    1003
#define IDC_About                       1004
#define IDC_Exit                        1005
#define MNU_TrackDir                    32771
#define MNU_Exit                        32772
#define MNU_About                       32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
