//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Uppgift2.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_UPPGIFT2_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDC_EDIT_RESULT                 1002
#define IDC_EDIT_ADD1                   1003
#define IDC_EDIT_EQUALS                 1004
#define IDC_BUTTON_EQUALS               1005
#define IDC_BUTTON_ADD                  1006
#define IDC_BUTTON_ADD2                 1007
#define IDC_BUTTON_REPLACE              1008
#define IDC_BUTTON_UPPERCASE            1009
#define IDC_BUTTON_LOWERCASE            1010
#define IDC_EDIT_ADD2                   1011
#define IDC_EDIT_FIND                   1012
#define IDC_EDIT_REPLACE                1013
#define IDC_EDIT_ADD3                   1014
#define IDC_EDIT_REAL                   1015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
