main.cpp 1: 
Mask.cpp 1: 
Mask.h 1: 
MaskPart.cpp 1: 
MaskPart.h 1: class MaskPart
MaskPart.h 2: {
MaskPart.h 3: private:
MaskPart.h 4: int x;
MaskPart.h 5: int y;
MaskPart.h 6: public:
MaskPart.h 7: MaskPart(int x=50,int y=50);
MaskPart.h 8: void SetX(int);
MaskPart.h 9: void SetY(int);
MaskPart.h 10: int GetX();
MaskPart.h 11: int GetY();
MaskPart.h 12: };
MaskPart.h 13: 
MaskPart.cpp 2: 
MaskPart.cpp 3: MaskPart::MaskPart(int x,int y)
MaskPart.cpp 4: {
MaskPart.cpp 5: this->x=x;
MaskPart.cpp 6: this->y=y;
MaskPart.cpp 7: }
MaskPart.cpp 8: 
MaskPart.cpp 9: void MaskPart::SetX(int x)
MaskPart.cpp 10: {
MaskPart.cpp 11: this->x=x;
MaskPart.cpp 12: }
MaskPart.cpp 13: 
MaskPart.cpp 14: void MaskPart::SetY(int y)
MaskPart.cpp 15: {
MaskPart.cpp 16: this->y=y;
MaskPart.cpp 17: }
MaskPart.cpp 18: 
MaskPart.cpp 19: int MaskPart::GetX()
MaskPart.cpp 20: {
MaskPart.cpp 21: return(x);
MaskPart.cpp 22: }
MaskPart.cpp 23: 
MaskPart.cpp 24: int MaskPart::GetY()
MaskPart.cpp 25: {
MaskPart.cpp 26: return(y);
MaskPart.cpp 27: }
MaskPart.cpp 28: 
MaskPart.cpp 29: 
Mask.h 2: 
Grafik.cpp 1: 
Grafik.h 1: 
C:\Program\BC45\INCLUDE\graphics.h 1: 
C:\Program\BC45\INCLUDE\graphics.h 2: 
C:\Program\BC45\INCLUDE\graphics.h 3: 
C:\Program\BC45\INCLUDE\graphics.h 4: 
C:\Program\BC45\INCLUDE\graphics.h 5: 
C:\Program\BC45\INCLUDE\graphics.h 6: 
C:\Program\BC45\INCLUDE\graphics.h 7: 
C:\Program\BC45\INCLUDE\graphics.h 8: 
C:\Program\BC45\INCLUDE\graphics.h 9: 
C:\Program\BC45\INCLUDE\graphics.h 10: 
C:\Program\BC45\INCLUDE\graphics.h 11: 
C:\Program\BC45\INCLUDE\graphics.h 12: 
C:\Program\BC45\INCLUDE\graphics.h 13: 
C:\Program\BC45\INCLUDE\graphics.h 14: 
C:\Program\BC45\INCLUDE\graphics.h 15: 
C:\Program\BC45\INCLUDE\graphics.h 16: 
C:\Program\BC45\INCLUDE\graphics.h 17: 
C:\Program\BC45\INCLUDE\graphics.h 18:     
C:\Program\BC45\INCLUDE\graphics.h 19: 
C:\Program\BC45\INCLUDE\graphics.h 20: 
C:\Program\BC45\INCLUDE\graphics.h 21: 
C:\Program\BC45\INCLUDE\graphics.h 22: 
C:\Program\BC45\INCLUDE\graphics.h 23: 
C:\Program\BC45\INCLUDE\graphics.h 24: 
C:\Program\BC45\INCLUDE\graphics.h 25: 
C:\Program\BC45\INCLUDE\graphics.h 26: 
C:\Program\BC45\INCLUDE\graphics.h 27: 
C:\Program\BC45\INCLUDE\_defs.h 1: 
C:\Program\BC45\INCLUDE\_defs.h 2: 
C:\Program\BC45\INCLUDE\_defs.h 3: 
C:\Program\BC45\INCLUDE\_defs.h 4: 
C:\Program\BC45\INCLUDE\_defs.h 5: 
C:\Program\BC45\INCLUDE\_defs.h 6: 
C:\Program\BC45\INCLUDE\_defs.h 7: 
C:\Program\BC45\INCLUDE\_defs.h 8: 
C:\Program\BC45\INCLUDE\_defs.h 9: 
C:\Program\BC45\INCLUDE\_defs.h 10: 
C:\Program\BC45\INCLUDE\_defs.h 11: 
C:\Program\BC45\INCLUDE\_defs.h 12: 
C:\Program\BC45\INCLUDE\_defs.h 13: 
C:\Program\BC45\INCLUDE\_defs.h 14: 
C:\Program\BC45\INCLUDE\_defs.h 15: 
C:\Program\BC45\INCLUDE\_defs.h 16: 
C:\Program\BC45\INCLUDE\_defs.h 17: 
C:\Program\BC45\INCLUDE\_defs.h 18: 
C:\Program\BC45\INCLUDE\_defs.h 19: 
C:\Program\BC45\INCLUDE\_defs.h 20: 
C:\Program\BC45\INCLUDE\_defs.h 21: 
C:\Program\BC45\INCLUDE\_defs.h 22: 
C:\Program\BC45\INCLUDE\_defs.h 23: 
C:\Program\BC45\INCLUDE\_defs.h 24: 
C:\Program\BC45\INCLUDE\_defs.h 25: 
C:\Program\BC45\INCLUDE\_defs.h 26: 
C:\Program\BC45\INCLUDE\_defs.h 27: 
C:\Program\BC45\INCLUDE\_defs.h 28: 
C:\Program\BC45\INCLUDE\_defs.h 29: 
C:\Program\BC45\INCLUDE\_defs.h 30: 
C:\Program\BC45\INCLUDE\_defs.h 31: 
C:\Program\BC45\INCLUDE\_defs.h 32: 
C:\Program\BC45\INCLUDE\_defs.h 33: 
C:\Program\BC45\INCLUDE\_defs.h 34: 
C:\Program\BC45\INCLUDE\_defs.h 35: 
C:\Program\BC45\INCLUDE\_defs.h 36: 
C:\Program\BC45\INCLUDE\_defs.h 37: 
C:\Program\BC45\INCLUDE\_defs.h 38: 
C:\Program\BC45\INCLUDE\_defs.h 39: 
C:\Program\BC45\INCLUDE\_defs.h 40: 
C:\Program\BC45\INCLUDE\_defs.h 41: 
C:\Program\BC45\INCLUDE\_defs.h 42: 
C:\Program\BC45\INCLUDE\_defs.h 43: 
C:\Program\BC45\INCLUDE\_defs.h 44: 
C:\Program\BC45\INCLUDE\_defs.h 45: 
C:\Program\BC45\INCLUDE\_defs.h 46: 
C:\Program\BC45\INCLUDE\_defs.h 47: 
C:\Program\BC45\INCLUDE\_defs.h 48: 
C:\Program\BC45\INCLUDE\_defs.h 49: 
C:\Program\BC45\INCLUDE\_defs.h 50: 
C:\Program\BC45\INCLUDE\_defs.h 51: 
C:\Program\BC45\INCLUDE\_defs.h 52: 
C:\Program\BC45\INCLUDE\_defs.h 53: 
C:\Program\BC45\INCLUDE\_defs.h 54: 
C:\Program\BC45\INCLUDE\_defs.h 55: 
C:\Program\BC45\INCLUDE\_defs.h 56: 
C:\Program\BC45\INCLUDE\_defs.h 57: 
C:\Program\BC45\INCLUDE\_defs.h 58: 
C:\Program\BC45\INCLUDE\_defs.h 59: 
C:\Program\BC45\INCLUDE\_defs.h 60: 
C:\Program\BC45\INCLUDE\_defs.h 61: 
C:\Program\BC45\INCLUDE\_defs.h 62: 
C:\Program\BC45\INCLUDE\_defs.h 63: 
C:\Program\BC45\INCLUDE\_defs.h 64: 
C:\Program\BC45\INCLUDE\_defs.h 65: 
C:\Program\BC45\INCLUDE\_defs.h 66: 
C:\Program\BC45\INCLUDE\_defs.h 67: 
C:\Program\BC45\INCLUDE\_defs.h 68: 
C:\Program\BC45\INCLUDE\_defs.h 69: 
C:\Program\BC45\INCLUDE\_defs.h 70: 
C:\Program\BC45\INCLUDE\_defs.h 71: 
C:\Program\BC45\INCLUDE\_defs.h 72: 
C:\Program\BC45\INCLUDE\_defs.h 73: 
C:\Program\BC45\INCLUDE\_defs.h 74: 
C:\Program\BC45\INCLUDE\_defs.h 75: 
C:\Program\BC45\INCLUDE\_defs.h 76: 
C:\Program\BC45\INCLUDE\_defs.h 77: 
C:\Program\BC45\INCLUDE\_defs.h 78: 
C:\Program\BC45\INCLUDE\_defs.h 79: 
C:\Program\BC45\INCLUDE\_defs.h 80: 
C:\Program\BC45\INCLUDE\_defs.h 81: 
C:\Program\BC45\INCLUDE\_defs.h 82: 
C:\Program\BC45\INCLUDE\_defs.h 83: 
C:\Program\BC45\INCLUDE\_defs.h 84: 
C:\Program\BC45\INCLUDE\_defs.h 85: 
C:\Program\BC45\INCLUDE\_defs.h 86:   
C:\Program\BC45\INCLUDE\_defs.h 87: 
C:\Program\BC45\INCLUDE\_defs.h 88: 
C:\Program\BC45\INCLUDE\_defs.h 89: 
C:\Program\BC45\INCLUDE\_defs.h 90:     
C:\Program\BC45\INCLUDE\_defs.h 91: 
C:\Program\BC45\INCLUDE\_defs.h 92: 
C:\Program\BC45\INCLUDE\_defs.h 93: 
C:\Program\BC45\INCLUDE\_defs.h 94: 
C:\Program\BC45\INCLUDE\_defs.h 95: 
C:\Program\BC45\INCLUDE\_defs.h 96: 
C:\Program\BC45\INCLUDE\_defs.h 97: 
C:\Program\BC45\INCLUDE\_defs.h 98: 
C:\Program\BC45\INCLUDE\_defs.h 99: 
C:\Program\BC45\INCLUDE\_defs.h 100: 
C:\Program\BC45\INCLUDE\_defs.h 101: 
C:\Program\BC45\INCLUDE\_defs.h 102: 
C:\Program\BC45\INCLUDE\_defs.h 103: 
C:\Program\BC45\INCLUDE\_defs.h 104: 
C:\Program\BC45\INCLUDE\_defs.h 105: 
C:\Program\BC45\INCLUDE\_defs.h 106: 
C:\Program\BC45\INCLUDE\_defs.h 107: 
C:\Program\BC45\INCLUDE\_defs.h 108: 
C:\Program\BC45\INCLUDE\_defs.h 109: 
C:\Program\BC45\INCLUDE\_defs.h 110:   
C:\Program\BC45\INCLUDE\_defs.h 111: 
C:\Program\BC45\INCLUDE\_defs.h 112: 
C:\Program\BC45\INCLUDE\_defs.h 113: 
C:\Program\BC45\INCLUDE\_defs.h 114: 
C:\Program\BC45\INCLUDE\_defs.h 115: 
C:\Program\BC45\INCLUDE\_defs.h 116: 
C:\Program\BC45\INCLUDE\_defs.h 117: 
C:\Program\BC45\INCLUDE\_defs.h 118: 
C:\Program\BC45\INCLUDE\_defs.h 119: 
C:\Program\BC45\INCLUDE\_defs.h 120: 
C:\Program\BC45\INCLUDE\_defs.h 121: 
C:\Program\BC45\INCLUDE\_defs.h 122: 
C:\Program\BC45\INCLUDE\_defs.h 123: 
C:\Program\BC45\INCLUDE\_defs.h 124: 
C:\Program\BC45\INCLUDE\_defs.h 125: 
C:\Program\BC45\INCLUDE\_defs.h 126: 
C:\Program\BC45\INCLUDE\_defs.h 127: 
C:\Program\BC45\INCLUDE\_defs.h 128: 
C:\Program\BC45\INCLUDE\_defs.h 129: 
C:\Program\BC45\INCLUDE\_defs.h 130: 
C:\Program\BC45\INCLUDE\_defs.h 131: 
C:\Program\BC45\INCLUDE\_defs.h 132: 
C:\Program\BC45\INCLUDE\_defs.h 133: 
C:\Program\BC45\INCLUDE\_defs.h 134: 
C:\Program\BC45\INCLUDE\_defs.h 135: 
C:\Program\BC45\INCLUDE\_defs.h 136: 
C:\Program\BC45\INCLUDE\_defs.h 137: 
C:\Program\BC45\INCLUDE\_defs.h 138: 
C:\Program\BC45\INCLUDE\_defs.h 139:   
C:\Program\BC45\INCLUDE\_defs.h 140: 
C:\Program\BC45\INCLUDE\_defs.h 141: 
C:\Program\BC45\INCLUDE\_defs.h 142: 
C:\Program\BC45\INCLUDE\_defs.h 143: 
C:\Program\BC45\INCLUDE\_defs.h 144: 
C:\Program\BC45\INCLUDE\_defs.h 145: 
C:\Program\BC45\INCLUDE\_defs.h 146: 
C:\Program\BC45\INCLUDE\_defs.h 147: 
C:\Program\BC45\INCLUDE\_defs.h 148: 
C:\Program\BC45\INCLUDE\_defs.h 149: 
C:\Program\BC45\INCLUDE\_defs.h 150: 
C:\Program\BC45\INCLUDE\_defs.h 151: 
C:\Program\BC45\INCLUDE\_defs.h 152: 
C:\Program\BC45\INCLUDE\_defs.h 153: 
C:\Program\BC45\INCLUDE\_defs.h 154: 
C:\Program\BC45\INCLUDE\_defs.h 155: 
C:\Program\BC45\INCLUDE\_defs.h 156: 
C:\Program\BC45\INCLUDE\_defs.h 157: 
C:\Program\BC45\INCLUDE\_defs.h 158: 
C:\Program\BC45\INCLUDE\_defs.h 159: 
C:\Program\BC45\INCLUDE\_defs.h 160: 
C:\Program\BC45\INCLUDE\_defs.h 161: 
C:\Program\BC45\INCLUDE\_defs.h 162: 
C:\Program\BC45\INCLUDE\_defs.h 163: 
C:\Program\BC45\INCLUDE\_defs.h 164: 
C:\Program\BC45\INCLUDE\_defs.h 165: 
C:\Program\BC45\INCLUDE\_defs.h 166: 
C:\Program\BC45\INCLUDE\_defs.h 167: 
C:\Program\BC45\INCLUDE\_defs.h 168: 
C:\Program\BC45\INCLUDE\_defs.h 169: 
C:\Program\BC45\INCLUDE\_defs.h 170: 
C:\Program\BC45\INCLUDE\_defs.h 171: 
C:\Program\BC45\INCLUDE\_defs.h 172: 
C:\Program\BC45\INCLUDE\_defs.h 173: 
C:\Program\BC45\INCLUDE\_defs.h 174: 
C:\Program\BC45\INCLUDE\_defs.h 175: 
C:\Program\BC45\INCLUDE\_defs.h 176: 
C:\Program\BC45\INCLUDE\_defs.h 177: 
C:\Program\BC45\INCLUDE\_defs.h 178: 
C:\Program\BC45\INCLUDE\graphics.h 28: 
C:\Program\BC45\INCLUDE\graphics.h 29: 
C:\Program\BC45\INCLUDE\graphics.h 30: 
C:\Program\BC45\INCLUDE\graphics.h 31: 
C:\Program\BC45\INCLUDE\graphics.h 32: 
C:\Program\BC45\INCLUDE\graphics.h 33: 
C:\Program\BC45\INCLUDE\graphics.h 34: 
C:\Program\BC45\INCLUDE\graphics.h 35: 
C:\Program\BC45\INCLUDE\graphics.h 36: 
C:\Program\BC45\INCLUDE\graphics.h 37: 
C:\Program\BC45\INCLUDE\graphics.h 38: 
C:\Program\BC45\INCLUDE\graphics.h 39: 
C:\Program\BC45\INCLUDE\graphics.h 40: 
C:\Program\BC45\INCLUDE\graphics.h 41: 
C:\Program\BC45\INCLUDE\graphics.h 42: 
C:\Program\BC45\INCLUDE\graphics.h 43: 
C:\Program\BC45\INCLUDE\graphics.h 44: 
C:\Program\BC45\INCLUDE\graphics.h 45: enum graphics_errors {      
C:\Program\BC45\INCLUDE\graphics.h 46: grOk           =   0,
C:\Program\BC45\INCLUDE\graphics.h 47: grNoInitGraph      =  -1,
C:\Program\BC45\INCLUDE\graphics.h 48: grNotDetected      =  -2,
C:\Program\BC45\INCLUDE\graphics.h 49: grFileNotFound     =  -3,
C:\Program\BC45\INCLUDE\graphics.h 50: grInvalidDriver    =  -4,
C:\Program\BC45\INCLUDE\graphics.h 51: grNoLoadMem    =  -5,
C:\Program\BC45\INCLUDE\graphics.h 52: grNoScanMem    =  -6,
C:\Program\BC45\INCLUDE\graphics.h 53: grNoFloodMem       =  -7,
C:\Program\BC45\INCLUDE\graphics.h 54: grFontNotFound     =  -8,
C:\Program\BC45\INCLUDE\graphics.h 55: grNoFontMem    =  -9,
C:\Program\BC45\INCLUDE\graphics.h 56: grInvalidMode      = -10,
C:\Program\BC45\INCLUDE\graphics.h 57: grError        = -11,   
C:\Program\BC45\INCLUDE\graphics.h 58: grIOerror      = -12,
C:\Program\BC45\INCLUDE\graphics.h 59: grInvalidFont      = -13,
C:\Program\BC45\INCLUDE\graphics.h 60: grInvalidFontNum   = -14,
C:\Program\BC45\INCLUDE\graphics.h 61: grInvalidVersion   = -18
C:\Program\BC45\INCLUDE\graphics.h 62: };
C:\Program\BC45\INCLUDE\graphics.h 63: 
C:\Program\BC45\INCLUDE\graphics.h 64: enum graphics_drivers {     
C:\Program\BC45\INCLUDE\graphics.h 65: DETECT,         
C:\Program\BC45\INCLUDE\graphics.h 66: CGA, MCGA, EGA, EGA64, EGAMONO, IBM8514,    
C:\Program\BC45\INCLUDE\graphics.h 67: HERCMONO, ATT400, VGA, PC3270,          
C:\Program\BC45\INCLUDE\graphics.h 68: CURRENT_DRIVER = -1
C:\Program\BC45\INCLUDE\graphics.h 69: };
C:\Program\BC45\INCLUDE\graphics.h 70: 
C:\Program\BC45\INCLUDE\graphics.h 71: enum graphics_modes {       
C:\Program\BC45\INCLUDE\graphics.h 72: CGAC0      = 0,  
C:\Program\BC45\INCLUDE\graphics.h 73: CGAC1      = 1,  
C:\Program\BC45\INCLUDE\graphics.h 74: CGAC2      = 2,  
C:\Program\BC45\INCLUDE\graphics.h 75: CGAC3      = 3,  
C:\Program\BC45\INCLUDE\graphics.h 76: CGAHI      = 4,  
C:\Program\BC45\INCLUDE\graphics.h 77: MCGAC0     = 0,  
C:\Program\BC45\INCLUDE\graphics.h 78: MCGAC1     = 1,  
C:\Program\BC45\INCLUDE\graphics.h 79: MCGAC2     = 2,  
C:\Program\BC45\INCLUDE\graphics.h 80: MCGAC3     = 3,  
C:\Program\BC45\INCLUDE\graphics.h 81: MCGAMED    = 4,  
C:\Program\BC45\INCLUDE\graphics.h 82: MCGAHI     = 5,  
C:\Program\BC45\INCLUDE\graphics.h 83: EGALO      = 0,  
C:\Program\BC45\INCLUDE\graphics.h 84: EGAHI      = 1,  
C:\Program\BC45\INCLUDE\graphics.h 85: EGA64LO    = 0,  
C:\Program\BC45\INCLUDE\graphics.h 86: EGA64HI    = 1,  
C:\Program\BC45\INCLUDE\graphics.h 87: EGAMONOHI  = 0,  
C:\Program\BC45\INCLUDE\graphics.h 88: HERCMONOHI = 0,  
C:\Program\BC45\INCLUDE\graphics.h 89: ATT400C0   = 0,  
C:\Program\BC45\INCLUDE\graphics.h 90: ATT400C1   = 1,  
C:\Program\BC45\INCLUDE\graphics.h 91: ATT400C2   = 2,  
C:\Program\BC45\INCLUDE\graphics.h 92: ATT400C3   = 3,  
C:\Program\BC45\INCLUDE\graphics.h 93: ATT400MED  = 4,  
C:\Program\BC45\INCLUDE\graphics.h 94: ATT400HI   = 5,  
C:\Program\BC45\INCLUDE\graphics.h 95: VGALO      = 0,  
C:\Program\BC45\INCLUDE\graphics.h 96: VGAMED     = 1,  
C:\Program\BC45\INCLUDE\graphics.h 97: VGAHI      = 2,  
C:\Program\BC45\INCLUDE\graphics.h 98: PC3270HI   = 0,  
C:\Program\BC45\INCLUDE\graphics.h 99: IBM8514LO  = 0,  
C:\Program\BC45\INCLUDE\graphics.h 100: IBM8514HI  = 1   
C:\Program\BC45\INCLUDE\graphics.h 101: };
C:\Program\BC45\INCLUDE\graphics.h 102: 
C:\Program\BC45\INCLUDE\graphics.h 103: 
C:\Program\BC45\INCLUDE\graphics.h 104: 
C:\Program\BC45\INCLUDE\graphics.h 105: 
C:\Program\BC45\INCLUDE\graphics.h 106: 
C:\Program\BC45\INCLUDE\graphics.h 107: 
C:\Program\BC45\INCLUDE\graphics.h 108: 
C:\Program\BC45\INCLUDE\graphics.h 109: 
C:\Program\BC45\INCLUDE\graphics.h 110: 
C:\Program\BC45\INCLUDE\graphics.h 111: 
C:\Program\BC45\INCLUDE\graphics.h 112: 
C:\Program\BC45\INCLUDE\graphics.h 113: 
C:\Program\BC45\INCLUDE\graphics.h 114: 
C:\Program\BC45\INCLUDE\graphics.h 115: 
C:\Program\BC45\INCLUDE\graphics.h 116: 
C:\Program\BC45\INCLUDE\graphics.h 117: 
C:\Program\BC45\INCLUDE\graphics.h 118: 
C:\Program\BC45\INCLUDE\graphics.h 119: 
C:\Program\BC45\INCLUDE\graphics.h 120: 
C:\Program\BC45\INCLUDE\graphics.h 121: 
C:\Program\BC45\INCLUDE\graphics.h 122: 
C:\Program\BC45\INCLUDE\graphics.h 123: 
C:\Program\BC45\INCLUDE\graphics.h 124: 
C:\Program\BC45\INCLUDE\graphics.h 125: 
C:\Program\BC45\INCLUDE\graphics.h 126: 
C:\Program\BC45\INCLUDE\graphics.h 127: 
C:\Program\BC45\INCLUDE\graphics.h 128: 
C:\Program\BC45\INCLUDE\graphics.h 129: 
C:\Program\BC45\INCLUDE\graphics.h 130: 
C:\Program\BC45\INCLUDE\graphics.h 131: 
C:\Program\BC45\INCLUDE\graphics.h 132: 
C:\Program\BC45\INCLUDE\graphics.h 133: 
C:\Program\BC45\INCLUDE\graphics.h 134: 
C:\Program\BC45\INCLUDE\graphics.h 135: 
C:\Program\BC45\INCLUDE\graphics.h 136: 
C:\Program\BC45\INCLUDE\graphics.h 137: 
C:\Program\BC45\INCLUDE\graphics.h 138: 
C:\Program\BC45\INCLUDE\graphics.h 139: 
C:\Program\BC45\INCLUDE\graphics.h 140: 
C:\Program\BC45\INCLUDE\graphics.h 141: 
C:\Program\BC45\INCLUDE\graphics.h 142: 
C:\Program\BC45\INCLUDE\graphics.h 143: 
C:\Program\BC45\INCLUDE\graphics.h 144: 
C:\Program\BC45\INCLUDE\graphics.h 145: 
C:\Program\BC45\INCLUDE\graphics.h 146: 
C:\Program\BC45\INCLUDE\graphics.h 147: 
C:\Program\BC45\INCLUDE\graphics.h 148: 
C:\Program\BC45\INCLUDE\graphics.h 149: 
C:\Program\BC45\INCLUDE\graphics.h 150: 
C:\Program\BC45\INCLUDE\graphics.h 151: 
C:\Program\BC45\INCLUDE\graphics.h 152: 
C:\Program\BC45\INCLUDE\graphics.h 153: 
C:\Program\BC45\INCLUDE\graphics.h 154: 
C:\Program\BC45\INCLUDE\graphics.h 155: 
C:\Program\BC45\INCLUDE\graphics.h 156: 
C:\Program\BC45\INCLUDE\graphics.h 157: 
C:\Program\BC45\INCLUDE\graphics.h 158: 
C:\Program\BC45\INCLUDE\graphics.h 159: 
C:\Program\BC45\INCLUDE\graphics.h 160: 
C:\Program\BC45\INCLUDE\graphics.h 161: 
C:\Program\BC45\INCLUDE\graphics.h 162: 
C:\Program\BC45\INCLUDE\graphics.h 163: 
C:\Program\BC45\INCLUDE\graphics.h 164: 
C:\Program\BC45\INCLUDE\graphics.h 165: 
C:\Program\BC45\INCLUDE\graphics.h 166: 
C:\Program\BC45\INCLUDE\graphics.h 167: 
C:\Program\BC45\INCLUDE\graphics.h 168: 
C:\Program\BC45\INCLUDE\graphics.h 169: 
C:\Program\BC45\INCLUDE\graphics.h 170: 
C:\Program\BC45\INCLUDE\graphics.h 171: enum COLORS {
C:\Program\BC45\INCLUDE\graphics.h 172: BLACK,          
C:\Program\BC45\INCLUDE\graphics.h 173: BLUE,
C:\Program\BC45\INCLUDE\graphics.h 174: GREEN,
C:\Program\BC45\INCLUDE\graphics.h 175: CYAN,
C:\Program\BC45\INCLUDE\graphics.h 176: RED,
C:\Program\BC45\INCLUDE\graphics.h 177: MAGENTA,
C:\Program\BC45\INCLUDE\graphics.h 178: BROWN,
C:\Program\BC45\INCLUDE\graphics.h 179: LIGHTGRAY,
C:\Program\BC45\INCLUDE\graphics.h 180: DARKGRAY,           
C:\Program\BC45\INCLUDE\graphics.h 181: LIGHTBLUE,
C:\Program\BC45\INCLUDE\graphics.h 182: LIGHTGREEN,
C:\Program\BC45\INCLUDE\graphics.h 183: LIGHTCYAN,
C:\Program\BC45\INCLUDE\graphics.h 184: LIGHTRED,
C:\Program\BC45\INCLUDE\graphics.h 185: LIGHTMAGENTA,
C:\Program\BC45\INCLUDE\graphics.h 186: YELLOW,
C:\Program\BC45\INCLUDE\graphics.h 187: WHITE
C:\Program\BC45\INCLUDE\graphics.h 188: };
C:\Program\BC45\INCLUDE\graphics.h 189: 
C:\Program\BC45\INCLUDE\graphics.h 190: 
C:\Program\BC45\INCLUDE\graphics.h 191: enum CGA_COLORS {
C:\Program\BC45\INCLUDE\graphics.h 192: CGA_LIGHTGREEN     = 1,     
C:\Program\BC45\INCLUDE\graphics.h 193: CGA_LIGHTRED       = 2,
C:\Program\BC45\INCLUDE\graphics.h 194: CGA_YELLOW         = 3,
C:\Program\BC45\INCLUDE\graphics.h 195: 
C:\Program\BC45\INCLUDE\graphics.h 196: CGA_LIGHTCYAN      = 1,     
C:\Program\BC45\INCLUDE\graphics.h 197: CGA_LIGHTMAGENTA   = 2,
C:\Program\BC45\INCLUDE\graphics.h 198: CGA_WHITE          = 3,
C:\Program\BC45\INCLUDE\graphics.h 199: 
C:\Program\BC45\INCLUDE\graphics.h 200: CGA_GREEN          = 1,     
C:\Program\BC45\INCLUDE\graphics.h 201: CGA_RED        = 2,
C:\Program\BC45\INCLUDE\graphics.h 202: CGA_BROWN          = 3,
C:\Program\BC45\INCLUDE\graphics.h 203: 
C:\Program\BC45\INCLUDE\graphics.h 204: CGA_CYAN           = 1,     
C:\Program\BC45\INCLUDE\graphics.h 205: CGA_MAGENTA        = 2,
C:\Program\BC45\INCLUDE\graphics.h 206: CGA_LIGHTGRAY      = 3
C:\Program\BC45\INCLUDE\graphics.h 207: };
C:\Program\BC45\INCLUDE\graphics.h 208: 
C:\Program\BC45\INCLUDE\graphics.h 209: 
C:\Program\BC45\INCLUDE\graphics.h 210: enum EGA_COLORS {
C:\Program\BC45\INCLUDE\graphics.h 211: EGA_BLACK        =  0,      
C:\Program\BC45\INCLUDE\graphics.h 212: EGA_BLUE         =  1,
C:\Program\BC45\INCLUDE\graphics.h 213: EGA_GREEN        =  2,
C:\Program\BC45\INCLUDE\graphics.h 214: EGA_CYAN         =  3,
C:\Program\BC45\INCLUDE\graphics.h 215: EGA_RED      =  4,
C:\Program\BC45\INCLUDE\graphics.h 216: EGA_MAGENTA      =  5,
C:\Program\BC45\INCLUDE\graphics.h 217: EGA_BROWN        =  20,
C:\Program\BC45\INCLUDE\graphics.h 218: EGA_LIGHTGRAY    =  7,
C:\Program\BC45\INCLUDE\graphics.h 219: EGA_DARKGRAY     =  56,     
C:\Program\BC45\INCLUDE\graphics.h 220: EGA_LIGHTBLUE    =  57,
C:\Program\BC45\INCLUDE\graphics.h 221: EGA_LIGHTGREEN   =  58,
C:\Program\BC45\INCLUDE\graphics.h 222: EGA_LIGHTCYAN    =  59,
C:\Program\BC45\INCLUDE\graphics.h 223: EGA_LIGHTRED     =  60,
C:\Program\BC45\INCLUDE\graphics.h 224: EGA_LIGHTMAGENTA     =  61,
C:\Program\BC45\INCLUDE\graphics.h 225: EGA_YELLOW       =  62,
C:\Program\BC45\INCLUDE\graphics.h 226: EGA_WHITE        =  63
C:\Program\BC45\INCLUDE\graphics.h 227: };
C:\Program\BC45\INCLUDE\graphics.h 228: 
C:\Program\BC45\INCLUDE\graphics.h 229: enum line_styles {      
C:\Program\BC45\INCLUDE\graphics.h 230: SOLID_LINE   = 0,
C:\Program\BC45\INCLUDE\graphics.h 231: DOTTED_LINE  = 1,
C:\Program\BC45\INCLUDE\graphics.h 232: CENTER_LINE  = 2,
C:\Program\BC45\INCLUDE\graphics.h 233: DASHED_LINE  = 3,
C:\Program\BC45\INCLUDE\graphics.h 234: USERBIT_LINE = 4,   
C:\Program\BC45\INCLUDE\graphics.h 235: };
C:\Program\BC45\INCLUDE\graphics.h 236: 
C:\Program\BC45\INCLUDE\graphics.h 237: enum line_widths {      
C:\Program\BC45\INCLUDE\graphics.h 238: NORM_WIDTH  = 1,
C:\Program\BC45\INCLUDE\graphics.h 239: THICK_WIDTH = 3,
C:\Program\BC45\INCLUDE\graphics.h 240: };
C:\Program\BC45\INCLUDE\graphics.h 241: 
C:\Program\BC45\INCLUDE\graphics.h 242: enum font_names {
C:\Program\BC45\INCLUDE\graphics.h 243: DEFAULT_FONT    = 0,    
C:\Program\BC45\INCLUDE\graphics.h 244: TRIPLEX_FONT    = 1,    
C:\Program\BC45\INCLUDE\graphics.h 245: SMALL_FONT  = 2,
C:\Program\BC45\INCLUDE\graphics.h 246: SANS_SERIF_FONT = 3,
C:\Program\BC45\INCLUDE\graphics.h 247: GOTHIC_FONT = 4,
C:\Program\BC45\INCLUDE\graphics.h 248: SCRIPT_FONT = 5,
C:\Program\BC45\INCLUDE\graphics.h 249: SIMPLEX_FONT = 6,
C:\Program\BC45\INCLUDE\graphics.h 250: TRIPLEX_SCR_FONT = 7,
C:\Program\BC45\INCLUDE\graphics.h 251: COMPLEX_FONT = 8,
C:\Program\BC45\INCLUDE\graphics.h 252: EUROPEAN_FONT = 9,
C:\Program\BC45\INCLUDE\graphics.h 253: BOLD_FONT = 10
C:\Program\BC45\INCLUDE\graphics.h 254: };
C:\Program\BC45\INCLUDE\graphics.h 255: 
C:\Program\BC45\INCLUDE\graphics.h 256: 
C:\Program\BC45\INCLUDE\graphics.h 257: 
C:\Program\BC45\INCLUDE\graphics.h 258: 
C:\Program\BC45\INCLUDE\graphics.h 259: 
C:\Program\BC45\INCLUDE\graphics.h 260: 
C:\Program\BC45\INCLUDE\graphics.h 261: enum fill_patterns {        
C:\Program\BC45\INCLUDE\graphics.h 262: EMPTY_FILL,     
C:\Program\BC45\INCLUDE\graphics.h 263: SOLID_FILL,     
C:\Program\BC45\INCLUDE\graphics.h 264: LINE_FILL,      
C:\Program\BC45\INCLUDE\graphics.h 265: LTSLASH_FILL,       
C:\Program\BC45\INCLUDE\graphics.h 266: SLASH_FILL,     
C:\Program\BC45\INCLUDE\graphics.h 267: BKSLASH_FILL,       
C:\Program\BC45\INCLUDE\graphics.h 268: LTBKSLASH_FILL,     
C:\Program\BC45\INCLUDE\graphics.h 269: HATCH_FILL,     
C:\Program\BC45\INCLUDE\graphics.h 270: XHATCH_FILL,        
C:\Program\BC45\INCLUDE\graphics.h 271: INTERLEAVE_FILL,    
C:\Program\BC45\INCLUDE\graphics.h 272: WIDE_DOT_FILL,      
C:\Program\BC45\INCLUDE\graphics.h 273: CLOSE_DOT_FILL,     
C:\Program\BC45\INCLUDE\graphics.h 274: USER_FILL       
C:\Program\BC45\INCLUDE\graphics.h 275: };
C:\Program\BC45\INCLUDE\graphics.h 276: 
C:\Program\BC45\INCLUDE\graphics.h 277: enum putimage_ops {     
C:\Program\BC45\INCLUDE\graphics.h 278: COPY_PUT,       
C:\Program\BC45\INCLUDE\graphics.h 279: XOR_PUT,        
C:\Program\BC45\INCLUDE\graphics.h 280: OR_PUT,         
C:\Program\BC45\INCLUDE\graphics.h 281: AND_PUT,        
C:\Program\BC45\INCLUDE\graphics.h 282: NOT_PUT         
C:\Program\BC45\INCLUDE\graphics.h 283: };
C:\Program\BC45\INCLUDE\graphics.h 284: 
C:\Program\BC45\INCLUDE\graphics.h 285: enum text_just {        
C:\Program\BC45\INCLUDE\graphics.h 286: 
C:\Program\BC45\INCLUDE\graphics.h 287: LEFT_TEXT   = 0,
C:\Program\BC45\INCLUDE\graphics.h 288: CENTER_TEXT = 1,
C:\Program\BC45\INCLUDE\graphics.h 289: RIGHT_TEXT  = 2,
C:\Program\BC45\INCLUDE\graphics.h 290: 
C:\Program\BC45\INCLUDE\graphics.h 291: BOTTOM_TEXT = 0,
C:\Program\BC45\INCLUDE\graphics.h 292: 
C:\Program\BC45\INCLUDE\graphics.h 293: TOP_TEXT    = 2
C:\Program\BC45\INCLUDE\graphics.h 294: };
C:\Program\BC45\INCLUDE\graphics.h 295: 
C:\Program\BC45\INCLUDE\graphics.h 296: 
C:\Program\BC45\INCLUDE\graphics.h 297: 
C:\Program\BC45\INCLUDE\graphics.h 298: 
C:\Program\BC45\INCLUDE\graphics.h 299: struct palettetype {
C:\Program\BC45\INCLUDE\graphics.h 300: unsigned char size;
C:\Program\BC45\INCLUDE\graphics.h 301: signed char colors[15+1];
C:\Program\BC45\INCLUDE\graphics.h 302: };
C:\Program\BC45\INCLUDE\graphics.h 303: 
C:\Program\BC45\INCLUDE\graphics.h 304: struct linesettingstype {
C:\Program\BC45\INCLUDE\graphics.h 305: int linestyle;
C:\Program\BC45\INCLUDE\graphics.h 306: unsigned upattern;
C:\Program\BC45\INCLUDE\graphics.h 307: int thickness;
C:\Program\BC45\INCLUDE\graphics.h 308: };
C:\Program\BC45\INCLUDE\graphics.h 309: 
C:\Program\BC45\INCLUDE\graphics.h 310: struct textsettingstype {
C:\Program\BC45\INCLUDE\graphics.h 311: int font;
C:\Program\BC45\INCLUDE\graphics.h 312: int direction;
C:\Program\BC45\INCLUDE\graphics.h 313: int charsize;
C:\Program\BC45\INCLUDE\graphics.h 314: int horiz;
C:\Program\BC45\INCLUDE\graphics.h 315: int vert;
C:\Program\BC45\INCLUDE\graphics.h 316: };
C:\Program\BC45\INCLUDE\graphics.h 317: 
C:\Program\BC45\INCLUDE\graphics.h 318: struct fillsettingstype {
C:\Program\BC45\INCLUDE\graphics.h 319: int pattern;
C:\Program\BC45\INCLUDE\graphics.h 320: int color;
C:\Program\BC45\INCLUDE\graphics.h 321: };
C:\Program\BC45\INCLUDE\graphics.h 322: 
C:\Program\BC45\INCLUDE\graphics.h 323: struct pointtype {
C:\Program\BC45\INCLUDE\graphics.h 324: int x, y;
C:\Program\BC45\INCLUDE\graphics.h 325: };
C:\Program\BC45\INCLUDE\graphics.h 326: 
C:\Program\BC45\INCLUDE\graphics.h 327: struct viewporttype {
C:\Program\BC45\INCLUDE\graphics.h 328: int left, top, right, bottom;
C:\Program\BC45\INCLUDE\graphics.h 329: int clip;
C:\Program\BC45\INCLUDE\graphics.h 330: };
C:\Program\BC45\INCLUDE\graphics.h 331: 
C:\Program\BC45\INCLUDE\graphics.h 332: struct arccoordstype {
C:\Program\BC45\INCLUDE\graphics.h 333: int x, y;
C:\Program\BC45\INCLUDE\graphics.h 334: int xstart, ystart, xend, yend;
C:\Program\BC45\INCLUDE\graphics.h 335: };
C:\Program\BC45\INCLUDE\graphics.h 336: 
C:\Program\BC45\INCLUDE\graphics.h 337: 
C:\Program\BC45\INCLUDE\graphics.h 338: extern "C" {
C:\Program\BC45\INCLUDE\graphics.h 339: 
C:\Program\BC45\INCLUDE\graphics.h 340: 
C:\Program\BC45\INCLUDE\graphics.h 341: 
C:\Program\BC45\INCLUDE\graphics.h 342: 
C:\Program\BC45\INCLUDE\graphics.h 343: 
C:\Program\BC45\INCLUDE\graphics.h 344: 
C:\Program\BC45\INCLUDE\graphics.h 345: 
C:\Program\BC45\INCLUDE\graphics.h 346: void       __far __cdecl arc(int __x, int __y, int __stangle, int __endangle,
C:\Program\BC45\INCLUDE\graphics.h 347: int __radius);
C:\Program\BC45\INCLUDE\graphics.h 348: void       __far __cdecl bar(int __left, int __top, int __right, int __bottom);
C:\Program\BC45\INCLUDE\graphics.h 349: void       __far __cdecl bar3d(int __left, int __top, int __right, int __bottom,
C:\Program\BC45\INCLUDE\graphics.h 350: int __depth, int __topflag);
C:\Program\BC45\INCLUDE\graphics.h 351: void       __far __cdecl circle(int __x, int __y, int __radius);
C:\Program\BC45\INCLUDE\graphics.h 352: void       __far __cdecl cleardevice(void);
C:\Program\BC45\INCLUDE\graphics.h 353: void       __far __cdecl clearviewport(void);
C:\Program\BC45\INCLUDE\graphics.h 354: void       __far __cdecl closegraph(void);
C:\Program\BC45\INCLUDE\graphics.h 355: void       __far __cdecl detectgraph(int __far *__graphdriver,int __far *__graphmode);
C:\Program\BC45\INCLUDE\graphics.h 356: void       __far __cdecl drawpoly(int __numpoints, const int __far *__polypoints);
C:\Program\BC45\INCLUDE\graphics.h 357: void       __far __cdecl ellipse(int __x, int __y, int __stangle, int __endangle,
C:\Program\BC45\INCLUDE\graphics.h 358: int __xradius, int __yradius);
C:\Program\BC45\INCLUDE\graphics.h 359: void       __far __cdecl fillellipse( int __x, int __y, int __xradius, int __yradius );
C:\Program\BC45\INCLUDE\graphics.h 360: void       __far __cdecl fillpoly(int __numpoints, const int __far *__polypoints);
C:\Program\BC45\INCLUDE\graphics.h 361: void       __far __cdecl floodfill(int __x, int __y, int __border);
C:\Program\BC45\INCLUDE\graphics.h 362: void       __far __cdecl getarccoords(struct arccoordstype __far *__arccoords);
C:\Program\BC45\INCLUDE\graphics.h 363: void       __far __cdecl getaspectratio(int __far *__xasp, int __far *__yasp);
C:\Program\BC45\INCLUDE\graphics.h 364: int        __far __cdecl getbkcolor(void);
C:\Program\BC45\INCLUDE\graphics.h 365: int        __far __cdecl getcolor(void);
C:\Program\BC45\INCLUDE\graphics.h 366: struct palettetype __far * __far __cdecl getdefaultpalette( void );
C:\Program\BC45\INCLUDE\graphics.h 367: char *     __far __cdecl getdrivername( void );
C:\Program\BC45\INCLUDE\graphics.h 368: void       __far __cdecl getfillpattern(char __far *__pattern);
C:\Program\BC45\INCLUDE\graphics.h 369: void       __far __cdecl getfillsettings(struct fillsettingstype __far *__fillinfo);
C:\Program\BC45\INCLUDE\graphics.h 370: int        __far __cdecl getgraphmode(void);
C:\Program\BC45\INCLUDE\graphics.h 371: void       __far __cdecl getimage(int __left, int __top, int __right, int __bottom,
C:\Program\BC45\INCLUDE\graphics.h 372: void __far *__bitmap);
C:\Program\BC45\INCLUDE\graphics.h 373: void       __far __cdecl getlinesettings(struct linesettingstype __far *__lineinfo);
C:\Program\BC45\INCLUDE\graphics.h 374: int        __far __cdecl getmaxcolor(void);
C:\Program\BC45\INCLUDE\graphics.h 375: int        __far __cdecl getmaxmode(void);
C:\Program\BC45\INCLUDE\graphics.h 376: int        __far __cdecl getmaxx(void);
C:\Program\BC45\INCLUDE\graphics.h 377: int        __far __cdecl getmaxy(void);
C:\Program\BC45\INCLUDE\graphics.h 378: char *     __far __cdecl getmodename( int __mode_number );
C:\Program\BC45\INCLUDE\graphics.h 379: void       __far __cdecl getmoderange(int __graphdriver, int __far *__lomode,
C:\Program\BC45\INCLUDE\graphics.h 380: int __far *__himode);
C:\Program\BC45\INCLUDE\graphics.h 381: unsigned   __far __cdecl getpixel(int __x, int __y);
C:\Program\BC45\INCLUDE\graphics.h 382: void       __far __cdecl getpalette(struct palettetype __far *__palette);
C:\Program\BC45\INCLUDE\graphics.h 383: int        __far __cdecl getpalettesize( void );
C:\Program\BC45\INCLUDE\graphics.h 384: void       __far __cdecl gettextsettings(struct textsettingstype __far *__texttypeinfo);
C:\Program\BC45\INCLUDE\graphics.h 385: void       __far __cdecl getviewsettings(struct viewporttype __far *__viewport);
C:\Program\BC45\INCLUDE\graphics.h 386: int        __far __cdecl getx(void);
C:\Program\BC45\INCLUDE\graphics.h 387: int        __far __cdecl gety(void);
C:\Program\BC45\INCLUDE\graphics.h 388: void       __far __cdecl graphdefaults(void);
C:\Program\BC45\INCLUDE\graphics.h 389: char *     __far __cdecl grapherrormsg(int __errorcode);
C:\Program\BC45\INCLUDE\graphics.h 390: void       __far __cdecl _graphfreemem(void __far *__ptr, unsigned __size);
C:\Program\BC45\INCLUDE\graphics.h 391: void __far * __far __cdecl _graphgetmem(unsigned __size);
C:\Program\BC45\INCLUDE\graphics.h 392: int        __far __cdecl graphresult(void);
C:\Program\BC45\INCLUDE\graphics.h 393: unsigned   __far __cdecl imagesize(int __left, int __top, int __right, int __bottom);
C:\Program\BC45\INCLUDE\graphics.h 394: void       __far __cdecl initgraph(int  __far *__graphdriver,
C:\Program\BC45\INCLUDE\graphics.h 395: int  __far *__graphmode,
C:\Program\BC45\INCLUDE\graphics.h 396: const char __far *__pathtodriver);
C:\Program\BC45\INCLUDE\graphics.h 397: int        __far __cdecl installuserdriver(const char __far *__name,
C:\Program\BC45\INCLUDE\graphics.h 398: int __huge (*detect)(void));
C:\Program\BC45\INCLUDE\graphics.h 399: int        __far __cdecl installuserfont(const char __far *__name);
C:\Program\BC45\INCLUDE\graphics.h 400: void       __far __cdecl line(int __x1, int __y1, int __x2, int __y2);
C:\Program\BC45\INCLUDE\graphics.h 401: void       __far __cdecl linerel(int __dx, int __dy);
C:\Program\BC45\INCLUDE\graphics.h 402: void       __far __cdecl lineto(int __x, int __y);
C:\Program\BC45\INCLUDE\graphics.h 403: void       __far __cdecl moverel(int __dx, int __dy);
C:\Program\BC45\INCLUDE\graphics.h 404: void       __far __cdecl moveto(int __x, int __y);
C:\Program\BC45\INCLUDE\graphics.h 405: void       __far __cdecl outtext(const char __far *__textstring);
C:\Program\BC45\INCLUDE\graphics.h 406: void       __far __cdecl outtextxy(int __x, int __y, const char __far *__textstring);
C:\Program\BC45\INCLUDE\graphics.h 407: void       __far __cdecl pieslice(int __x, int __y, int __stangle, int __endangle,
C:\Program\BC45\INCLUDE\graphics.h 408: int __radius);
C:\Program\BC45\INCLUDE\graphics.h 409: void       __far __cdecl putimage(int __left, int __top, const void __far *__bitmap,
C:\Program\BC45\INCLUDE\graphics.h 410: int __op);
C:\Program\BC45\INCLUDE\graphics.h 411: void       __far __cdecl putpixel(int __x, int __y, int __color);
C:\Program\BC45\INCLUDE\graphics.h 412: void       __far __cdecl rectangle(int __left, int __top, int __right, int __bottom);
C:\Program\BC45\INCLUDE\graphics.h 413: void       __far __cdecl restorecrtmode(void);
C:\Program\BC45\INCLUDE\graphics.h 414: void       __far __cdecl sector(int __X, int __Y, int __StAngle, int __EndAngle,
C:\Program\BC45\INCLUDE\graphics.h 415: int __XRadius, int __YRadius);
C:\Program\BC45\INCLUDE\graphics.h 416: void       __far __cdecl setactivepage(int __page);
C:\Program\BC45\INCLUDE\graphics.h 417: void       __far __cdecl setallpalette(const struct palettetype __far *__palette);
C:\Program\BC45\INCLUDE\graphics.h 418: void       __far __cdecl setaspectratio(int __xasp, int __yasp);
C:\Program\BC45\INCLUDE\graphics.h 419: void       __far __cdecl setbkcolor(int __color);
C:\Program\BC45\INCLUDE\graphics.h 420: void       __far __cdecl setcolor(int __color);
C:\Program\BC45\INCLUDE\graphics.h 421: void       __far __cdecl setfillpattern(const char __far *__upattern, int __color);
C:\Program\BC45\INCLUDE\graphics.h 422: void       __far __cdecl setfillstyle(int __pattern, int __color);
C:\Program\BC45\INCLUDE\graphics.h 423: unsigned   __far __cdecl setgraphbufsize(unsigned __bufsize);
C:\Program\BC45\INCLUDE\graphics.h 424: void       __far __cdecl setgraphmode(int __mode);
C:\Program\BC45\INCLUDE\graphics.h 425: void       __far __cdecl setlinestyle(int __linestyle, unsigned __upattern,
C:\Program\BC45\INCLUDE\graphics.h 426: int __thickness);
C:\Program\BC45\INCLUDE\graphics.h 427: void       __far __cdecl setpalette(int __colornum, int __color);
C:\Program\BC45\INCLUDE\graphics.h 428: void       __far __cdecl setrgbpalette(int __colornum,
C:\Program\BC45\INCLUDE\graphics.h 429: int __red, int __green, int __blue);
C:\Program\BC45\INCLUDE\graphics.h 430: void       __far __cdecl settextjustify(int __horiz, int __vert);
C:\Program\BC45\INCLUDE\graphics.h 431: void       __far __cdecl settextstyle(int __font, int __direction, int __charsize);
C:\Program\BC45\INCLUDE\graphics.h 432: void       __far __cdecl setusercharsize(int __multx, int __divx,
C:\Program\BC45\INCLUDE\graphics.h 433: int __multy, int __divy);
C:\Program\BC45\INCLUDE\graphics.h 434: void       __far __cdecl setviewport(int __left, int __top, int __right, int __bottom,
C:\Program\BC45\INCLUDE\graphics.h 435: int __clip);
C:\Program\BC45\INCLUDE\graphics.h 436: void       __far __cdecl setvisualpage(int __page);
C:\Program\BC45\INCLUDE\graphics.h 437: void       __far __cdecl setwritemode( int __mode );
C:\Program\BC45\INCLUDE\graphics.h 438: int        __far __cdecl textheight(const char __far *__textstring);
C:\Program\BC45\INCLUDE\graphics.h 439: int        __far __cdecl textwidth(const char __far *__textstring);
C:\Program\BC45\INCLUDE\graphics.h 440: 
C:\Program\BC45\INCLUDE\graphics.h 441: 
C:\Program\BC45\INCLUDE\graphics.h 442: 
C:\Program\BC45\INCLUDE\graphics.h 443: int        __cdecl registerbgidriver(void (*driver)(void));
C:\Program\BC45\INCLUDE\graphics.h 444: 
C:\Program\BC45\INCLUDE\graphics.h 445:   
C:\Program\BC45\INCLUDE\graphics.h 446: 
C:\Program\BC45\INCLUDE\graphics.h 447: 
C:\Program\BC45\INCLUDE\graphics.h 448: int    __far __cdecl registerfarbgidriver(void __far *__driver);
C:\Program\BC45\INCLUDE\graphics.h 449: 
C:\Program\BC45\INCLUDE\graphics.h 450: 
C:\Program\BC45\INCLUDE\graphics.h 451: 
C:\Program\BC45\INCLUDE\graphics.h 452: 
C:\Program\BC45\INCLUDE\graphics.h 453: 
C:\Program\BC45\INCLUDE\graphics.h 454: void           __cdecl CGA_driver(void);
C:\Program\BC45\INCLUDE\graphics.h 455: void           __cdecl EGAVGA_driver(void);
C:\Program\BC45\INCLUDE\graphics.h 456: void           __cdecl IBM8514_driver(void);
C:\Program\BC45\INCLUDE\graphics.h 457: void           __cdecl Herc_driver(void);
C:\Program\BC45\INCLUDE\graphics.h 458: void           __cdecl ATT_driver(void);
C:\Program\BC45\INCLUDE\graphics.h 459: void           __cdecl PC3270_driver(void);
C:\Program\BC45\INCLUDE\graphics.h 460: 
C:\Program\BC45\INCLUDE\graphics.h 461: 
C:\Program\BC45\INCLUDE\graphics.h 462: 
C:\Program\BC45\INCLUDE\graphics.h 463: 
C:\Program\BC45\INCLUDE\graphics.h 464: 
C:\Program\BC45\INCLUDE\graphics.h 465: 
C:\Program\BC45\INCLUDE\graphics.h 466: 
C:\Program\BC45\INCLUDE\graphics.h 467: 
C:\Program\BC45\INCLUDE\graphics.h 468: 
C:\Program\BC45\INCLUDE\graphics.h 469: extern int __far __cdecl CGA_driver_far[];
C:\Program\BC45\INCLUDE\graphics.h 470: extern int __far __cdecl EGAVGA_driver_far[];
C:\Program\BC45\INCLUDE\graphics.h 471: extern int __far __cdecl IBM8514_driver_far[];
C:\Program\BC45\INCLUDE\graphics.h 472: extern int __far __cdecl Herc_driver_far[];
C:\Program\BC45\INCLUDE\graphics.h 473: extern int __far __cdecl ATT_driver_far[];
C:\Program\BC45\INCLUDE\graphics.h 474: extern int __far __cdecl PC3270_driver_far[];
C:\Program\BC45\INCLUDE\graphics.h 475: 
C:\Program\BC45\INCLUDE\graphics.h 476: 
C:\Program\BC45\INCLUDE\graphics.h 477: 
C:\Program\BC45\INCLUDE\graphics.h 478: 
C:\Program\BC45\INCLUDE\graphics.h 479: int        __cdecl registerbgifont(void (*font)(void));
C:\Program\BC45\INCLUDE\graphics.h 480: 
C:\Program\BC45\INCLUDE\graphics.h 481:   
C:\Program\BC45\INCLUDE\graphics.h 482: 
C:\Program\BC45\INCLUDE\graphics.h 483: 
C:\Program\BC45\INCLUDE\graphics.h 484: int    __far __cdecl registerfarbgifont(void __far *__font);
C:\Program\BC45\INCLUDE\graphics.h 485: 
C:\Program\BC45\INCLUDE\graphics.h 486: 
C:\Program\BC45\INCLUDE\graphics.h 487: 
C:\Program\BC45\INCLUDE\graphics.h 488: 
C:\Program\BC45\INCLUDE\graphics.h 489: 
C:\Program\BC45\INCLUDE\graphics.h 490: void           __cdecl   triplex_font(void);
C:\Program\BC45\INCLUDE\graphics.h 491: void           __cdecl     small_font(void);
C:\Program\BC45\INCLUDE\graphics.h 492: void           __cdecl sansserif_font(void);
C:\Program\BC45\INCLUDE\graphics.h 493: void           __cdecl    gothic_font(void);
C:\Program\BC45\INCLUDE\graphics.h 494: 
C:\Program\BC45\INCLUDE\graphics.h 495: extern int __far __cdecl   triplex_font_far[];
C:\Program\BC45\INCLUDE\graphics.h 496: extern int __far __cdecl     small_font_far[];
C:\Program\BC45\INCLUDE\graphics.h 497: extern int __far __cdecl sansserif_font_far[];
C:\Program\BC45\INCLUDE\graphics.h 498: extern int __far __cdecl    gothic_font_far[];
C:\Program\BC45\INCLUDE\graphics.h 499: 
C:\Program\BC45\INCLUDE\graphics.h 500: 
C:\Program\BC45\INCLUDE\graphics.h 501: }
C:\Program\BC45\INCLUDE\graphics.h 502: 
C:\Program\BC45\INCLUDE\graphics.h 503: 
C:\Program\BC45\INCLUDE\graphics.h 504: 
C:\Program\BC45\INCLUDE\graphics.h 505: 
C:\Program\BC45\INCLUDE\graphics.h 506: 
Grafik.h 2: 
Grafik.h 3: class Grafik
Grafik.h 4: {
Grafik.h 5: private:
Grafik.h 6: int    GraphDriver;             
Grafik.h 7: int    GraphMode;               
Grafik.h 8: double AspectRatio;             
Grafik.h 9: int    MaxX, MaxY;              
Grafik.h 10: int    MaxColors;               
Grafik.h 11: int    ErrorCode;               
Grafik.h 12: struct palettetype palette;     
Grafik.h 13: public:
Grafik.h 14: void Initialize(void);
Grafik.h 15: void Reset(void);
Grafik.h 16: void PaintPixle(int x, int y, int color);
Grafik.h 17: void PrintText(int x, int y, char *text, int color=14, int HorizJust=0, int Font=0, int Size=1);
Grafik.h 18: void PaintBox(int x, int y, int height, int width,int color);
Grafik.h 19: void PaintLine(int x1, int y1, int x2, int y2, int color=15);
Grafik.h 20: int GetMaxX(void);
Grafik.h 21: int GetMaxY(void);
Grafik.h 22: int GetColor(int x, int y);
Grafik.h 23: void ClearScreen();
Grafik.h 24: };
Grafik.h 25: 
Grafik.cpp 2: 
Grafik.cpp 3: void Grafik::Initialize(void)
Grafik.cpp 4: {
Grafik.cpp 5: int xasp, yasp;                       
Grafik.cpp 6: 
Grafik.cpp 7: GraphDriver = DETECT;                 
Grafik.cpp 8: initgraph( &GraphDriver, &GraphMode, "" );
Grafik.cpp 9: ErrorCode = graphresult();            
Grafik.cpp 10: 
Grafik.cpp 11: getpalette( &palette );               
Grafik.cpp 12: MaxColors = getmaxcolor() + 1;        
Grafik.cpp 13: 
Grafik.cpp 14: MaxX = getmaxx();
Grafik.cpp 15: MaxY = getmaxy();                     
Grafik.cpp 16: 
Grafik.cpp 17: getaspectratio( &xasp, &yasp );       
Grafik.cpp 18: AspectRatio = (double)xasp / (double)yasp; 
Grafik.cpp 19: }
Grafik.cpp 20: 
Grafik.cpp 21: void Grafik::Reset(void)
Grafik.cpp 22: {
Grafik.cpp 23: closegraph();		
Grafik.cpp 24: }
Grafik.cpp 25: 
Grafik.cpp 26: void Grafik::PaintPixle(int x, int y, int color)
Grafik.cpp 27: {
Grafik.cpp 28: putpixel(x, y, color);
Grafik.cpp 29: }
Grafik.cpp 30: 
Grafik.cpp 31: void Grafik::PrintText(int x,int y, char *text,int color, int HorizJust, int Font, int Size)
Grafik.cpp 32: {
Grafik.cpp 33: setcolor(color);
Grafik.cpp 34: settextstyle(Font, 0,Size);
Grafik.cpp 35: settextjustify(HorizJust, TOP_TEXT);
Grafik.cpp 36: outtextxy(x, y,text);
Grafik.cpp 37: }
Grafik.cpp 38: 
Grafik.cpp 39: void Grafik::PaintBox(int x, int y, int height, int width, int color)
Grafik.cpp 40: {
Grafik.cpp 41: setfillstyle(SOLID_FILL, color);
Grafik.cpp 42: bar(x,y,x+height,y+width);
Grafik.cpp 43: }
Grafik.cpp 44: 
Grafik.cpp 45: int Grafik::GetMaxX()
Grafik.cpp 46: {
Grafik.cpp 47: return(MaxX);
Grafik.cpp 48: }
Grafik.cpp 49: 
Grafik.cpp 50: int Grafik::GetMaxY()
Grafik.cpp 51: {
Grafik.cpp 52: return(MaxY);
Grafik.cpp 53: }
Grafik.cpp 54: 
Grafik.cpp 55: void Grafik::PaintLine(int x1, int y1, int x2, int y2, int color)
Grafik.cpp 56: {
Grafik.cpp 57: 
Grafik.cpp 58: setcolor(color);
Grafik.cpp 59: line(x1, y1, x2, y2);
Grafik.cpp 60: }
Grafik.cpp 61: 
Grafik.cpp 62: int Grafik::GetColor(int x, int y)
Grafik.cpp 63: {
Grafik.cpp 64: return(getpixel(x,y));
Grafik.cpp 65: }
Grafik.cpp 66: 
Grafik.cpp 67: void Grafik::ClearScreen()
Grafik.cpp 68: {
Grafik.cpp 69: cleardevice();
Grafik.cpp 70: }
Grafik.cpp 71: 
Mask.h 3: 
Dot.cpp 1: 
Dot.h 1: 
C:\Program\BC45\INCLUDE\time.h 1: 
C:\Program\BC45\INCLUDE\time.h 2: 
C:\Program\BC45\INCLUDE\time.h 3: 
C:\Program\BC45\INCLUDE\time.h 4: 
C:\Program\BC45\INCLUDE\time.h 5: 
C:\Program\BC45\INCLUDE\time.h 6: 
C:\Program\BC45\INCLUDE\time.h 7: 
C:\Program\BC45\INCLUDE\time.h 8: 
C:\Program\BC45\INCLUDE\time.h 9: 
C:\Program\BC45\INCLUDE\time.h 10: 
C:\Program\BC45\INCLUDE\time.h 11: 
C:\Program\BC45\INCLUDE\time.h 12: 
C:\Program\BC45\INCLUDE\time.h 13: 
C:\Program\BC45\INCLUDE\time.h 14: 
C:\Program\BC45\INCLUDE\time.h 15: 
C:\Program\BC45\INCLUDE\time.h 16: 
C:\Program\BC45\INCLUDE\time.h 17: 
C:\Program\BC45\INCLUDE\time.h 18: 
C:\Program\BC45\INCLUDE\time.h 19: 
C:\Program\BC45\INCLUDE\time.h 20: 
C:\Program\BC45\INCLUDE\time.h 21: 
C:\Program\BC45\INCLUDE\time.h 22: 
C:\Program\BC45\INCLUDE\time.h 23: 
C:\Program\BC45\INCLUDE\time.h 24: 
C:\Program\BC45\INCLUDE\time.h 25: 
C:\Program\BC45\INCLUDE\time.h 26: 
C:\Program\BC45\INCLUDE\time.h 27: 
C:\Program\BC45\INCLUDE\time.h 28: 
C:\Program\BC45\INCLUDE\time.h 29: #pragma option -a-
C:\Program\BC45\INCLUDE\time.h 30: 
C:\Program\BC45\INCLUDE\time.h 31: 
C:\Program\BC45\INCLUDE\time.h 32: 
C:\Program\BC45\INCLUDE\time.h 33: 
C:\Program\BC45\INCLUDE\time.h 34: 
C:\Program\BC45\INCLUDE\time.h 35: 
C:\Program\BC45\INCLUDE\time.h 36: typedef unsigned size_t;
C:\Program\BC45\INCLUDE\time.h 37: 
C:\Program\BC45\INCLUDE\time.h 38: 
C:\Program\BC45\INCLUDE\time.h 39: 
C:\Program\BC45\INCLUDE\time.h 40: 
C:\Program\BC45\INCLUDE\time.h 41: typedef long time_t;
C:\Program\BC45\INCLUDE\time.h 42: 
C:\Program\BC45\INCLUDE\time.h 43: 
C:\Program\BC45\INCLUDE\time.h 44: 
C:\Program\BC45\INCLUDE\time.h 45: 
C:\Program\BC45\INCLUDE\time.h 46: typedef long clock_t;
C:\Program\BC45\INCLUDE\time.h 47: 
C:\Program\BC45\INCLUDE\time.h 48: 
C:\Program\BC45\INCLUDE\time.h 49: 
C:\Program\BC45\INCLUDE\time.h 50: 
C:\Program\BC45\INCLUDE\time.h 51: 
C:\Program\BC45\INCLUDE\time.h 52: struct tm
C:\Program\BC45\INCLUDE\time.h 53: {
C:\Program\BC45\INCLUDE\time.h 54: int   tm_sec;
C:\Program\BC45\INCLUDE\time.h 55: int   tm_min;
C:\Program\BC45\INCLUDE\time.h 56: int   tm_hour;
C:\Program\BC45\INCLUDE\time.h 57: int   tm_mday;
C:\Program\BC45\INCLUDE\time.h 58: int   tm_mon;
C:\Program\BC45\INCLUDE\time.h 59: int   tm_year;
C:\Program\BC45\INCLUDE\time.h 60: int   tm_wday;
C:\Program\BC45\INCLUDE\time.h 61: int   tm_yday;
C:\Program\BC45\INCLUDE\time.h 62: int   tm_isdst;
C:\Program\BC45\INCLUDE\time.h 63: };
C:\Program\BC45\INCLUDE\time.h 64: 
C:\Program\BC45\INCLUDE\time.h 65: 
C:\Program\BC45\INCLUDE\time.h 66: extern "C" {
C:\Program\BC45\INCLUDE\time.h 67: 
C:\Program\BC45\INCLUDE\time.h 68: char  * __cdecl    asctime(const struct tm  *__tblock);
C:\Program\BC45\INCLUDE\time.h 69: char  * __cdecl    ctime(const time_t  *__time);
C:\Program\BC45\INCLUDE\time.h 70: double      __cdecl  difftime(time_t __time2, time_t __time1);
C:\Program\BC45\INCLUDE\time.h 71: struct tm  * __cdecl  gmtime(const time_t  *__timer);
C:\Program\BC45\INCLUDE\time.h 72: struct tm  * __cdecl  localtime(const time_t  *__timer);
C:\Program\BC45\INCLUDE\time.h 73: time_t      __cdecl  time(time_t  *__timer);
C:\Program\BC45\INCLUDE\time.h 74: time_t      __cdecl    mktime(struct tm  *__timeptr);
C:\Program\BC45\INCLUDE\time.h 75: clock_t     __cdecl  clock(void);
C:\Program\BC45\INCLUDE\time.h 76: size_t      __cdecl    strftime(char  *__s, size_t __maxsize,
C:\Program\BC45\INCLUDE\time.h 77: const char  *__fmt, const struct tm  *__t);
C:\Program\BC45\INCLUDE\time.h 78: size_t      __cdecl    _lstrftime(char  *__s, size_t __maxsize,
C:\Program\BC45\INCLUDE\time.h 79: const char  *__fmt, const struct tm  *__t);
C:\Program\BC45\INCLUDE\time.h 80: 
C:\Program\BC45\INCLUDE\time.h 81:   
C:\Program\BC45\INCLUDE\time.h 82: 
C:\Program\BC45\INCLUDE\time.h 83: 
C:\Program\BC45\INCLUDE\time.h 84: 
C:\Program\BC45\INCLUDE\time.h 85: 
C:\Program\BC45\INCLUDE\time.h 86: 
C:\Program\BC45\INCLUDE\time.h 87:   
C:\Program\BC45\INCLUDE\time.h 88: 
C:\Program\BC45\INCLUDE\time.h 89: extern int               __cdecl  _daylight;
C:\Program\BC45\INCLUDE\time.h 90: extern long              __cdecl  _timezone;
C:\Program\BC45\INCLUDE\time.h 91: extern char  * const __cdecl  _tzname[2];
C:\Program\BC45\INCLUDE\time.h 92: 
C:\Program\BC45\INCLUDE\time.h 93: 
C:\Program\BC45\INCLUDE\time.h 94: 
C:\Program\BC45\INCLUDE\time.h 95: 
C:\Program\BC45\INCLUDE\time.h 96: 
C:\Program\BC45\INCLUDE\time.h 97: 
C:\Program\BC45\INCLUDE\time.h 98: 
C:\Program\BC45\INCLUDE\time.h 99: 
C:\Program\BC45\INCLUDE\time.h 100: 
C:\Program\BC45\INCLUDE\time.h 101: 
C:\Program\BC45\INCLUDE\time.h 102: 
C:\Program\BC45\INCLUDE\time.h 103: 
C:\Program\BC45\INCLUDE\time.h 104: 
C:\Program\BC45\INCLUDE\time.h 105: int         __cdecl           stime(time_t  *__tp);
C:\Program\BC45\INCLUDE\time.h 106: void        __cdecl   tzset(void);
C:\Program\BC45\INCLUDE\time.h 107: char  * __cdecl   _strdate(char  *datestr);
C:\Program\BC45\INCLUDE\time.h 108: char  * __cdecl   _strtime(char  *timestr);
C:\Program\BC45\INCLUDE\time.h 109: 
C:\Program\BC45\INCLUDE\time.h 110: 
C:\Program\BC45\INCLUDE\time.h 111: }
C:\Program\BC45\INCLUDE\time.h 112: 
C:\Program\BC45\INCLUDE\time.h 113: 
C:\Program\BC45\INCLUDE\time.h 114: 
C:\Program\BC45\INCLUDE\time.h 115: 
C:\Program\BC45\INCLUDE\time.h 116: 
C:\Program\BC45\INCLUDE\time.h 117: 
C:\Program\BC45\INCLUDE\time.h 118: 
C:\Program\BC45\INCLUDE\time.h 119: 
C:\Program\BC45\INCLUDE\time.h 120: 
C:\Program\BC45\INCLUDE\time.h 121: 
C:\Program\BC45\INCLUDE\time.h 122: 
C:\Program\BC45\INCLUDE\time.h 123: 
C:\Program\BC45\INCLUDE\time.h 124: 
C:\Program\BC45\INCLUDE\time.h 125: 
C:\Program\BC45\INCLUDE\time.h 126: 
C:\Program\BC45\INCLUDE\time.h 127: 
C:\Program\BC45\INCLUDE\time.h 128: #pragma option -a. /* restore default packing */
C:\Program\BC45\INCLUDE\time.h 129: 
C:\Program\BC45\INCLUDE\time.h 130: 
C:\Program\BC45\INCLUDE\time.h 131: 
C:\Program\BC45\INCLUDE\time.h 132: 
C:\Program\BC45\INCLUDE\time.h 133: 
C:\Program\BC45\INCLUDE\time.h 134: 
C:\Program\BC45\INCLUDE\time.h 135: 
C:\Program\BC45\INCLUDE\time.h 136: 
C:\Program\BC45\INCLUDE\time.h 137: 
C:\Program\BC45\INCLUDE\time.h 138: 
C:\Program\BC45\INCLUDE\time.h 139: 
Dot.h 2: 
C:\Program\BC45\INCLUDE\stdlib.h 1: 
C:\Program\BC45\INCLUDE\stdlib.h 2: 
C:\Program\BC45\INCLUDE\stdlib.h 3: 
C:\Program\BC45\INCLUDE\stdlib.h 4: 
C:\Program\BC45\INCLUDE\stdlib.h 5: 
C:\Program\BC45\INCLUDE\stdlib.h 6: 
C:\Program\BC45\INCLUDE\stdlib.h 7: 
C:\Program\BC45\INCLUDE\stdlib.h 8: 
C:\Program\BC45\INCLUDE\stdlib.h 9: 
C:\Program\BC45\INCLUDE\stdlib.h 10: 
C:\Program\BC45\INCLUDE\stdlib.h 11: 
C:\Program\BC45\INCLUDE\stdlib.h 12: 
C:\Program\BC45\INCLUDE\stdlib.h 13: 
C:\Program\BC45\INCLUDE\stdlib.h 14: 
C:\Program\BC45\INCLUDE\stdlib.h 15: 
C:\Program\BC45\INCLUDE\stdlib.h 16: 
C:\Program\BC45\INCLUDE\stdlib.h 17: 
C:\Program\BC45\INCLUDE\stdlib.h 18: 
C:\Program\BC45\INCLUDE\stdlib.h 19: 
C:\Program\BC45\INCLUDE\stdlib.h 20: 
C:\Program\BC45\INCLUDE\stdlib.h 21: 
C:\Program\BC45\INCLUDE\stdlib.h 22: 
C:\Program\BC45\INCLUDE\stdlib.h 23: 
C:\Program\BC45\INCLUDE\_null.h 1: 
C:\Program\BC45\INCLUDE\_null.h 2: 
C:\Program\BC45\INCLUDE\_null.h 3: 
C:\Program\BC45\INCLUDE\_null.h 4: 
C:\Program\BC45\INCLUDE\_null.h 5: 
C:\Program\BC45\INCLUDE\_null.h 6: 
C:\Program\BC45\INCLUDE\_null.h 7: 
C:\Program\BC45\INCLUDE\_null.h 8: 
C:\Program\BC45\INCLUDE\_null.h 9: 
C:\Program\BC45\INCLUDE\_null.h 10: 
C:\Program\BC45\INCLUDE\_null.h 11: 
C:\Program\BC45\INCLUDE\_null.h 12: 
C:\Program\BC45\INCLUDE\_null.h 13: 
C:\Program\BC45\INCLUDE\_null.h 14: 
C:\Program\BC45\INCLUDE\_null.h 15: 
C:\Program\BC45\INCLUDE\_null.h 16: 
C:\Program\BC45\INCLUDE\_null.h 17:     
C:\Program\BC45\INCLUDE\_null.h 18: 
C:\Program\BC45\INCLUDE\_null.h 19: 
C:\Program\BC45\INCLUDE\_null.h 20: 
C:\Program\BC45\INCLUDE\_null.h 21: 
C:\Program\BC45\INCLUDE\_null.h 22: 
C:\Program\BC45\INCLUDE\_null.h 23: 
C:\Program\BC45\INCLUDE\_null.h 24: 
C:\Program\BC45\INCLUDE\_null.h 25: 
C:\Program\BC45\INCLUDE\_null.h 26: 
C:\Program\BC45\INCLUDE\_null.h 27: 
C:\Program\BC45\INCLUDE\_null.h 28: 
C:\Program\BC45\INCLUDE\_null.h 29: 
C:\Program\BC45\INCLUDE\_null.h 30: 
C:\Program\BC45\INCLUDE\_null.h 31: 
C:\Program\BC45\INCLUDE\_null.h 32: 
C:\Program\BC45\INCLUDE\stdlib.h 24: 
C:\Program\BC45\INCLUDE\stdlib.h 25: 
C:\Program\BC45\INCLUDE\stdlib.h 26: 
C:\Program\BC45\INCLUDE\stdlib.h 27: 
C:\Program\BC45\INCLUDE\stdlib.h 28: 
C:\Program\BC45\INCLUDE\stdlib.h 29: 
C:\Program\BC45\INCLUDE\stdlib.h 30: 
C:\Program\BC45\INCLUDE\stdlib.h 31: 
C:\Program\BC45\INCLUDE\stdlib.h 32: 
C:\Program\BC45\INCLUDE\stdlib.h 33: #pragma option -a-
C:\Program\BC45\INCLUDE\stdlib.h 34: 
C:\Program\BC45\INCLUDE\stdlib.h 35: 
C:\Program\BC45\INCLUDE\stdlib.h 36: 
C:\Program\BC45\INCLUDE\stdlib.h 37: 
C:\Program\BC45\INCLUDE\stdlib.h 38: 
C:\Program\BC45\INCLUDE\stdlib.h 39: 
C:\Program\BC45\INCLUDE\stdlib.h 40: 
C:\Program\BC45\INCLUDE\stdlib.h 41: 
C:\Program\BC45\INCLUDE\stdlib.h 42: 
C:\Program\BC45\INCLUDE\stdlib.h 43: 
C:\Program\BC45\INCLUDE\stdlib.h 44: 
C:\Program\BC45\INCLUDE\stdlib.h 45: typedef struct {
C:\Program\BC45\INCLUDE\stdlib.h 46: int     quot;
C:\Program\BC45\INCLUDE\stdlib.h 47: int     rem;
C:\Program\BC45\INCLUDE\stdlib.h 48: } div_t;
C:\Program\BC45\INCLUDE\stdlib.h 49: 
C:\Program\BC45\INCLUDE\stdlib.h 50: 
C:\Program\BC45\INCLUDE\stdlib.h 51: 
C:\Program\BC45\INCLUDE\stdlib.h 52: 
C:\Program\BC45\INCLUDE\stdlib.h 53: typedef struct {
C:\Program\BC45\INCLUDE\stdlib.h 54: long    quot;
C:\Program\BC45\INCLUDE\stdlib.h 55: long    rem;
C:\Program\BC45\INCLUDE\stdlib.h 56: } ldiv_t;
C:\Program\BC45\INCLUDE\stdlib.h 57: 
C:\Program\BC45\INCLUDE\stdlib.h 58: 
C:\Program\BC45\INCLUDE\stdlib.h 59: 
C:\Program\BC45\INCLUDE\stdlib.h 60: 
C:\Program\BC45\INCLUDE\stdlib.h 61: 
C:\Program\BC45\INCLUDE\stdlib.h 62: 
C:\Program\BC45\INCLUDE\stdlib.h 63: 
C:\Program\BC45\INCLUDE\stdlib.h 64: 
C:\Program\BC45\INCLUDE\stdlib.h 65: 
C:\Program\BC45\INCLUDE\stdlib.h 66: 
C:\Program\BC45\INCLUDE\stdlib.h 67: 
C:\Program\BC45\INCLUDE\stdlib.h 68: 
C:\Program\BC45\INCLUDE\stdlib.h 69: 
C:\Program\BC45\INCLUDE\stdlib.h 70: 
C:\Program\BC45\INCLUDE\stdlib.h 71: 
C:\Program\BC45\INCLUDE\stdlib.h 72: 
C:\Program\BC45\INCLUDE\stdlib.h 73: 
C:\Program\BC45\INCLUDE\stdlib.h 74: 
C:\Program\BC45\INCLUDE\stdlib.h 75: typedef void (__cdecl * atexit_t)(void);
C:\Program\BC45\INCLUDE\stdlib.h 76: 
C:\Program\BC45\INCLUDE\stdlib.h 77: 
C:\Program\BC45\INCLUDE\stdlib.h 78: 
C:\Program\BC45\INCLUDE\stdlib.h 79: 
C:\Program\BC45\INCLUDE\stdlib.h 80: 
C:\Program\BC45\INCLUDE\stdlib.h 81: 
C:\Program\BC45\INCLUDE\stdlib.h 82: 
C:\Program\BC45\INCLUDE\stdlib.h 83: 
C:\Program\BC45\INCLUDE\stdlib.h 84: 
C:\Program\BC45\INCLUDE\stdlib.h 85: 
C:\Program\BC45\INCLUDE\stdlib.h 86: 
C:\Program\BC45\INCLUDE\stdlib.h 87: 
C:\Program\BC45\INCLUDE\stdlib.h 88: extern "C" {
C:\Program\BC45\INCLUDE\stdlib.h 89: 
C:\Program\BC45\INCLUDE\stdlib.h 90: 
C:\Program\BC45\INCLUDE\stdlib.h 91: void        __cdecl abort(void);
C:\Program\BC45\INCLUDE\stdlib.h 92: 
C:\Program\BC45\INCLUDE\stdlib.h 93: 
C:\Program\BC45\INCLUDE\stdlib.h 94: 
C:\Program\BC45\INCLUDE\stdlib.h 95: 
C:\Program\BC45\INCLUDE\stdlib.h 96: int         __cdecl __abs__(int);
C:\Program\BC45\INCLUDE\stdlib.h 97: 
C:\Program\BC45\INCLUDE\stdlib.h 98: inline int __cdecl  abs(int __x) { return __abs__(__x); }
C:\Program\BC45\INCLUDE\stdlib.h 99: 
C:\Program\BC45\INCLUDE\stdlib.h 100: 
C:\Program\BC45\INCLUDE\stdlib.h 101: 
C:\Program\BC45\INCLUDE\stdlib.h 102: 
C:\Program\BC45\INCLUDE\stdlib.h 103: 
C:\Program\BC45\INCLUDE\stdlib.h 104: 
C:\Program\BC45\INCLUDE\stdlib.h 105: 
C:\Program\BC45\INCLUDE\stdlib.h 106: int         __cdecl  atexit(void (__cdecl *__func)(void));
C:\Program\BC45\INCLUDE\stdlib.h 107: double      __cdecl  atof(const char  *__s);
C:\Program\BC45\INCLUDE\stdlib.h 108: int         __cdecl atoi(const char  *__s);
C:\Program\BC45\INCLUDE\stdlib.h 109: long        __cdecl atol(const char  *__s);
C:\Program\BC45\INCLUDE\stdlib.h 110: void  * __cdecl bsearch(const void  *__key, const void  *__base,
C:\Program\BC45\INCLUDE\stdlib.h 111: size_t __nelem, size_t __width,
C:\Program\BC45\INCLUDE\stdlib.h 112: int (__cdecl *fcmp)(const void  *,
C:\Program\BC45\INCLUDE\stdlib.h 113: const void  *));
C:\Program\BC45\INCLUDE\stdlib.h 114: void  * __cdecl  calloc(size_t __nitems, size_t __size);
C:\Program\BC45\INCLUDE\stdlib.h 115: div_t       __cdecl  div(int __numer, int __denom);
C:\Program\BC45\INCLUDE\stdlib.h 116: void        __cdecl  exit(int __status);
C:\Program\BC45\INCLUDE\stdlib.h 117: void        __cdecl  free(void  *__block);
C:\Program\BC45\INCLUDE\stdlib.h 118: char  * __cdecl getenv(const char  *__name);
C:\Program\BC45\INCLUDE\stdlib.h 119: long        __cdecl  labs(long __x);
C:\Program\BC45\INCLUDE\stdlib.h 120: ldiv_t      __cdecl  ldiv(long __numer, long __denom);
C:\Program\BC45\INCLUDE\stdlib.h 121: void  * __cdecl  malloc(size_t __size);
C:\Program\BC45\INCLUDE\stdlib.h 122: int         __cdecl  mblen(const char  *__s, size_t __n);
C:\Program\BC45\INCLUDE\stdlib.h 123: size_t      __cdecl  mbstowcs(wchar_t  *__pwcs, const char  *__s,
C:\Program\BC45\INCLUDE\stdlib.h 124: size_t __n);
C:\Program\BC45\INCLUDE\stdlib.h 125: int         __cdecl  mbtowc(wchar_t  *__pwc, const char  *__s, size_t __n);
C:\Program\BC45\INCLUDE\stdlib.h 126: void        __cdecl  qsort(void  *__base, size_t __nelem, size_t __width,
C:\Program\BC45\INCLUDE\stdlib.h 127: int __cdecl (* __fcmp)(const void  *, const void  *));
C:\Program\BC45\INCLUDE\stdlib.h 128: int         __cdecl  rand(void);
C:\Program\BC45\INCLUDE\stdlib.h 129: void   *__cdecl  realloc(void  *__block, size_t __size);
C:\Program\BC45\INCLUDE\stdlib.h 130: void        __cdecl  srand(unsigned __seed);
C:\Program\BC45\INCLUDE\stdlib.h 131: double      __cdecl  strtod(const char  *__s, char  * *__endptr);
C:\Program\BC45\INCLUDE\stdlib.h 132: long        __cdecl  strtol(const char  *__s, char  * *__endptr,
C:\Program\BC45\INCLUDE\stdlib.h 133: int __radix);
C:\Program\BC45\INCLUDE\stdlib.h 134: long double __cdecl  _strtold(const char  *__s, char  * *__endptr);
C:\Program\BC45\INCLUDE\stdlib.h 135: unsigned long __cdecl  strtoul(const char  *__s, char  * *__endptr,
C:\Program\BC45\INCLUDE\stdlib.h 136: int __radix);
C:\Program\BC45\INCLUDE\stdlib.h 137: int         __cdecl  system(const char  *__command);
C:\Program\BC45\INCLUDE\stdlib.h 138: size_t      __cdecl  wcstombs(char  *__s, const wchar_t  *__pwcs,
C:\Program\BC45\INCLUDE\stdlib.h 139: size_t __n);
C:\Program\BC45\INCLUDE\stdlib.h 140: int         __cdecl  wctomb(char  *__s, wchar_t __wc);
C:\Program\BC45\INCLUDE\stdlib.h 141: 
C:\Program\BC45\INCLUDE\stdlib.h 142: 
C:\Program\BC45\INCLUDE\stdlib.h 143: }
C:\Program\BC45\INCLUDE\stdlib.h 144: 
C:\Program\BC45\INCLUDE\stdlib.h 145: 
C:\Program\BC45\INCLUDE\stdlib.h 146: extern  unsigned        __cdecl _psp;
C:\Program\BC45\INCLUDE\stdlib.h 147: 
C:\Program\BC45\INCLUDE\stdlib.h 148:  
C:\Program\BC45\INCLUDE\stdlib.h 149: 
C:\Program\BC45\INCLUDE\stdlib.h 150: 
C:\Program\BC45\INCLUDE\stdlib.h 151: 
C:\Program\BC45\INCLUDE\stdlib.h 152: extern  char          **__cdecl _environ;
C:\Program\BC45\INCLUDE\stdlib.h 153: extern  int             __cdecl _fmode;
C:\Program\BC45\INCLUDE\stdlib.h 154: extern  unsigned char   __cdecl _osmajor;
C:\Program\BC45\INCLUDE\stdlib.h 155: extern  unsigned char   __cdecl _osminor;
C:\Program\BC45\INCLUDE\stdlib.h 156: extern  unsigned int    __cdecl _version;
C:\Program\BC45\INCLUDE\stdlib.h 157: 
C:\Program\BC45\INCLUDE\stdlib.h 158: 
C:\Program\BC45\INCLUDE\stdlib.h 159: 
C:\Program\BC45\INCLUDE\stdlib.h 160: 
C:\Program\BC45\INCLUDE\stdlib.h 161: 
C:\Program\BC45\INCLUDE\stdlib.h 162: 
C:\Program\BC45\INCLUDE\stdlib.h 163: 
C:\Program\BC45\INCLUDE\stdlib.h 164: 
C:\Program\BC45\INCLUDE\stdlib.h 165: 
C:\Program\BC45\INCLUDE\stdlib.h 166: 
C:\Program\BC45\INCLUDE\stdlib.h 167: 
C:\Program\BC45\INCLUDE\stdlib.h 168: 
C:\Program\BC45\INCLUDE\stdlib.h 169: 
C:\Program\BC45\INCLUDE\stdlib.h 170: 
C:\Program\BC45\INCLUDE\stdlib.h 171: 
C:\Program\BC45\INCLUDE\stdlib.h 172: 
C:\Program\BC45\INCLUDE\stdlib.h 173: 
C:\Program\BC45\INCLUDE\stdlib.h 174: 
C:\Program\BC45\INCLUDE\stdlib.h 175: 
C:\Program\BC45\INCLUDE\stdlib.h 176: 
C:\Program\BC45\INCLUDE\stdlib.h 177: 
C:\Program\BC45\INCLUDE\stdlib.h 178: extern  char       *__cdecl _sys_errlist[];
C:\Program\BC45\INCLUDE\stdlib.h 179: extern  int             __cdecl _sys_nerr;
C:\Program\BC45\INCLUDE\stdlib.h 180: 
C:\Program\BC45\INCLUDE\stdlib.h 181: 
C:\Program\BC45\INCLUDE\stdlib.h 182: 
C:\Program\BC45\INCLUDE\stdlib.h 183: 
C:\Program\BC45\INCLUDE\stdlib.h 184: 
C:\Program\BC45\INCLUDE\stdlib.h 185: inline int  __cdecl atoi(const char  *__s) { return (int) atol(__s); }
C:\Program\BC45\INCLUDE\stdlib.h 186: 
C:\Program\BC45\INCLUDE\stdlib.h 187: 
C:\Program\BC45\INCLUDE\stdlib.h 188: 
C:\Program\BC45\INCLUDE\stdlib.h 189: 
C:\Program\BC45\INCLUDE\stdlib.h 190: 
C:\Program\BC45\INCLUDE\stdlib.h 191: 
C:\Program\BC45\INCLUDE\stdlib.h 192: 
C:\Program\BC45\INCLUDE\stdlib.h 193: 
C:\Program\BC45\INCLUDE\stdlib.h 194: 
C:\Program\BC45\INCLUDE\stdlib.h 195: 
C:\Program\BC45\INCLUDE\stdlib.h 196: 
C:\Program\BC45\INCLUDE\stdlib.h 197: 
C:\Program\BC45\INCLUDE\stdlib.h 198: 
C:\Program\BC45\INCLUDE\stdlib.h 199: 
C:\Program\BC45\INCLUDE\stdlib.h 200: extern "C" {
C:\Program\BC45\INCLUDE\stdlib.h 201: 
C:\Program\BC45\INCLUDE\stdlib.h 202: 
C:\Program\BC45\INCLUDE\stdlib.h 203: long double    __cdecl   _atold(const char  *__s);
C:\Program\BC45\INCLUDE\stdlib.h 204: unsigned char  __cdecl   _crotl(unsigned char __value, int __count);
C:\Program\BC45\INCLUDE\stdlib.h 205: unsigned char  __cdecl   _crotr(unsigned char __value, int __count);
C:\Program\BC45\INCLUDE\stdlib.h 206: char      *__cdecl   ecvt(double __value, int __ndig, int  *__dec,
C:\Program\BC45\INCLUDE\stdlib.h 207: int  *__sign);
C:\Program\BC45\INCLUDE\stdlib.h 208: void           __cdecl   _exit(int __status);
C:\Program\BC45\INCLUDE\stdlib.h 209: char      *__cdecl   fcvt(double __value, int __ndig, int  *__dec,
C:\Program\BC45\INCLUDE\stdlib.h 210: int  *__sign);
C:\Program\BC45\INCLUDE\stdlib.h 211: char      *__cdecl   _fullpath( char  *__buf,
C:\Program\BC45\INCLUDE\stdlib.h 212: const char  *__path,
C:\Program\BC45\INCLUDE\stdlib.h 213: size_t __maxlen );
C:\Program\BC45\INCLUDE\stdlib.h 214: char      *__cdecl   gcvt(double __value, int __ndec, char  *__buf);
C:\Program\BC45\INCLUDE\stdlib.h 215: char      *__cdecl   itoa(int __value, char  *__string, int __radix);
C:\Program\BC45\INCLUDE\stdlib.h 216: void      *__cdecl    lfind(const void  *__key, const void  *__base,
C:\Program\BC45\INCLUDE\stdlib.h 217: size_t  *__num, size_t __width,
C:\Program\BC45\INCLUDE\stdlib.h 218: int __cdecl(* __fcmp)(const void  *,
C:\Program\BC45\INCLUDE\stdlib.h 219: const void  *));
C:\Program\BC45\INCLUDE\stdlib.h 220: unsigned long  __cdecl   _lrotl(unsigned long __val, int __count);
C:\Program\BC45\INCLUDE\stdlib.h 221: unsigned long  __cdecl   _lrotr(unsigned long __val, int __count);
C:\Program\BC45\INCLUDE\stdlib.h 222: 
C:\Program\BC45\INCLUDE\stdlib.h 223: void      *__cdecl    lsearch(const void  *__key, void  *__base,
C:\Program\BC45\INCLUDE\stdlib.h 224: size_t  *__num, size_t __width,
C:\Program\BC45\INCLUDE\stdlib.h 225: int __cdecl(* __fcmp)(const void  *, const void  *));
C:\Program\BC45\INCLUDE\stdlib.h 226: char      *__cdecl   ltoa(long __value, char  *__string, int __radix);
C:\Program\BC45\INCLUDE\stdlib.h 227: void           __cdecl    _makepath( char  *__path,
C:\Program\BC45\INCLUDE\stdlib.h 228: const char  *__drive,
C:\Program\BC45\INCLUDE\stdlib.h 229: const char  *__dir,
C:\Program\BC45\INCLUDE\stdlib.h 230: const char  *__name,
C:\Program\BC45\INCLUDE\stdlib.h 231: const char  *__ext );
C:\Program\BC45\INCLUDE\stdlib.h 232: int            __cdecl    putenv(const char  *__name);
C:\Program\BC45\INCLUDE\stdlib.h 233: 
C:\Program\BC45\INCLUDE\stdlib.h 234: unsigned       __cdecl   _rotl(unsigned __value, int __count);
C:\Program\BC45\INCLUDE\stdlib.h 235: unsigned       __cdecl   _rotr(unsigned __value, int __count);
C:\Program\BC45\INCLUDE\stdlib.h 236: 
C:\Program\BC45\INCLUDE\stdlib.h 237: unsigned       __cdecl   __rotl__(unsigned __value, int __count);     
C:\Program\BC45\INCLUDE\stdlib.h 238: unsigned       __cdecl   __rotr__(unsigned __value, int __count);     
C:\Program\BC45\INCLUDE\stdlib.h 239: 
C:\Program\BC45\INCLUDE\stdlib.h 240: void           __cdecl   _searchenv(const char  *__file,
C:\Program\BC45\INCLUDE\stdlib.h 241: const char  *__varname,
C:\Program\BC45\INCLUDE\stdlib.h 242: char  *__pathname);
C:\Program\BC45\INCLUDE\stdlib.h 243: void           __cdecl   _searchstr(const char  *__file,
C:\Program\BC45\INCLUDE\stdlib.h 244: const char  *__ipath,
C:\Program\BC45\INCLUDE\stdlib.h 245: char  *__pathname);
C:\Program\BC45\INCLUDE\stdlib.h 246: void           __cdecl    _splitpath( const char  *__path,
C:\Program\BC45\INCLUDE\stdlib.h 247: char  *__drive,
C:\Program\BC45\INCLUDE\stdlib.h 248: char  *__dir,
C:\Program\BC45\INCLUDE\stdlib.h 249: char  *__name,
C:\Program\BC45\INCLUDE\stdlib.h 250: char  *__ext );
C:\Program\BC45\INCLUDE\stdlib.h 251: void           __cdecl    swab(char  *__from, char  *__to, int __nbytes);
C:\Program\BC45\INCLUDE\stdlib.h 252: char      *__cdecl   ultoa(unsigned long __value, char  *__string,
C:\Program\BC45\INCLUDE\stdlib.h 253: int __radix);
C:\Program\BC45\INCLUDE\stdlib.h 254: 
C:\Program\BC45\INCLUDE\stdlib.h 255: 
C:\Program\BC45\INCLUDE\stdlib.h 256: }
C:\Program\BC45\INCLUDE\stdlib.h 257: 
C:\Program\BC45\INCLUDE\stdlib.h 258: 
C:\Program\BC45\INCLUDE\stdlib.h 259: 
C:\Program\BC45\INCLUDE\stdlib.h 260: 
C:\Program\BC45\INCLUDE\stdlib.h 261: 
C:\Program\BC45\INCLUDE\stdlib.h 262: 
C:\Program\BC45\INCLUDE\stdlib.h 263: 
C:\Program\BC45\INCLUDE\stdlib.h 264: 
C:\Program\BC45\INCLUDE\stdlib.h 265:   
C:\Program\BC45\INCLUDE\stdlib.h 266: 
C:\Program\BC45\INCLUDE\stdlib.h 267: 
C:\Program\BC45\INCLUDE\stdlib.h 268: 
C:\Program\BC45\INCLUDE\stdlib.h 269: 
C:\Program\BC45\INCLUDE\stdlib.h 270: 
C:\Program\BC45\INCLUDE\stdlib.h 271: 
C:\Program\BC45\INCLUDE\stdlib.h 272: 
C:\Program\BC45\INCLUDE\stdlib.h 273: 
C:\Program\BC45\INCLUDE\stdlib.h 274: 
C:\Program\BC45\INCLUDE\stdlib.h 275: 
C:\Program\BC45\INCLUDE\stdlib.h 276: 
C:\Program\BC45\INCLUDE\stdlib.h 277: 
C:\Program\BC45\INCLUDE\stdlib.h 278: 
C:\Program\BC45\INCLUDE\stdlib.h 279: 
C:\Program\BC45\INCLUDE\stdlib.h 280: 
C:\Program\BC45\INCLUDE\stdlib.h 281: 
C:\Program\BC45\INCLUDE\stdlib.h 282: 
C:\Program\BC45\INCLUDE\stdlib.h 283: 
C:\Program\BC45\INCLUDE\stdlib.h 284: extern  int   __cdecl _doserrno;
C:\Program\BC45\INCLUDE\stdlib.h 285: extern  int   __cdecl errno;
C:\Program\BC45\INCLUDE\stdlib.h 286: 
C:\Program\BC45\INCLUDE\stdlib.h 287: 
C:\Program\BC45\INCLUDE\stdlib.h 288: 
C:\Program\BC45\INCLUDE\stdlib.h 289: 
C:\Program\BC45\INCLUDE\stdlib.h 290: 
C:\Program\BC45\INCLUDE\stdlib.h 291: 
C:\Program\BC45\INCLUDE\stdlib.h 292: inline int __cdecl     random(int __num)
C:\Program\BC45\INCLUDE\stdlib.h 293: { return(int)(((long)rand()*__num)/(0x7FFFU+1)); }
C:\Program\BC45\INCLUDE\stdlib.h 294: 
C:\Program\BC45\INCLUDE\stdlib.h 295: 
C:\Program\BC45\INCLUDE\stdlib.h 296: 
C:\Program\BC45\INCLUDE\stdlib.h 297: 
C:\Program\BC45\INCLUDE\stdlib.h 298: 
C:\Program\BC45\INCLUDE\stdlib.h 299: 
C:\Program\BC45\INCLUDE\stdlib.h 300: 
C:\Program\BC45\INCLUDE\stdlib.h 301: 
C:\Program\BC45\INCLUDE\stdlib.h 302: 
C:\Program\BC45\INCLUDE\stdlib.h 303: 
C:\Program\BC45\INCLUDE\stdlib.h 304: 
C:\Program\BC45\INCLUDE\stdlib.h 305: 
C:\Program\BC45\INCLUDE\stdlib.h 306: 
C:\Program\BC45\INCLUDE\stdlib.h 307: 
C:\Program\BC45\INCLUDE\stdlib.h 308: 
C:\Program\BC45\INCLUDE\stdlib.h 309: 
C:\Program\BC45\INCLUDE\stdlib.h 310: 
C:\Program\BC45\INCLUDE\stdlib.h 311: 
C:\Program\BC45\INCLUDE\stdlib.h 312: 
C:\Program\BC45\INCLUDE\stdlib.h 313: 
C:\Program\BC45\INCLUDE\stdlib.h 314: 
C:\Program\BC45\INCLUDE\stdlib.h 315: 
C:\Program\BC45\INCLUDE\stdlib.h 316: 
C:\Program\BC45\INCLUDE\stdlib.h 317: 
C:\Program\BC45\INCLUDE\stdlib.h 318: 
C:\Program\BC45\INCLUDE\stdlib.h 319: 
C:\Program\BC45\INCLUDE\stdlib.h 320: 
C:\Program\BC45\INCLUDE\stdlib.h 321: 
C:\Program\BC45\INCLUDE\stdlib.h 322: 
C:\Program\BC45\INCLUDE\stdlib.h 323: 
C:\Program\BC45\INCLUDE\stdlib.h 324: 
C:\Program\BC45\INCLUDE\stdlib.h 325: 
C:\Program\BC45\INCLUDE\stdlib.h 326: 
C:\Program\BC45\INCLUDE\stdlib.h 327: 
C:\Program\BC45\INCLUDE\stdlib.h 328: 
C:\Program\BC45\INCLUDE\stdlib.h 329: 
C:\Program\BC45\INCLUDE\stdlib.h 330: 
C:\Program\BC45\INCLUDE\stdlib.h 331: 
C:\Program\BC45\INCLUDE\stdlib.h 332: 
C:\Program\BC45\INCLUDE\stdlib.h 333: 
C:\Program\BC45\INCLUDE\stdlib.h 334: 
C:\Program\BC45\INCLUDE\stdlib.h 335: 
C:\Program\BC45\INCLUDE\stdlib.h 336: 
C:\Program\BC45\INCLUDE\stdlib.h 337: 
C:\Program\BC45\INCLUDE\stdlib.h 338: 
C:\Program\BC45\INCLUDE\stdlib.h 339: 
C:\Program\BC45\INCLUDE\stdlib.h 340: 
C:\Program\BC45\INCLUDE\stdlib.h 341: 
C:\Program\BC45\INCLUDE\stdlib.h 342: 
C:\Program\BC45\INCLUDE\stdlib.h 343: 
C:\Program\BC45\INCLUDE\stdlib.h 344: 
C:\Program\BC45\INCLUDE\stdlib.h 345: 
C:\Program\BC45\INCLUDE\stdlib.h 346: 
C:\Program\BC45\INCLUDE\stdlib.h 347: 
C:\Program\BC45\INCLUDE\stdlib.h 348: 
C:\Program\BC45\INCLUDE\stdlib.h 349: 
C:\Program\BC45\INCLUDE\stdlib.h 350: 
C:\Program\BC45\INCLUDE\stdlib.h 351: 
C:\Program\BC45\INCLUDE\stdlib.h 352: 
C:\Program\BC45\INCLUDE\stdlib.h 353: 
C:\Program\BC45\INCLUDE\stdlib.h 354: 
C:\Program\BC45\INCLUDE\stdlib.h 355: 
C:\Program\BC45\INCLUDE\stdlib.h 356: 
C:\Program\BC45\INCLUDE\stdlib.h 357: 
C:\Program\BC45\INCLUDE\stdlib.h 358: 
C:\Program\BC45\INCLUDE\stdlib.h 359: 
C:\Program\BC45\INCLUDE\stdlib.h 360: 
C:\Program\BC45\INCLUDE\stdlib.h 361: 
C:\Program\BC45\INCLUDE\stdlib.h 362: 
C:\Program\BC45\INCLUDE\stdlib.h 363: 
C:\Program\BC45\INCLUDE\stdlib.h 364: 
C:\Program\BC45\INCLUDE\stdlib.h 365: 
C:\Program\BC45\INCLUDE\stdlib.h 366: 
C:\Program\BC45\INCLUDE\stdlib.h 367: 
C:\Program\BC45\INCLUDE\stdlib.h 368: 
C:\Program\BC45\INCLUDE\stdlib.h 369: 
C:\Program\BC45\INCLUDE\stdlib.h 370: 
C:\Program\BC45\INCLUDE\stdlib.h 371: 
C:\Program\BC45\INCLUDE\stdlib.h 372: 
C:\Program\BC45\INCLUDE\stdlib.h 373: 
C:\Program\BC45\INCLUDE\stdlib.h 374: 
C:\Program\BC45\INCLUDE\stdlib.h 375: 
C:\Program\BC45\INCLUDE\stdlib.h 376: 
C:\Program\BC45\INCLUDE\stdlib.h 377: 
C:\Program\BC45\INCLUDE\stdlib.h 378: 
C:\Program\BC45\INCLUDE\stdlib.h 379: 
C:\Program\BC45\INCLUDE\stdlib.h 380: 
C:\Program\BC45\INCLUDE\stdlib.h 381: 
C:\Program\BC45\INCLUDE\stdlib.h 382: 
C:\Program\BC45\INCLUDE\stdlib.h 383: 
C:\Program\BC45\INCLUDE\stdlib.h 384: 
C:\Program\BC45\INCLUDE\stdlib.h 385: 
C:\Program\BC45\INCLUDE\stdlib.h 386: 
C:\Program\BC45\INCLUDE\stdlib.h 387: 
C:\Program\BC45\INCLUDE\stdlib.h 388: 
C:\Program\BC45\INCLUDE\stdlib.h 389: 
C:\Program\BC45\INCLUDE\stdlib.h 390: 
C:\Program\BC45\INCLUDE\stdlib.h 391: 
C:\Program\BC45\INCLUDE\stdlib.h 392: 
C:\Program\BC45\INCLUDE\stdlib.h 393: 
C:\Program\BC45\INCLUDE\stdlib.h 394: 
C:\Program\BC45\INCLUDE\stdlib.h 395: 
C:\Program\BC45\INCLUDE\stdlib.h 396: 
C:\Program\BC45\INCLUDE\stdlib.h 397: 
C:\Program\BC45\INCLUDE\stdlib.h 398: 
C:\Program\BC45\INCLUDE\stdlib.h 399: 
C:\Program\BC45\INCLUDE\stdlib.h 400: 
C:\Program\BC45\INCLUDE\stdlib.h 401: 
C:\Program\BC45\INCLUDE\stdlib.h 402: 
C:\Program\BC45\INCLUDE\stdlib.h 403: 
C:\Program\BC45\INCLUDE\stdlib.h 404: 
C:\Program\BC45\INCLUDE\stdlib.h 405: 
C:\Program\BC45\INCLUDE\stdlib.h 406: 
C:\Program\BC45\INCLUDE\stdlib.h 407: 
C:\Program\BC45\INCLUDE\stdlib.h 408: 
C:\Program\BC45\INCLUDE\stdlib.h 409: 
C:\Program\BC45\INCLUDE\stdlib.h 410: 
C:\Program\BC45\INCLUDE\stdlib.h 411: 
C:\Program\BC45\INCLUDE\stdlib.h 412: 
C:\Program\BC45\INCLUDE\stdlib.h 413: 
C:\Program\BC45\INCLUDE\stdlib.h 414: 
C:\Program\BC45\INCLUDE\stdlib.h 415: 
C:\Program\BC45\INCLUDE\stdlib.h 416: 
C:\Program\BC45\INCLUDE\stdlib.h 417: 
C:\Program\BC45\INCLUDE\stdlib.h 418: 
C:\Program\BC45\INCLUDE\stdlib.h 419: 
C:\Program\BC45\INCLUDE\stdlib.h 420: 
C:\Program\BC45\INCLUDE\stdlib.h 421: 
C:\Program\BC45\INCLUDE\stdlib.h 422: 
C:\Program\BC45\INCLUDE\stdlib.h 423: 
C:\Program\BC45\INCLUDE\stdlib.h 424: 
C:\Program\BC45\INCLUDE\stdlib.h 425: 
C:\Program\BC45\INCLUDE\stdlib.h 426: 
C:\Program\BC45\INCLUDE\stdlib.h 427: 
C:\Program\BC45\INCLUDE\stdlib.h 428: 
C:\Program\BC45\INCLUDE\stdlib.h 429: 
C:\Program\BC45\INCLUDE\stdlib.h 430: 
C:\Program\BC45\INCLUDE\stdlib.h 431: 
C:\Program\BC45\INCLUDE\stdlib.h 432: 
C:\Program\BC45\INCLUDE\stdlib.h 433: 
C:\Program\BC45\INCLUDE\stdlib.h 434: 
C:\Program\BC45\INCLUDE\stdlib.h 435: 
C:\Program\BC45\INCLUDE\stdlib.h 436: 
C:\Program\BC45\INCLUDE\stdlib.h 437: 
C:\Program\BC45\INCLUDE\stdlib.h 438: 
C:\Program\BC45\INCLUDE\stdlib.h 439: 
C:\Program\BC45\INCLUDE\stdlib.h 440: 
C:\Program\BC45\INCLUDE\stdlib.h 441: 
C:\Program\BC45\INCLUDE\stdlib.h 442: 
C:\Program\BC45\INCLUDE\stdlib.h 443: 
C:\Program\BC45\INCLUDE\stdlib.h 444: 
C:\Program\BC45\INCLUDE\stdlib.h 445: 
C:\Program\BC45\INCLUDE\stdlib.h 446: 
C:\Program\BC45\INCLUDE\stdlib.h 447: 
C:\Program\BC45\INCLUDE\stdlib.h 448: 
C:\Program\BC45\INCLUDE\stdlib.h 449: 
C:\Program\BC45\INCLUDE\stdlib.h 450: 
C:\Program\BC45\INCLUDE\stdlib.h 451: 
C:\Program\BC45\INCLUDE\stdlib.h 452: 
C:\Program\BC45\INCLUDE\stdlib.h 453: 
C:\Program\BC45\INCLUDE\stdlib.h 454: 
C:\Program\BC45\INCLUDE\stdlib.h 455: 
C:\Program\BC45\INCLUDE\stdlib.h 456: 
C:\Program\BC45\INCLUDE\stdlib.h 457: 
C:\Program\BC45\INCLUDE\stdlib.h 458: 
C:\Program\BC45\INCLUDE\stdlib.h 459: 
C:\Program\BC45\INCLUDE\stdlib.h 460: 
C:\Program\BC45\INCLUDE\stdlib.h 461: 
C:\Program\BC45\INCLUDE\stdlib.h 462: 
C:\Program\BC45\INCLUDE\stdlib.h 463: 
C:\Program\BC45\INCLUDE\stdlib.h 464: 
C:\Program\BC45\INCLUDE\stdlib.h 465: 
C:\Program\BC45\INCLUDE\stdlib.h 466: 
C:\Program\BC45\INCLUDE\stdlib.h 467: 
C:\Program\BC45\INCLUDE\stdlib.h 468: 
C:\Program\BC45\INCLUDE\stdlib.h 469: 
C:\Program\BC45\INCLUDE\stdlib.h 470: 
C:\Program\BC45\INCLUDE\stdlib.h 471: 
C:\Program\BC45\INCLUDE\stdlib.h 472: 
C:\Program\BC45\INCLUDE\stdlib.h 473: 
C:\Program\BC45\INCLUDE\stdlib.h 474: 
C:\Program\BC45\INCLUDE\stdlib.h 475: 
C:\Program\BC45\INCLUDE\stdlib.h 476: 
C:\Program\BC45\INCLUDE\stdlib.h 477: 
C:\Program\BC45\INCLUDE\stdlib.h 478: 
C:\Program\BC45\INCLUDE\stdlib.h 479: 
C:\Program\BC45\INCLUDE\stdlib.h 480: 
C:\Program\BC45\INCLUDE\stdlib.h 481: 
C:\Program\BC45\INCLUDE\stdlib.h 482: 
C:\Program\BC45\INCLUDE\stdlib.h 483: 
C:\Program\BC45\INCLUDE\stdlib.h 484: 
C:\Program\BC45\INCLUDE\stdlib.h 485: 
C:\Program\BC45\INCLUDE\stdlib.h 486: 
C:\Program\BC45\INCLUDE\stdlib.h 487: 
C:\Program\BC45\INCLUDE\stdlib.h 488: 
C:\Program\BC45\INCLUDE\stdlib.h 489: 
C:\Program\BC45\INCLUDE\stdlib.h 490: 
C:\Program\BC45\INCLUDE\stdlib.h 491: 
C:\Program\BC45\INCLUDE\stdlib.h 492: 
C:\Program\BC45\INCLUDE\stdlib.h 493: 
C:\Program\BC45\INCLUDE\stdlib.h 494: 
C:\Program\BC45\INCLUDE\stdlib.h 495: 
C:\Program\BC45\INCLUDE\stdlib.h 496: 
C:\Program\BC45\INCLUDE\stdlib.h 497: 
C:\Program\BC45\INCLUDE\stdlib.h 498: 
C:\Program\BC45\INCLUDE\stdlib.h 499: 
C:\Program\BC45\INCLUDE\stdlib.h 500: 
C:\Program\BC45\INCLUDE\stdlib.h 501: 
C:\Program\BC45\INCLUDE\stdlib.h 502: 
C:\Program\BC45\INCLUDE\stdlib.h 503: 
C:\Program\BC45\INCLUDE\stdlib.h 504: 
C:\Program\BC45\INCLUDE\stdlib.h 505: 
C:\Program\BC45\INCLUDE\stdlib.h 506: 
C:\Program\BC45\INCLUDE\stdlib.h 507: 
C:\Program\BC45\INCLUDE\stdlib.h 508: 
C:\Program\BC45\INCLUDE\stdlib.h 509: 
C:\Program\BC45\INCLUDE\stdlib.h 510: 
C:\Program\BC45\INCLUDE\stdlib.h 511: 
C:\Program\BC45\INCLUDE\stdlib.h 512: 
C:\Program\BC45\INCLUDE\stdlib.h 513: 
C:\Program\BC45\INCLUDE\stdlib.h 514: 
C:\Program\BC45\INCLUDE\stdlib.h 515: 
C:\Program\BC45\INCLUDE\stdlib.h 516: 
C:\Program\BC45\INCLUDE\stdlib.h 517: 
C:\Program\BC45\INCLUDE\stdlib.h 518: 
C:\Program\BC45\INCLUDE\stdlib.h 519: 
C:\Program\BC45\INCLUDE\stdlib.h 520: 
C:\Program\BC45\INCLUDE\stdlib.h 521: 
C:\Program\BC45\INCLUDE\stdlib.h 522: 
C:\Program\BC45\INCLUDE\stdlib.h 523: extern "C" long __cdecl  time(long  *);
C:\Program\BC45\INCLUDE\stdlib.h 524: 
C:\Program\BC45\INCLUDE\stdlib.h 525: 
C:\Program\BC45\INCLUDE\stdlib.h 526: 
C:\Program\BC45\INCLUDE\stdlib.h 527: 
C:\Program\BC45\INCLUDE\stdlib.h 528: 
C:\Program\BC45\INCLUDE\stdlib.h 529: 
C:\Program\BC45\INCLUDE\stdlib.h 530: 
C:\Program\BC45\INCLUDE\stdlib.h 531: inline void __cdecl randomize(void) { srand((unsigned) time(0)); }
C:\Program\BC45\INCLUDE\stdlib.h 532: 
C:\Program\BC45\INCLUDE\stdlib.h 533:   
C:\Program\BC45\INCLUDE\stdlib.h 534: 
C:\Program\BC45\INCLUDE\stdlib.h 535: template <class T> inline const T  &min( const T  &t1, const T  &t2 )
C:\Program\BC45\INCLUDE\stdlib.h 536: {
C:\Program\BC45\INCLUDE\stdlib.h 537: if  (t1 < t2)
C:\Program\BC45\INCLUDE\stdlib.h 538: return t1;
C:\Program\BC45\INCLUDE\stdlib.h 539: else
C:\Program\BC45\INCLUDE\stdlib.h 540: return t2;
C:\Program\BC45\INCLUDE\stdlib.h 541: }
C:\Program\BC45\INCLUDE\stdlib.h 542: 
C:\Program\BC45\INCLUDE\stdlib.h 543: template <class T> inline const T  &max( const T  &t1, const T  &t2 )
C:\Program\BC45\INCLUDE\stdlib.h 544: {
C:\Program\BC45\INCLUDE\stdlib.h 545: if  (t1 > t2)
C:\Program\BC45\INCLUDE\stdlib.h 546: return t1;
C:\Program\BC45\INCLUDE\stdlib.h 547: else
C:\Program\BC45\INCLUDE\stdlib.h 548: return t2;
C:\Program\BC45\INCLUDE\stdlib.h 549: }
C:\Program\BC45\INCLUDE\stdlib.h 550: 
C:\Program\BC45\INCLUDE\stdlib.h 551: 
C:\Program\BC45\INCLUDE\stdlib.h 552: 
C:\Program\BC45\INCLUDE\stdlib.h 553: 
C:\Program\BC45\INCLUDE\stdlib.h 554: 
C:\Program\BC45\INCLUDE\stdlib.h 555: 
C:\Program\BC45\INCLUDE\stdlib.h 556: 
C:\Program\BC45\INCLUDE\stdlib.h 557: 
C:\Program\BC45\INCLUDE\stdlib.h 558: 
C:\Program\BC45\INCLUDE\stdlib.h 559: 
C:\Program\BC45\INCLUDE\stdlib.h 560: 
C:\Program\BC45\INCLUDE\stdlib.h 561: 
C:\Program\BC45\INCLUDE\stdlib.h 562: 
C:\Program\BC45\INCLUDE\stdlib.h 563: 
C:\Program\BC45\INCLUDE\stdlib.h 564: 
C:\Program\BC45\INCLUDE\stdlib.h 565: 
C:\Program\BC45\INCLUDE\stdlib.h 566: 
C:\Program\BC45\INCLUDE\stdlib.h 567: 
C:\Program\BC45\INCLUDE\stdlib.h 568: 
C:\Program\BC45\INCLUDE\stdlib.h 569: 
C:\Program\BC45\INCLUDE\stdlib.h 570: #pragma option -a.  /* restore default packing */
C:\Program\BC45\INCLUDE\stdlib.h 571: 
C:\Program\BC45\INCLUDE\stdlib.h 572: 
C:\Program\BC45\INCLUDE\stdlib.h 573: 
C:\Program\BC45\INCLUDE\stdlib.h 574: 
C:\Program\BC45\INCLUDE\stdlib.h 575: 
C:\Program\BC45\INCLUDE\stdlib.h 576: 
C:\Program\BC45\INCLUDE\stdlib.h 577: 
C:\Program\BC45\INCLUDE\stdlib.h 578: 
C:\Program\BC45\INCLUDE\stdlib.h 579: 
C:\Program\BC45\INCLUDE\stdlib.h 580: 
C:\Program\BC45\INCLUDE\stdlib.h 581: 
C:\Program\BC45\INCLUDE\stdlib.h 582: 
Dot.h 3: 
Dot.h 4: class CDot  
Dot.h 5: {
Dot.h 6: private:
Dot.h 7: int x;
Dot.h 8: int y;
Dot.h 9: int size;
Dot.h 10: public:
Dot.h 11: void SetSize(int size);
Dot.h 12: int GetY();
Dot.h 13: int GetX();
Dot.h 14: int GetSize();
Dot.h 15: void PaintNewDot(Grafik g,int MaxX, int MaxY);
Dot.h 16: void RemoveDot(Grafik g);
Dot.h 17: CDot(int size=2);
Dot.h 18: };
Dot.h 19: 
Dot.cpp 2: 
Dot.cpp 3: CDot::CDot(int size)
Dot.cpp 4: {
Dot.cpp 5: this->size=size;
Dot.cpp 6: srand(unsigned(time(0)));
Dot.cpp 7: x=0;
Dot.cpp 8: y=0;
Dot.cpp 9: }
Dot.cpp 10: 
Dot.cpp 11: void CDot::PaintNewDot(Grafik g,int MaxX,int MaxY)
Dot.cpp 12: {
Dot.cpp 13: char *ch;
Dot.cpp 14: x=(rand()%MaxX+1);
Dot.cpp 15: y=(rand()%MaxY+1);
Dot.cpp 16: g.PaintBox(x,y,size,size,14);
Dot.cpp 17: }
Dot.cpp 18: 
Dot.cpp 19: int CDot::GetX()
Dot.cpp 20: {
Dot.cpp 21: return(x);
Dot.cpp 22: }
Dot.cpp 23: 
Dot.cpp 24: int CDot::GetY()
Dot.cpp 25: {
Dot.cpp 26: return(y);
Dot.cpp 27: }
Dot.cpp 28: 
Dot.cpp 29: int CDot::GetSize()
Dot.cpp 30: {
Dot.cpp 31: return(size);
Dot.cpp 32: }
Dot.cpp 33: 
Dot.cpp 34: void CDot::SetSize(int size)
Dot.cpp 35: {
Dot.cpp 36: this->size=size;
Dot.cpp 37: }
Dot.cpp 38: 
Dot.cpp 39: void CDot::RemoveDot(Grafik g)
Dot.cpp 40: {
Dot.cpp 41: if(x!=0&&y!=0)
Dot.cpp 42: g.PaintBox(x,y,size,size,0);
Dot.cpp 43: }
Dot.cpp 44: 
Mask.h 4: 
Mask.h 5: class Mask
Mask.h 6: {
Mask.h 7: private:
Mask.h 8: int NrMaskParts;
Mask.h 9: int size;
Mask.h 10: MaskPart *MaskParts;
Mask.h 11: int top, left, right, bottom;
Mask.h 12: CDot dot;
Mask.h 13: public:
Mask.h 14: Mask();
Mask.h 15: ~Mask();
Mask.h 16: void AddMaskPart(int Parts=4);
Mask.h 17: int GetNrMaskParts();
Mask.h 18: int MoveMask(int,Grafik g);
Mask.h 19: void PaintMask(Grafik);
Mask.h 20: void SetLimits(int top, int left, int right, int bottom);
Mask.h 21: void SetDot(CDot dot);
Mask.h 22: void Reset(Grafik g, int lenght,int size,int startX=50, int startY=50);
Mask.h 23: };
Mask.h 24: 
Mask.cpp 2: 
Mask.cpp 3: Mask::Mask()
Mask.cpp 4: {
Mask.cpp 5: NrMaskParts=0;
Mask.cpp 6: }
Mask.cpp 7: 
Mask.cpp 8: Mask::~Mask()
Mask.cpp 9: {
Mask.cpp 10: delete[] MaskParts;
Mask.cpp 11: }
Mask.cpp 12: 
Mask.cpp 13: void Mask::Reset(Grafik g,int length,int size, int startX, int startY)
Mask.cpp 14: {
Mask.cpp 15: int i(0);
Mask.cpp 16: if(NrMaskParts!=0)
Mask.cpp 17: {
Mask.cpp 18: for(int i=0;i<NrMaskParts;i++)
Mask.cpp 19: g.PaintBox(MaskParts[i].GetX(),MaskParts[i].GetY(),size,size,0);
Mask.cpp 20: delete[] MaskParts;
Mask.cpp 21: }
Mask.cpp 22: MaskParts = new MaskPart[length];
Mask.cpp 23: NrMaskParts=length;
Mask.cpp 24: for(i=0;i<NrMaskParts;i++)
Mask.cpp 25: {
Mask.cpp 26: MaskParts[i].SetX(startX);
Mask.cpp 27: MaskParts[i].SetY(startY);
Mask.cpp 28: }
Mask.cpp 29: this->size=size;
Mask.cpp 30: }
Mask.cpp 31: 
Mask.cpp 32: void Mask::AddMaskPart(int Parts)
Mask.cpp 33: {
Mask.cpp 34: MaskPart *tmpMask = new MaskPart[NrMaskParts+Parts];
Mask.cpp 35: int i(0);
Mask.cpp 36: 
Mask.cpp 37: for(i=0;i<NrMaskParts;i++)
Mask.cpp 38: tmpMask[i]=MaskParts[i];
Mask.cpp 39: delete[] MaskParts;
Mask.cpp 40: MaskParts = new MaskPart[NrMaskParts+Parts];
Mask.cpp 41: for(i=0;i<NrMaskParts;i++)
Mask.cpp 42: MaskParts[i]=tmpMask[i];
Mask.cpp 43: for(i=NrMaskParts;i<NrMaskParts+Parts;i++)
Mask.cpp 44: MaskParts[i]=MaskParts[NrMaskParts-1];
Mask.cpp 45: NrMaskParts+=Parts;
Mask.cpp 46: delete[] tmpMask;
Mask.cpp 47: }
Mask.cpp 48: 
Mask.cpp 49: int Mask::GetNrMaskParts()
Mask.cpp 50: {
Mask.cpp 51: return(NrMaskParts);
Mask.cpp 52: }
Mask.cpp 53: 
Mask.cpp 54: int Mask::MoveMask(int Direction, Grafik g)
Mask.cpp 55: {
Mask.cpp 56: MaskPart *tmpMask = new MaskPart[NrMaskParts-1];
Mask.cpp 57: int i(0);
Mask.cpp 58: 
Mask.cpp 59: for(i=0;i<NrMaskParts-1;i++)
Mask.cpp 60: tmpMask[i]=MaskParts[i];
Mask.cpp 61: if(Direction==0) 
Mask.cpp 62: MaskParts[0].SetY(MaskParts[0].GetY()+(1*size));
Mask.cpp 63: else if(Direction==1) 
Mask.cpp 64: MaskParts[0].SetY(MaskParts[0].GetY()-(1*size));
Mask.cpp 65: else if(Direction==2) 
Mask.cpp 66: MaskParts[0].SetX(MaskParts[0].GetX()+(1*size));
Mask.cpp 67: else if(Direction==3) 
Mask.cpp 68: MaskParts[0].SetX(MaskParts[0].GetX()-(1*size));
Mask.cpp 69: for(i=0;i<NrMaskParts-1;i++)
Mask.cpp 70: MaskParts[i+1]=tmpMask[i];
Mask.cpp 71: delete[] tmpMask;
Mask.cpp 72: 
Mask.cpp 73: int MaskX = MaskParts[0].GetX();
Mask.cpp 74: int MaskY = MaskParts[0].GetY();
Mask.cpp 75: 
Mask.cpp 76: 
Mask.cpp 77: 
Mask.cpp 78: 
Mask.cpp 79: 
Mask.cpp 80: 
Mask.cpp 81: if(Direction==0)
Mask.cpp 82: {
Mask.cpp 83: if((g.GetColor(MaskX,MaskY+size)!=0)||(g.GetColor(MaskX+size,MaskY+size)!=0))
Mask.cpp 84: {
Mask.cpp 85: if((g.GetColor(MaskX,MaskY+size)==14)||(g.GetColor(MaskX+size,MaskY+size)==14))
Mask.cpp 86: return(2);
Mask.cpp 87: else
Mask.cpp 88: return(1);
Mask.cpp 89: }
Mask.cpp 90: else if(MaskY+size>=bottom)
Mask.cpp 91: {
Mask.cpp 92: return(1);
Mask.cpp 93: }
Mask.cpp 94: }
Mask.cpp 95: else if(Direction==1)
Mask.cpp 96: {
Mask.cpp 97: if((g.GetColor(MaskX,MaskY)!=0)||(g.GetColor(MaskX+size,MaskY)!=0))
Mask.cpp 98: {
Mask.cpp 99: if((g.GetColor(MaskX,MaskY)==14)||(g.GetColor(MaskX+size,MaskY)==14))
Mask.cpp 100: return(2);
Mask.cpp 101: else
Mask.cpp 102: return(1);
Mask.cpp 103: }
Mask.cpp 104: else if(MaskY<=top)
Mask.cpp 105: {
Mask.cpp 106: return(1);
Mask.cpp 107: }
Mask.cpp 108: }
Mask.cpp 109: else if(Direction==2)
Mask.cpp 110: {
Mask.cpp 111: if((g.GetColor(MaskX+size,MaskY)!=0)||(g.GetColor(MaskX+size,MaskY+size)!=0))
Mask.cpp 112: {
Mask.cpp 113: if((g.GetColor(MaskX+size,MaskY)==14)||(g.GetColor(MaskX+size,MaskY+size)==14))
Mask.cpp 114: return(2);
Mask.cpp 115: else
Mask.cpp 116: return(1);
Mask.cpp 117: }
Mask.cpp 118: else if(MaskX+size>=right)
Mask.cpp 119: {
Mask.cpp 120: return(1);
Mask.cpp 121: }
Mask.cpp 122: }
Mask.cpp 123: else if(Direction==3)
Mask.cpp 124: {
Mask.cpp 125: if((g.GetColor(MaskX,MaskY)!=0)||(g.GetColor(MaskX,MaskY+size)!=0))
Mask.cpp 126: {
Mask.cpp 127: if((g.GetColor(MaskX,MaskY)==14)||(g.GetColor(MaskX,MaskY+size)==14))
Mask.cpp 128: return(2);
Mask.cpp 129: else
Mask.cpp 130: return(1);
Mask.cpp 131: }
Mask.cpp 132: else if(MaskX<=left)
Mask.cpp 133: {
Mask.cpp 134: return(1);
Mask.cpp 135: }
Mask.cpp 136: }
Mask.cpp 137: return(0);
Mask.cpp 138: }
Mask.cpp 139: 
Mask.cpp 140: void Mask::PaintMask(Grafik g)
Mask.cpp 141: {
Mask.cpp 142: for(int i=0;i<NrMaskParts-1;i++)
Mask.cpp 143: g.PaintBox(MaskParts[i].GetX(),MaskParts[i].GetY(),size,size,12);
Mask.cpp 144: g.PaintBox(MaskParts[i].GetX(),MaskParts[i].GetY(),size,size,0);
Mask.cpp 145: }
Mask.cpp 146: 
Mask.cpp 147: void Mask::SetLimits(int top,int left,int right,int bottom)
Mask.cpp 148: {
Mask.cpp 149: this->top=top;
Mask.cpp 150: this->left=left;
Mask.cpp 151: this->right=right;
Mask.cpp 152: this->bottom=bottom;
Mask.cpp 153: }
Mask.cpp 154: 
Mask.cpp 155: void Mask::SetDot(CDot dot)
Mask.cpp 156: {
Mask.cpp 157: this->dot=dot;
Mask.cpp 158: }
Mask.cpp 159: 
Mask.cpp 160: 
main.cpp 2: 
C:\Program\BC45\INCLUDE\stdio.h 1: 
C:\Program\BC45\INCLUDE\stdio.h 2: 
C:\Program\BC45\INCLUDE\stdio.h 3: 
C:\Program\BC45\INCLUDE\stdio.h 4: 
C:\Program\BC45\INCLUDE\stdio.h 5: 
C:\Program\BC45\INCLUDE\stdio.h 6: 
C:\Program\BC45\INCLUDE\stdio.h 7: 
C:\Program\BC45\INCLUDE\stdio.h 8: 
C:\Program\BC45\INCLUDE\stdio.h 9: 
C:\Program\BC45\INCLUDE\stdio.h 10: 
C:\Program\BC45\INCLUDE\stdio.h 11: 
C:\Program\BC45\INCLUDE\stdio.h 12: 
C:\Program\BC45\INCLUDE\stdio.h 13: 
C:\Program\BC45\INCLUDE\stdio.h 14: 
C:\Program\BC45\INCLUDE\stdio.h 15: 
C:\Program\BC45\INCLUDE\stdio.h 16: 
C:\Program\BC45\INCLUDE\stdio.h 17: 
C:\Program\BC45\INCLUDE\stdio.h 18: 
C:\Program\BC45\INCLUDE\stdio.h 19: 
C:\Program\BC45\INCLUDE\stdio.h 20: 
C:\Program\BC45\INCLUDE\stdio.h 21: 
C:\Program\BC45\INCLUDE\stdio.h 22: 
C:\Program\BC45\INCLUDE\stdio.h 23: 
C:\Program\BC45\INCLUDE\_nfile.h 1: 
C:\Program\BC45\INCLUDE\_nfile.h 2: 
C:\Program\BC45\INCLUDE\_nfile.h 3: 
C:\Program\BC45\INCLUDE\_nfile.h 4: 
C:\Program\BC45\INCLUDE\_nfile.h 5: 
C:\Program\BC45\INCLUDE\_nfile.h 6: 
C:\Program\BC45\INCLUDE\_nfile.h 7: 
C:\Program\BC45\INCLUDE\_nfile.h 8: 
C:\Program\BC45\INCLUDE\_nfile.h 9: 
C:\Program\BC45\INCLUDE\_nfile.h 10: 
C:\Program\BC45\INCLUDE\_nfile.h 11: 
C:\Program\BC45\INCLUDE\_nfile.h 12: 
C:\Program\BC45\INCLUDE\_nfile.h 13: 
C:\Program\BC45\INCLUDE\_nfile.h 14: 
C:\Program\BC45\INCLUDE\_nfile.h 15: 
C:\Program\BC45\INCLUDE\_nfile.h 16: 
C:\Program\BC45\INCLUDE\_nfile.h 17: 
C:\Program\BC45\INCLUDE\_nfile.h 18: 
C:\Program\BC45\INCLUDE\_nfile.h 19: 
C:\Program\BC45\INCLUDE\_nfile.h 20: 
C:\Program\BC45\INCLUDE\_nfile.h 21: 
C:\Program\BC45\INCLUDE\_nfile.h 22: 
C:\Program\BC45\INCLUDE\_nfile.h 23: 
C:\Program\BC45\INCLUDE\_nfile.h 24: 
C:\Program\BC45\INCLUDE\_nfile.h 25: 
C:\Program\BC45\INCLUDE\_nfile.h 26: 
C:\Program\BC45\INCLUDE\_nfile.h 27: 
C:\Program\BC45\INCLUDE\_nfile.h 28: 
C:\Program\BC45\INCLUDE\_nfile.h 29: 
C:\Program\BC45\INCLUDE\_nfile.h 30: 
C:\Program\BC45\INCLUDE\stdio.h 24: 
C:\Program\BC45\INCLUDE\stdio.h 25: 
C:\Program\BC45\INCLUDE\stdio.h 26: 
C:\Program\BC45\INCLUDE\stdio.h 27: 
C:\Program\BC45\INCLUDE\stdio.h 28: 
C:\Program\BC45\INCLUDE\stdio.h 29: 
C:\Program\BC45\INCLUDE\stdio.h 30: 
C:\Program\BC45\INCLUDE\stdio.h 31: 
C:\Program\BC45\INCLUDE\stdio.h 32: 
C:\Program\BC45\INCLUDE\stdio.h 33: 
C:\Program\BC45\INCLUDE\stdio.h 34: 
C:\Program\BC45\INCLUDE\stdio.h 35: 
C:\Program\BC45\INCLUDE\stdio.h 36: 
C:\Program\BC45\INCLUDE\stdio.h 37: #pragma option -a-
C:\Program\BC45\INCLUDE\stdio.h 38: 
C:\Program\BC45\INCLUDE\stdio.h 39: 
C:\Program\BC45\INCLUDE\stdio.h 40: 
C:\Program\BC45\INCLUDE\stdio.h 41: 
C:\Program\BC45\INCLUDE\stdio.h 42: 
C:\Program\BC45\INCLUDE\stdio.h 43: 
C:\Program\BC45\INCLUDE\stdio.h 44: 
C:\Program\BC45\INCLUDE\stdio.h 45: 
C:\Program\BC45\INCLUDE\stdio.h 46: 
C:\Program\BC45\INCLUDE\stdio.h 47: 
C:\Program\BC45\INCLUDE\stdio.h 48: 
C:\Program\BC45\INCLUDE\stdio.h 49: typedef long    fpos_t;
C:\Program\BC45\INCLUDE\stdio.h 50: 
C:\Program\BC45\INCLUDE\stdio.h 51: 
C:\Program\BC45\INCLUDE\stdio.h 52: 
C:\Program\BC45\INCLUDE\stdio.h 53: 
C:\Program\BC45\INCLUDE\stdio.h 54: extern int _floatconvert;
C:\Program\BC45\INCLUDE\stdio.h 55: 
C:\Program\BC45\INCLUDE\stdio.h 56: 
C:\Program\BC45\INCLUDE\stdio.h 57: 
C:\Program\BC45\INCLUDE\stdio.h 58: 
C:\Program\BC45\INCLUDE\stdio.h 59: 
C:\Program\BC45\INCLUDE\stdio.h 60: 
C:\Program\BC45\INCLUDE\stdio.h 61: 
C:\Program\BC45\INCLUDE\stdio.h 62: 
C:\Program\BC45\INCLUDE\stdio.h 63: 
C:\Program\BC45\INCLUDE\stdio.h 64: 
C:\Program\BC45\INCLUDE\stdio.h 65: 
C:\Program\BC45\INCLUDE\stdio.h 66: 
C:\Program\BC45\INCLUDE\stdio.h 67: 
C:\Program\BC45\INCLUDE\stdio.h 68: 
C:\Program\BC45\INCLUDE\stdio.h 69: 
C:\Program\BC45\INCLUDE\stdio.h 70: 
C:\Program\BC45\INCLUDE\stdio.h 71: 
C:\Program\BC45\INCLUDE\stdio.h 72: 
C:\Program\BC45\INCLUDE\stdio.h 73: 
C:\Program\BC45\INCLUDE\stdio.h 74: 
C:\Program\BC45\INCLUDE\stdio.h 75: 
C:\Program\BC45\INCLUDE\stdio.h 76: 
C:\Program\BC45\INCLUDE\stdio.h 77: 
C:\Program\BC45\INCLUDE\stdio.h 78: 
C:\Program\BC45\INCLUDE\stdio.h 79: 
C:\Program\BC45\INCLUDE\stdio.h 80: 
C:\Program\BC45\INCLUDE\stdio.h 81: 
C:\Program\BC45\INCLUDE\stdio.h 82: 
C:\Program\BC45\INCLUDE\stdio.h 83: 
C:\Program\BC45\INCLUDE\stdio.h 84: 
C:\Program\BC45\INCLUDE\stdio.h 85: 
C:\Program\BC45\INCLUDE\stdio.h 86: 
C:\Program\BC45\INCLUDE\stdio.h 87: 
C:\Program\BC45\INCLUDE\stdio.h 88: 
C:\Program\BC45\INCLUDE\stdio.h 89: 
C:\Program\BC45\INCLUDE\stdio.h 90: 
C:\Program\BC45\INCLUDE\stdio.h 91: 
C:\Program\BC45\INCLUDE\stdio.h 92: 
C:\Program\BC45\INCLUDE\stdio.h 93: 
C:\Program\BC45\INCLUDE\stdio.h 94: 
C:\Program\BC45\INCLUDE\stdio.h 95: 
C:\Program\BC45\INCLUDE\stdio.h 96: 
C:\Program\BC45\INCLUDE\stdio.h 97: 
C:\Program\BC45\INCLUDE\stdio.h 98: 
C:\Program\BC45\INCLUDE\stdio.h 99: 
C:\Program\BC45\INCLUDE\stdio.h 100: 
C:\Program\BC45\INCLUDE\stdio.h 101: 
C:\Program\BC45\INCLUDE\stdio.h 102: 
C:\Program\BC45\INCLUDE\stdio.h 103: 
C:\Program\BC45\INCLUDE\stdio.h 104: 
C:\Program\BC45\INCLUDE\stdio.h 105: typedef struct  {
C:\Program\BC45\INCLUDE\stdio.h 106: int             level;          
C:\Program\BC45\INCLUDE\stdio.h 107: unsigned        flags;          
C:\Program\BC45\INCLUDE\stdio.h 108: char            fd;             
C:\Program\BC45\INCLUDE\stdio.h 109: unsigned char   hold;           
C:\Program\BC45\INCLUDE\stdio.h 110: int             bsize;          
C:\Program\BC45\INCLUDE\stdio.h 111: unsigned char    *buffer;   
C:\Program\BC45\INCLUDE\stdio.h 112: unsigned char    *curp;     
C:\Program\BC45\INCLUDE\stdio.h 113: unsigned        istemp;         
C:\Program\BC45\INCLUDE\stdio.h 114: short           token;          
C:\Program\BC45\INCLUDE\stdio.h 115: }       FILE;                           
C:\Program\BC45\INCLUDE\stdio.h 116: 
C:\Program\BC45\INCLUDE\stdio.h 117: 
C:\Program\BC45\INCLUDE\stdio.h 118: 
C:\Program\BC45\INCLUDE\stdio.h 119: 
C:\Program\BC45\INCLUDE\stdio.h 120: 
C:\Program\BC45\INCLUDE\stdio.h 121: 
C:\Program\BC45\INCLUDE\stdio.h 122: 
C:\Program\BC45\INCLUDE\stdio.h 123: 
C:\Program\BC45\INCLUDE\stdio.h 124: 
C:\Program\BC45\INCLUDE\stdio.h 125: 
C:\Program\BC45\INCLUDE\stdio.h 126: 
C:\Program\BC45\INCLUDE\stdio.h 127: 
C:\Program\BC45\INCLUDE\stdio.h 128: 
C:\Program\BC45\INCLUDE\stdio.h 129: 
C:\Program\BC45\INCLUDE\stdio.h 130: 
C:\Program\BC45\INCLUDE\stdio.h 131: 
C:\Program\BC45\INCLUDE\stdio.h 132: extern  FILE    __cdecl _streams[];
C:\Program\BC45\INCLUDE\stdio.h 133: extern  unsigned    __cdecl _nfile;
C:\Program\BC45\INCLUDE\stdio.h 134: 
C:\Program\BC45\INCLUDE\stdio.h 135: 
C:\Program\BC45\INCLUDE\stdio.h 136: 
C:\Program\BC45\INCLUDE\stdio.h 137: 
C:\Program\BC45\INCLUDE\stdio.h 138: 
C:\Program\BC45\INCLUDE\stdio.h 139: 
C:\Program\BC45\INCLUDE\stdio.h 140: 
C:\Program\BC45\INCLUDE\stdio.h 141: 
C:\Program\BC45\INCLUDE\stdio.h 142: 
C:\Program\BC45\INCLUDE\stdio.h 143: 
C:\Program\BC45\INCLUDE\stdio.h 144: 
C:\Program\BC45\INCLUDE\stdio.h 145: 
C:\Program\BC45\INCLUDE\stdio.h 146: 
C:\Program\BC45\INCLUDE\stdio.h 147: 
C:\Program\BC45\INCLUDE\stdio.h 148: 
C:\Program\BC45\INCLUDE\stdio.h 149: 
C:\Program\BC45\INCLUDE\stdio.h 150: 
C:\Program\BC45\INCLUDE\stdio.h 151: 
C:\Program\BC45\INCLUDE\stdio.h 152: 
C:\Program\BC45\INCLUDE\stdio.h 153: 
C:\Program\BC45\INCLUDE\stdio.h 154: 
C:\Program\BC45\INCLUDE\stdio.h 155: 
C:\Program\BC45\INCLUDE\stdio.h 156: 
C:\Program\BC45\INCLUDE\stdio.h 157: 
C:\Program\BC45\INCLUDE\stdio.h 158: extern "C" {
C:\Program\BC45\INCLUDE\stdio.h 159: 
C:\Program\BC45\INCLUDE\stdio.h 160: void    __cdecl          clearerr(FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 161: int     __cdecl  fclose(FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 162: int     __cdecl  fflush(FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 163: int     __cdecl  fgetc(FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 164: int     __cdecl          fgetpos(FILE  *__stream, fpos_t  *__pos);
C:\Program\BC45\INCLUDE\stdio.h 165: char    *__cdecl  fgets(char  *__s, int __n, FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 166: FILE    *__cdecl  fopen(const char  *__path, const char  *__mode);
C:\Program\BC45\INCLUDE\stdio.h 167: int     __cdecl  fprintf(FILE  *__stream, const char  *__format, ...);
C:\Program\BC45\INCLUDE\stdio.h 168: int     __cdecl  fputc(int __c, FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 169: int     __cdecl  fputs(const char  *__s, FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 170: size_t  __cdecl  fread(void  *__ptr, size_t __size, size_t __n,
C:\Program\BC45\INCLUDE\stdio.h 171: FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 172: FILE    *__cdecl  freopen(const char  *__path, const char  *__mode,
C:\Program\BC45\INCLUDE\stdio.h 173: FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 174: int     __cdecl  fscanf(FILE  *__stream, const char  *__format, ...);
C:\Program\BC45\INCLUDE\stdio.h 175: int     __cdecl  fseek(FILE  *__stream, long __offset, int __whence);
C:\Program\BC45\INCLUDE\stdio.h 176: int     __cdecl          fsetpos(FILE  *__stream, const fpos_t  *__pos);
C:\Program\BC45\INCLUDE\stdio.h 177: long    __cdecl  ftell(FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 178: size_t  __cdecl  fwrite(const void  *__ptr, size_t __size, size_t __n,
C:\Program\BC45\INCLUDE\stdio.h 179: FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 180: char    *__cdecl     gets(char  *__s);
C:\Program\BC45\INCLUDE\stdio.h 181: void    __cdecl          perror(const char  *__s);
C:\Program\BC45\INCLUDE\stdio.h 182: int     __cdecl          printf(const char  *__format, ...);
C:\Program\BC45\INCLUDE\stdio.h 183: int     __cdecl          puts(const char  *__s);
C:\Program\BC45\INCLUDE\stdio.h 184: int     __cdecl         remove(const char  *__path);
C:\Program\BC45\INCLUDE\stdio.h 185: int     __cdecl  rename(const char  *__oldname,const char  *__newname);
C:\Program\BC45\INCLUDE\stdio.h 186: void    __cdecl  rewind(FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 187: int     __cdecl          scanf(const char  *__format, ...);
C:\Program\BC45\INCLUDE\stdio.h 188: void    __cdecl          setbuf(FILE  *__stream, char  *__buf);
C:\Program\BC45\INCLUDE\stdio.h 189: int     __cdecl  setvbuf(FILE  *__stream, char  *__buf,
C:\Program\BC45\INCLUDE\stdio.h 190: int __type, size_t __size);
C:\Program\BC45\INCLUDE\stdio.h 191: int     __cdecl  sprintf(char  *__buffer, const char  *__format, ...);
C:\Program\BC45\INCLUDE\stdio.h 192: int     __cdecl  sscanf(const char  *__buffer,
C:\Program\BC45\INCLUDE\stdio.h 193: const char  *__format, ...);
C:\Program\BC45\INCLUDE\stdio.h 194: char    *__cdecl  strerror(int __errnum);
C:\Program\BC45\INCLUDE\stdio.h 195: FILE    *__cdecl  tmpfile(void);
C:\Program\BC45\INCLUDE\stdio.h 196: char    *__cdecl  tmpnam(char  *__s);
C:\Program\BC45\INCLUDE\stdio.h 197: int     __cdecl  ungetc(int __c, FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 198: int     __cdecl  vfprintf(FILE  *__stream, const char  *__format,
C:\Program\BC45\INCLUDE\stdio.h 199: void  *__arglist);
C:\Program\BC45\INCLUDE\stdio.h 200: int     __cdecl  vfscanf(FILE  *__stream, const char  *__format,
C:\Program\BC45\INCLUDE\stdio.h 201: void  *__arglist);
C:\Program\BC45\INCLUDE\stdio.h 202: int     __cdecl         vprintf(const char  *__format, void  *__arglist);
C:\Program\BC45\INCLUDE\stdio.h 203: int     __cdecl          vscanf(const char  *__format, void  *__arglist);
C:\Program\BC45\INCLUDE\stdio.h 204: int     __cdecl  vsprintf(char  *__buffer, const char  *__format,
C:\Program\BC45\INCLUDE\stdio.h 205: void  *__arglist);
C:\Program\BC45\INCLUDE\stdio.h 206: int     __cdecl  vsscanf(const char  *__buffer, const char  *__format,
C:\Program\BC45\INCLUDE\stdio.h 207: void  *__arglist);
C:\Program\BC45\INCLUDE\stdio.h 208: int     __cdecl         unlink(const char  *__path);
C:\Program\BC45\INCLUDE\stdio.h 209: int     __cdecl          getc(FILE  *__fp);
C:\Program\BC45\INCLUDE\stdio.h 210: 
C:\Program\BC45\INCLUDE\stdio.h 211: int     __cdecl          getchar(void);
C:\Program\BC45\INCLUDE\stdio.h 212: int     __cdecl          putchar(const int __c);
C:\Program\BC45\INCLUDE\stdio.h 213: 
C:\Program\BC45\INCLUDE\stdio.h 214: int     __cdecl          putc(const int __c, FILE  *__fp);
C:\Program\BC45\INCLUDE\stdio.h 215: int     __cdecl          feof(FILE  *__fp);
C:\Program\BC45\INCLUDE\stdio.h 216: int     __cdecl          ferror(FILE  *__fp);
C:\Program\BC45\INCLUDE\stdio.h 217: 
C:\Program\BC45\INCLUDE\stdio.h 218: int     __cdecl  fcloseall(void);
C:\Program\BC45\INCLUDE\stdio.h 219: FILE     *__cdecl  fdopen(int __handle, char  *__type);
C:\Program\BC45\INCLUDE\stdio.h 220: int     __cdecl  fgetchar(void);
C:\Program\BC45\INCLUDE\stdio.h 221: int     __cdecl  flushall(void);
C:\Program\BC45\INCLUDE\stdio.h 222: int     __cdecl  fputchar(int __c);
C:\Program\BC45\INCLUDE\stdio.h 223: FILE     * __cdecl   _fsopen (const char  *__path, const char  *__mode,
C:\Program\BC45\INCLUDE\stdio.h 224: int __shflag);
C:\Program\BC45\INCLUDE\stdio.h 225: int     __cdecl          getw(FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 226: int     __cdecl          putw(int __w, FILE  *__stream);
C:\Program\BC45\INCLUDE\stdio.h 227: int     __cdecl          rmtmp(void);
C:\Program\BC45\INCLUDE\stdio.h 228: char     * __cdecl  _strerror(const char  *__s);
C:\Program\BC45\INCLUDE\stdio.h 229: char     * __cdecl  tempnam(char  *__dir, char  *__pfx);
C:\Program\BC45\INCLUDE\stdio.h 230: 
C:\Program\BC45\INCLUDE\stdio.h 231: 
C:\Program\BC45\INCLUDE\stdio.h 232: 
C:\Program\BC45\INCLUDE\stdio.h 233: int      __cdecl  _fgetc(FILE  *__stream);           
C:\Program\BC45\INCLUDE\stdio.h 234: int      __cdecl  _fputc(char __c, FILE  *__stream); 
C:\Program\BC45\INCLUDE\stdio.h 235: void     __cdecl _InitEasyWin(void);  
C:\Program\BC45\INCLUDE\stdio.h 236: 
C:\Program\BC45\INCLUDE\stdio.h 237: 
C:\Program\BC45\INCLUDE\stdio.h 238: }
C:\Program\BC45\INCLUDE\stdio.h 239: 
C:\Program\BC45\INCLUDE\stdio.h 240: 
C:\Program\BC45\INCLUDE\stdio.h 241: 
C:\Program\BC45\INCLUDE\stdio.h 242: 
C:\Program\BC45\INCLUDE\stdio.h 243: 
C:\Program\BC45\INCLUDE\stdio.h 244: 
C:\Program\BC45\INCLUDE\stdio.h 245: 
C:\Program\BC45\INCLUDE\stdio.h 246: 
C:\Program\BC45\INCLUDE\stdio.h 247: 
C:\Program\BC45\INCLUDE\stdio.h 248: 
C:\Program\BC45\INCLUDE\stdio.h 249: 
C:\Program\BC45\INCLUDE\stdio.h 250: 
C:\Program\BC45\INCLUDE\stdio.h 251: 
C:\Program\BC45\INCLUDE\stdio.h 252: 
C:\Program\BC45\INCLUDE\stdio.h 253: 
C:\Program\BC45\INCLUDE\stdio.h 254: 
C:\Program\BC45\INCLUDE\stdio.h 255: 
C:\Program\BC45\INCLUDE\stdio.h 256: 
C:\Program\BC45\INCLUDE\stdio.h 257: 
C:\Program\BC45\INCLUDE\stdio.h 258: 
C:\Program\BC45\INCLUDE\stdio.h 259: 
C:\Program\BC45\INCLUDE\stdio.h 260: 
C:\Program\BC45\INCLUDE\stdio.h 261: 
C:\Program\BC45\INCLUDE\stdio.h 262: 
C:\Program\BC45\INCLUDE\stdio.h 263: 
C:\Program\BC45\INCLUDE\stdio.h 264: 
C:\Program\BC45\INCLUDE\stdio.h 265: 
C:\Program\BC45\INCLUDE\stdio.h 266: 
C:\Program\BC45\INCLUDE\stdio.h 267: 
C:\Program\BC45\INCLUDE\stdio.h 268: 
C:\Program\BC45\INCLUDE\stdio.h 269: 
C:\Program\BC45\INCLUDE\stdio.h 270: 
C:\Program\BC45\INCLUDE\stdio.h 271: 
C:\Program\BC45\INCLUDE\stdio.h 272: 
C:\Program\BC45\INCLUDE\stdio.h 273: 
C:\Program\BC45\INCLUDE\stdio.h 274: 
C:\Program\BC45\INCLUDE\stdio.h 275: 
C:\Program\BC45\INCLUDE\stdio.h 276: 
C:\Program\BC45\INCLUDE\stdio.h 277: 
C:\Program\BC45\INCLUDE\stdio.h 278: 
C:\Program\BC45\INCLUDE\stdio.h 279: 
C:\Program\BC45\INCLUDE\stdio.h 280: 
C:\Program\BC45\INCLUDE\stdio.h 281: 
C:\Program\BC45\INCLUDE\stdio.h 282: 
C:\Program\BC45\INCLUDE\stdio.h 283: 
C:\Program\BC45\INCLUDE\stdio.h 284: 
C:\Program\BC45\INCLUDE\stdio.h 285: 
C:\Program\BC45\INCLUDE\stdio.h 286: 
C:\Program\BC45\INCLUDE\stdio.h 287: 
C:\Program\BC45\INCLUDE\stdio.h 288: 
C:\Program\BC45\INCLUDE\stdio.h 289: 
C:\Program\BC45\INCLUDE\stdio.h 290: 
C:\Program\BC45\INCLUDE\stdio.h 291: 
C:\Program\BC45\INCLUDE\stdio.h 292: 
C:\Program\BC45\INCLUDE\stdio.h 293: 
C:\Program\BC45\INCLUDE\stdio.h 294: 
C:\Program\BC45\INCLUDE\stdio.h 295: 
C:\Program\BC45\INCLUDE\stdio.h 296: 
C:\Program\BC45\INCLUDE\stdio.h 297: 
C:\Program\BC45\INCLUDE\stdio.h 298: 
C:\Program\BC45\INCLUDE\stdio.h 299: 
C:\Program\BC45\INCLUDE\stdio.h 300: 
C:\Program\BC45\INCLUDE\stdio.h 301: 
C:\Program\BC45\INCLUDE\stdio.h 302: 
C:\Program\BC45\INCLUDE\stdio.h 303: 
C:\Program\BC45\INCLUDE\stdio.h 304: 
C:\Program\BC45\INCLUDE\stdio.h 305: 
C:\Program\BC45\INCLUDE\stdio.h 306: 
C:\Program\BC45\INCLUDE\stdio.h 307: 
C:\Program\BC45\INCLUDE\stdio.h 308: 
C:\Program\BC45\INCLUDE\stdio.h 309: 
C:\Program\BC45\INCLUDE\stdio.h 310: 
C:\Program\BC45\INCLUDE\stdio.h 311: 
C:\Program\BC45\INCLUDE\stdio.h 312: 
C:\Program\BC45\INCLUDE\stdio.h 313: 
C:\Program\BC45\INCLUDE\stdio.h 314: 
C:\Program\BC45\INCLUDE\stdio.h 315: 
C:\Program\BC45\INCLUDE\stdio.h 316: 
C:\Program\BC45\INCLUDE\stdio.h 317: 
C:\Program\BC45\INCLUDE\stdio.h 318: 
C:\Program\BC45\INCLUDE\stdio.h 319: 
C:\Program\BC45\INCLUDE\stdio.h 320: 
C:\Program\BC45\INCLUDE\stdio.h 321: 
C:\Program\BC45\INCLUDE\stdio.h 322: 
C:\Program\BC45\INCLUDE\stdio.h 323: 
C:\Program\BC45\INCLUDE\stdio.h 324: 
C:\Program\BC45\INCLUDE\stdio.h 325: 
C:\Program\BC45\INCLUDE\stdio.h 326: 
C:\Program\BC45\INCLUDE\stdio.h 327: 
C:\Program\BC45\INCLUDE\stdio.h 328: 
C:\Program\BC45\INCLUDE\stdio.h 329: 
C:\Program\BC45\INCLUDE\stdio.h 330: 
C:\Program\BC45\INCLUDE\stdio.h 331: 
C:\Program\BC45\INCLUDE\stdio.h 332: 
C:\Program\BC45\INCLUDE\stdio.h 333: 
C:\Program\BC45\INCLUDE\stdio.h 334: 
C:\Program\BC45\INCLUDE\stdio.h 335: 
C:\Program\BC45\INCLUDE\stdio.h 336: 
C:\Program\BC45\INCLUDE\stdio.h 337: 
C:\Program\BC45\INCLUDE\stdio.h 338: 
C:\Program\BC45\INCLUDE\stdio.h 339: 
C:\Program\BC45\INCLUDE\stdio.h 340: 
C:\Program\BC45\INCLUDE\stdio.h 341: 
C:\Program\BC45\INCLUDE\stdio.h 342: 
C:\Program\BC45\INCLUDE\stdio.h 343: 
C:\Program\BC45\INCLUDE\stdio.h 344: 
C:\Program\BC45\INCLUDE\stdio.h 345: 
C:\Program\BC45\INCLUDE\stdio.h 346: 
C:\Program\BC45\INCLUDE\stdio.h 347: 
C:\Program\BC45\INCLUDE\stdio.h 348: 
C:\Program\BC45\INCLUDE\stdio.h 349: 
C:\Program\BC45\INCLUDE\stdio.h 350: 
C:\Program\BC45\INCLUDE\stdio.h 351: 
C:\Program\BC45\INCLUDE\stdio.h 352: 
C:\Program\BC45\INCLUDE\stdio.h 353: 
C:\Program\BC45\INCLUDE\stdio.h 354: 
C:\Program\BC45\INCLUDE\stdio.h 355: 
C:\Program\BC45\INCLUDE\stdio.h 356: 
C:\Program\BC45\INCLUDE\stdio.h 357: 
C:\Program\BC45\INCLUDE\stdio.h 358: 
C:\Program\BC45\INCLUDE\stdio.h 359: 
C:\Program\BC45\INCLUDE\stdio.h 360: 
C:\Program\BC45\INCLUDE\stdio.h 361: 
C:\Program\BC45\INCLUDE\stdio.h 362: 
C:\Program\BC45\INCLUDE\stdio.h 363: 
C:\Program\BC45\INCLUDE\stdio.h 364: 
C:\Program\BC45\INCLUDE\stdio.h 365: 
C:\Program\BC45\INCLUDE\stdio.h 366: 
C:\Program\BC45\INCLUDE\stdio.h 367: 
C:\Program\BC45\INCLUDE\stdio.h 368: 
C:\Program\BC45\INCLUDE\stdio.h 369: 
C:\Program\BC45\INCLUDE\stdio.h 370: 
C:\Program\BC45\INCLUDE\stdio.h 371: 
C:\Program\BC45\INCLUDE\stdio.h 372: 
C:\Program\BC45\INCLUDE\stdio.h 373: 
C:\Program\BC45\INCLUDE\stdio.h 374: 
C:\Program\BC45\INCLUDE\stdio.h 375: 
C:\Program\BC45\INCLUDE\stdio.h 376: 
C:\Program\BC45\INCLUDE\stdio.h 377: 
C:\Program\BC45\INCLUDE\stdio.h 378: 
C:\Program\BC45\INCLUDE\stdio.h 379: 
C:\Program\BC45\INCLUDE\stdio.h 380: 
C:\Program\BC45\INCLUDE\stdio.h 381: 
C:\Program\BC45\INCLUDE\stdio.h 382: 
C:\Program\BC45\INCLUDE\stdio.h 383: 
C:\Program\BC45\INCLUDE\stdio.h 384: 
C:\Program\BC45\INCLUDE\stdio.h 385: 
C:\Program\BC45\INCLUDE\stdio.h 386: 
C:\Program\BC45\INCLUDE\stdio.h 387: 
C:\Program\BC45\INCLUDE\stdio.h 388: 
C:\Program\BC45\INCLUDE\stdio.h 389: 
C:\Program\BC45\INCLUDE\stdio.h 390: 
C:\Program\BC45\INCLUDE\stdio.h 391: #pragma option -a. /* restore default packing */
C:\Program\BC45\INCLUDE\stdio.h 392: 
C:\Program\BC45\INCLUDE\stdio.h 393: 
C:\Program\BC45\INCLUDE\stdio.h 394: 
C:\Program\BC45\INCLUDE\stdio.h 395: 
C:\Program\BC45\INCLUDE\stdio.h 396: 
C:\Program\BC45\INCLUDE\stdio.h 397: 
C:\Program\BC45\INCLUDE\stdio.h 398: 
C:\Program\BC45\INCLUDE\stdio.h 399: 
C:\Program\BC45\INCLUDE\stdio.h 400: 
C:\Program\BC45\INCLUDE\stdio.h 401: 
C:\Program\BC45\INCLUDE\stdio.h 402: 
main.cpp 3: 
C:\Program\BC45\INCLUDE\conio.h 1: 
C:\Program\BC45\INCLUDE\conio.h 2: 
C:\Program\BC45\INCLUDE\conio.h 3: 
C:\Program\BC45\INCLUDE\conio.h 4: 
C:\Program\BC45\INCLUDE\conio.h 5: 
C:\Program\BC45\INCLUDE\conio.h 6: 
C:\Program\BC45\INCLUDE\conio.h 7: 
C:\Program\BC45\INCLUDE\conio.h 8: 
C:\Program\BC45\INCLUDE\conio.h 9: 
C:\Program\BC45\INCLUDE\conio.h 10: 
C:\Program\BC45\INCLUDE\conio.h 11: 
C:\Program\BC45\INCLUDE\conio.h 12: 
C:\Program\BC45\INCLUDE\conio.h 13: 
C:\Program\BC45\INCLUDE\conio.h 14: 
C:\Program\BC45\INCLUDE\conio.h 15: 
C:\Program\BC45\INCLUDE\conio.h 16: 
C:\Program\BC45\INCLUDE\conio.h 17: 
C:\Program\BC45\INCLUDE\conio.h 18: 
C:\Program\BC45\INCLUDE\conio.h 19: 
C:\Program\BC45\INCLUDE\conio.h 20: 
C:\Program\BC45\INCLUDE\conio.h 21: 
C:\Program\BC45\INCLUDE\conio.h 22: 
C:\Program\BC45\INCLUDE\conio.h 23: 
C:\Program\BC45\INCLUDE\conio.h 24: 
C:\Program\BC45\INCLUDE\conio.h 25: 
C:\Program\BC45\INCLUDE\conio.h 26: 
C:\Program\BC45\INCLUDE\conio.h 27: 
C:\Program\BC45\INCLUDE\conio.h 28: #pragma option -a-
C:\Program\BC45\INCLUDE\conio.h 29: 
C:\Program\BC45\INCLUDE\conio.h 30: 
C:\Program\BC45\INCLUDE\conio.h 31: 
C:\Program\BC45\INCLUDE\conio.h 32: 
C:\Program\BC45\INCLUDE\conio.h 33: 
C:\Program\BC45\INCLUDE\conio.h 34: 
C:\Program\BC45\INCLUDE\conio.h 35: 
C:\Program\BC45\INCLUDE\conio.h 36: 
C:\Program\BC45\INCLUDE\conio.h 37: struct text_info {
C:\Program\BC45\INCLUDE\conio.h 38: unsigned char winleft;
C:\Program\BC45\INCLUDE\conio.h 39: unsigned char wintop;
C:\Program\BC45\INCLUDE\conio.h 40: unsigned char winright;
C:\Program\BC45\INCLUDE\conio.h 41: unsigned char winbottom;
C:\Program\BC45\INCLUDE\conio.h 42: unsigned char attribute;
C:\Program\BC45\INCLUDE\conio.h 43: unsigned char normattr;
C:\Program\BC45\INCLUDE\conio.h 44: unsigned char currmode;
C:\Program\BC45\INCLUDE\conio.h 45: unsigned char screenheight;
C:\Program\BC45\INCLUDE\conio.h 46: unsigned char screenwidth;
C:\Program\BC45\INCLUDE\conio.h 47: unsigned char curx;
C:\Program\BC45\INCLUDE\conio.h 48: unsigned char cury;
C:\Program\BC45\INCLUDE\conio.h 49: };
C:\Program\BC45\INCLUDE\conio.h 50: 
C:\Program\BC45\INCLUDE\conio.h 51: 
C:\Program\BC45\INCLUDE\conio.h 52: 
C:\Program\BC45\INCLUDE\conio.h 53: 
C:\Program\BC45\INCLUDE\conio.h 54: 
C:\Program\BC45\INCLUDE\conio.h 55: 
C:\Program\BC45\INCLUDE\conio.h 56: 
C:\Program\BC45\INCLUDE\conio.h 57: 
C:\Program\BC45\INCLUDE\conio.h 58: 
C:\Program\BC45\INCLUDE\conio.h 59: 
C:\Program\BC45\INCLUDE\conio.h 60: 
C:\Program\BC45\INCLUDE\conio.h 61: 
C:\Program\BC45\INCLUDE\conio.h 62: 
C:\Program\BC45\INCLUDE\conio.h 63: 
C:\Program\BC45\INCLUDE\conio.h 64: 
C:\Program\BC45\INCLUDE\conio.h 65: 
C:\Program\BC45\INCLUDE\conio.h 66: 
C:\Program\BC45\INCLUDE\conio.h 67: 
C:\Program\BC45\INCLUDE\conio.h 68: 
C:\Program\BC45\INCLUDE\conio.h 69: 
C:\Program\BC45\INCLUDE\conio.h 70: 
C:\Program\BC45\INCLUDE\conio.h 71: 
C:\Program\BC45\INCLUDE\conio.h 72: 
C:\Program\BC45\INCLUDE\conio.h 73: 
C:\Program\BC45\INCLUDE\conio.h 74: 
C:\Program\BC45\INCLUDE\conio.h 75: 
C:\Program\BC45\INCLUDE\conio.h 76: 
C:\Program\BC45\INCLUDE\conio.h 77: 
C:\Program\BC45\INCLUDE\conio.h 78: enum text_modes {  LASTMODE=-1,
C:\Program\BC45\INCLUDE\conio.h 79: BW40=0,
C:\Program\BC45\INCLUDE\conio.h 80: C40,
C:\Program\BC45\INCLUDE\conio.h 81: BW80,
C:\Program\BC45\INCLUDE\conio.h 82: C80,
C:\Program\BC45\INCLUDE\conio.h 83: MONO=7,
C:\Program\BC45\INCLUDE\conio.h 84: C4350=64 };
C:\Program\BC45\INCLUDE\conio.h 85: 
C:\Program\BC45\INCLUDE\conio.h 86:   
C:\Program\BC45\INCLUDE\conio.h 87: 
C:\Program\BC45\INCLUDE\conio.h 88:   
C:\Program\BC45\INCLUDE\conio.h 89: 
C:\Program\BC45\INCLUDE\conio.h 90: 
C:\Program\BC45\INCLUDE\conio.h 91: 
C:\Program\BC45\INCLUDE\conio.h 92: extern   int __cdecl _directvideo;
C:\Program\BC45\INCLUDE\conio.h 93: 
C:\Program\BC45\INCLUDE\conio.h 94: 
C:\Program\BC45\INCLUDE\conio.h 95: 
C:\Program\BC45\INCLUDE\conio.h 96: extern   int __cdecl _wscroll;
C:\Program\BC45\INCLUDE\conio.h 97: 
C:\Program\BC45\INCLUDE\conio.h 98: 
C:\Program\BC45\INCLUDE\conio.h 99: extern "C" {
C:\Program\BC45\INCLUDE\conio.h 100: 
C:\Program\BC45\INCLUDE\conio.h 101: 
C:\Program\BC45\INCLUDE\conio.h 102: void        __cdecl clreol( void );
C:\Program\BC45\INCLUDE\conio.h 103: void        __cdecl clrscr( void );
C:\Program\BC45\INCLUDE\conio.h 104: void        __cdecl gotoxy( int __x, int __y );
C:\Program\BC45\INCLUDE\conio.h 105: int         __cdecl getch( void );
C:\Program\BC45\INCLUDE\conio.h 106: int         __cdecl getche( void );
C:\Program\BC45\INCLUDE\conio.h 107: int         __cdecl kbhit( void );
C:\Program\BC45\INCLUDE\conio.h 108: int         __cdecl putch( int __c );
C:\Program\BC45\INCLUDE\conio.h 109: int         __cdecl wherex( void );
C:\Program\BC45\INCLUDE\conio.h 110: int         __cdecl wherey( void );
C:\Program\BC45\INCLUDE\conio.h 111: 
C:\Program\BC45\INCLUDE\conio.h 112: 
C:\Program\BC45\INCLUDE\conio.h 113: unsigned char   __cdecl inportb( unsigned __portid );
C:\Program\BC45\INCLUDE\conio.h 114: unsigned        __cdecl inport ( unsigned __portid );
C:\Program\BC45\INCLUDE\conio.h 115: int             __cdecl inp( unsigned __portid );
C:\Program\BC45\INCLUDE\conio.h 116: unsigned        __cdecl inpw( unsigned __portid );
C:\Program\BC45\INCLUDE\conio.h 117: void            __cdecl outportb( unsigned __portid, unsigned char __value );
C:\Program\BC45\INCLUDE\conio.h 118: void            __cdecl outport ( unsigned __portid, unsigned __value );
C:\Program\BC45\INCLUDE\conio.h 119: int             __cdecl outp( unsigned __portid, int __value );
C:\Program\BC45\INCLUDE\conio.h 120: unsigned        __cdecl outpw( unsigned __portid, unsigned __value );
C:\Program\BC45\INCLUDE\conio.h 121: 
C:\Program\BC45\INCLUDE\conio.h 122: 
C:\Program\BC45\INCLUDE\conio.h 123:   
C:\Program\BC45\INCLUDE\conio.h 124: 
C:\Program\BC45\INCLUDE\conio.h 125: void        __cdecl delline( void );
C:\Program\BC45\INCLUDE\conio.h 126: int         __cdecl gettext( int __left, int __top,
C:\Program\BC45\INCLUDE\conio.h 127: int __right, int __bottom,
C:\Program\BC45\INCLUDE\conio.h 128: void *__destin);
C:\Program\BC45\INCLUDE\conio.h 129: void        __cdecl gettextinfo (struct text_info *__r );
C:\Program\BC45\INCLUDE\conio.h 130: void        __cdecl highvideo( void );
C:\Program\BC45\INCLUDE\conio.h 131: void        __cdecl insline( void );
C:\Program\BC45\INCLUDE\conio.h 132: void        __cdecl lowvideo( void );
C:\Program\BC45\INCLUDE\conio.h 133: int         __cdecl movetext( int __left, int __top,
C:\Program\BC45\INCLUDE\conio.h 134: int __right, int __bottom,
C:\Program\BC45\INCLUDE\conio.h 135: int __destleft, int __desttop );
C:\Program\BC45\INCLUDE\conio.h 136: void        __cdecl normvideo( void );
C:\Program\BC45\INCLUDE\conio.h 137: int         __cdecl puttext( int __left, int __top,
C:\Program\BC45\INCLUDE\conio.h 138: int __right, int __bottom,
C:\Program\BC45\INCLUDE\conio.h 139: void *__source );
C:\Program\BC45\INCLUDE\conio.h 140: void        __cdecl textattr( int __newattr );
C:\Program\BC45\INCLUDE\conio.h 141: void        __cdecl textbackground( int __newcolor );
C:\Program\BC45\INCLUDE\conio.h 142: void        __cdecl textcolor( int __newcolor );
C:\Program\BC45\INCLUDE\conio.h 143: void        __cdecl textmode( int __newmode );
C:\Program\BC45\INCLUDE\conio.h 144: void        __cdecl window( int __left, int __top, int __right, int __bottom);
C:\Program\BC45\INCLUDE\conio.h 145: 
C:\Program\BC45\INCLUDE\conio.h 146: void        __cdecl _setcursortype( int __cur_t );
C:\Program\BC45\INCLUDE\conio.h 147: char *      __cdecl cgets( char *__str );
C:\Program\BC45\INCLUDE\conio.h 148: int         __cdecl cprintf( const char *__format, ... );
C:\Program\BC45\INCLUDE\conio.h 149: int         __cdecl cputs( const char *__str );
C:\Program\BC45\INCLUDE\conio.h 150: int         __cdecl cscanf( const char *__format, ... );
C:\Program\BC45\INCLUDE\conio.h 151: char *      __cdecl getpass( const char *__prompt );
C:\Program\BC45\INCLUDE\conio.h 152: int         __cdecl ungetch( int __ch );
C:\Program\BC45\INCLUDE\conio.h 153: 
C:\Program\BC45\INCLUDE\conio.h 154: 
C:\Program\BC45\INCLUDE\conio.h 155: 
C:\Program\BC45\INCLUDE\conio.h 156: 
C:\Program\BC45\INCLUDE\conio.h 157: 
C:\Program\BC45\INCLUDE\conio.h 158: 
C:\Program\BC45\INCLUDE\conio.h 159: 
C:\Program\BC45\INCLUDE\conio.h 160: 
C:\Program\BC45\INCLUDE\conio.h 161: 
C:\Program\BC45\INCLUDE\conio.h 162: unsigned char   __cdecl  __inportb__ (unsigned __portid);
C:\Program\BC45\INCLUDE\conio.h 163: unsigned        __cdecl  __inportw__ (unsigned __portid);
C:\Program\BC45\INCLUDE\conio.h 164: unsigned char   __cdecl  __outportb__(unsigned __portid, unsigned char __value);
C:\Program\BC45\INCLUDE\conio.h 165: unsigned        __cdecl  __outportw__(unsigned __portid, unsigned __value);
C:\Program\BC45\INCLUDE\conio.h 166: 
C:\Program\BC45\INCLUDE\conio.h 167: 
C:\Program\BC45\INCLUDE\conio.h 168: 
C:\Program\BC45\INCLUDE\conio.h 169: 
C:\Program\BC45\INCLUDE\conio.h 170: 
C:\Program\BC45\INCLUDE\conio.h 171: 
C:\Program\BC45\INCLUDE\conio.h 172: 
C:\Program\BC45\INCLUDE\conio.h 173: 
C:\Program\BC45\INCLUDE\conio.h 174: 
C:\Program\BC45\INCLUDE\conio.h 175: 
C:\Program\BC45\INCLUDE\conio.h 176: 
C:\Program\BC45\INCLUDE\conio.h 177: 
C:\Program\BC45\INCLUDE\conio.h 178: 
C:\Program\BC45\INCLUDE\conio.h 179: 
C:\Program\BC45\INCLUDE\conio.h 180: 
C:\Program\BC45\INCLUDE\conio.h 181: }
C:\Program\BC45\INCLUDE\conio.h 182: 
C:\Program\BC45\INCLUDE\conio.h 183: 
C:\Program\BC45\INCLUDE\conio.h 184: 
C:\Program\BC45\INCLUDE\conio.h 185: 
C:\Program\BC45\INCLUDE\conio.h 186: 
C:\Program\BC45\INCLUDE\conio.h 187: 
C:\Program\BC45\INCLUDE\conio.h 188: 
C:\Program\BC45\INCLUDE\conio.h 189: 
C:\Program\BC45\INCLUDE\conio.h 190: 
C:\Program\BC45\INCLUDE\conio.h 191: 
C:\Program\BC45\INCLUDE\conio.h 192: 
C:\Program\BC45\INCLUDE\conio.h 193: 
C:\Program\BC45\INCLUDE\conio.h 194: 
C:\Program\BC45\INCLUDE\conio.h 195: 
C:\Program\BC45\INCLUDE\conio.h 196: 
C:\Program\BC45\INCLUDE\conio.h 197: 
C:\Program\BC45\INCLUDE\conio.h 198: 
C:\Program\BC45\INCLUDE\conio.h 199: 
C:\Program\BC45\INCLUDE\conio.h 200: 
C:\Program\BC45\INCLUDE\conio.h 201: 
C:\Program\BC45\INCLUDE\conio.h 202: 
C:\Program\BC45\INCLUDE\conio.h 203: 
C:\Program\BC45\INCLUDE\conio.h 204: 
C:\Program\BC45\INCLUDE\conio.h 205: 
C:\Program\BC45\INCLUDE\conio.h 206: 
C:\Program\BC45\INCLUDE\conio.h 207: 
C:\Program\BC45\INCLUDE\conio.h 208: 
C:\Program\BC45\INCLUDE\conio.h 209: 
C:\Program\BC45\INCLUDE\conio.h 210: 
C:\Program\BC45\INCLUDE\conio.h 211: 
C:\Program\BC45\INCLUDE\conio.h 212: 
C:\Program\BC45\INCLUDE\conio.h 213: 
C:\Program\BC45\INCLUDE\conio.h 214: 
C:\Program\BC45\INCLUDE\conio.h 215: 
C:\Program\BC45\INCLUDE\conio.h 216: 
C:\Program\BC45\INCLUDE\conio.h 217: 
C:\Program\BC45\INCLUDE\conio.h 218: 
C:\Program\BC45\INCLUDE\conio.h 219: 
C:\Program\BC45\INCLUDE\conio.h 220: 
C:\Program\BC45\INCLUDE\conio.h 221: 
C:\Program\BC45\INCLUDE\conio.h 222: 
C:\Program\BC45\INCLUDE\conio.h 223: 
C:\Program\BC45\INCLUDE\conio.h 224: 
C:\Program\BC45\INCLUDE\conio.h 225: 
C:\Program\BC45\INCLUDE\conio.h 226: 
C:\Program\BC45\INCLUDE\conio.h 227: 
C:\Program\BC45\INCLUDE\conio.h 228: 
C:\Program\BC45\INCLUDE\conio.h 229: 
C:\Program\BC45\INCLUDE\conio.h 230: 
C:\Program\BC45\INCLUDE\conio.h 231: 
C:\Program\BC45\INCLUDE\conio.h 232: 
C:\Program\BC45\INCLUDE\conio.h 233: 
C:\Program\BC45\INCLUDE\conio.h 234: 
C:\Program\BC45\INCLUDE\conio.h 235: 
C:\Program\BC45\INCLUDE\conio.h 236: 
C:\Program\BC45\INCLUDE\conio.h 237: 
C:\Program\BC45\INCLUDE\conio.h 238: 
C:\Program\BC45\INCLUDE\conio.h 239: 
C:\Program\BC45\INCLUDE\conio.h 240: 
C:\Program\BC45\INCLUDE\conio.h 241: 
C:\Program\BC45\INCLUDE\conio.h 242: 
C:\Program\BC45\INCLUDE\conio.h 243: 
C:\Program\BC45\INCLUDE\conio.h 244: 
C:\Program\BC45\INCLUDE\conio.h 245: 
C:\Program\BC45\INCLUDE\conio.h 246: 
C:\Program\BC45\INCLUDE\conio.h 247: 
C:\Program\BC45\INCLUDE\conio.h 248: 
C:\Program\BC45\INCLUDE\conio.h 249: 
C:\Program\BC45\INCLUDE\conio.h 250: 
C:\Program\BC45\INCLUDE\conio.h 251: 
C:\Program\BC45\INCLUDE\conio.h 252: 
C:\Program\BC45\INCLUDE\conio.h 253: 
C:\Program\BC45\INCLUDE\conio.h 254: 
C:\Program\BC45\INCLUDE\conio.h 255: 
C:\Program\BC45\INCLUDE\conio.h 256: 
C:\Program\BC45\INCLUDE\conio.h 257: 
C:\Program\BC45\INCLUDE\conio.h 258: 
C:\Program\BC45\INCLUDE\conio.h 259: 
C:\Program\BC45\INCLUDE\conio.h 260: 
C:\Program\BC45\INCLUDE\conio.h 261: 
C:\Program\BC45\INCLUDE\conio.h 262: 
C:\Program\BC45\INCLUDE\conio.h 263: 
C:\Program\BC45\INCLUDE\conio.h 264: 
C:\Program\BC45\INCLUDE\conio.h 265: 
C:\Program\BC45\INCLUDE\conio.h 266: 
C:\Program\BC45\INCLUDE\conio.h 267: 
C:\Program\BC45\INCLUDE\conio.h 268: 
C:\Program\BC45\INCLUDE\conio.h 269: 
C:\Program\BC45\INCLUDE\conio.h 270: 
C:\Program\BC45\INCLUDE\conio.h 271: 
C:\Program\BC45\INCLUDE\conio.h 272: 
C:\Program\BC45\INCLUDE\conio.h 273: 
C:\Program\BC45\INCLUDE\conio.h 274: 
C:\Program\BC45\INCLUDE\conio.h 275: 
C:\Program\BC45\INCLUDE\conio.h 276: 
C:\Program\BC45\INCLUDE\conio.h 277: 
C:\Program\BC45\INCLUDE\conio.h 278: 
C:\Program\BC45\INCLUDE\conio.h 279: 
C:\Program\BC45\INCLUDE\conio.h 280: 
C:\Program\BC45\INCLUDE\conio.h 281: 
C:\Program\BC45\INCLUDE\conio.h 282: 
C:\Program\BC45\INCLUDE\conio.h 283: 
C:\Program\BC45\INCLUDE\conio.h 284: 
C:\Program\BC45\INCLUDE\conio.h 285: 
C:\Program\BC45\INCLUDE\conio.h 286: 
C:\Program\BC45\INCLUDE\conio.h 287: 
C:\Program\BC45\INCLUDE\conio.h 288: 
C:\Program\BC45\INCLUDE\conio.h 289: 
C:\Program\BC45\INCLUDE\conio.h 290: 
C:\Program\BC45\INCLUDE\conio.h 291: 
C:\Program\BC45\INCLUDE\conio.h 292: 
C:\Program\BC45\INCLUDE\conio.h 293: 
C:\Program\BC45\INCLUDE\conio.h 294: 
C:\Program\BC45\INCLUDE\conio.h 295: 
C:\Program\BC45\INCLUDE\conio.h 296: 
C:\Program\BC45\INCLUDE\conio.h 297: 
C:\Program\BC45\INCLUDE\conio.h 298: 
C:\Program\BC45\INCLUDE\conio.h 299: 
C:\Program\BC45\INCLUDE\conio.h 300: 
C:\Program\BC45\INCLUDE\conio.h 301: 
C:\Program\BC45\INCLUDE\conio.h 302: 
C:\Program\BC45\INCLUDE\conio.h 303: 
C:\Program\BC45\INCLUDE\conio.h 304: #pragma option -a.
C:\Program\BC45\INCLUDE\conio.h 305: 
C:\Program\BC45\INCLUDE\conio.h 306: 
C:\Program\BC45\INCLUDE\conio.h 307: 
C:\Program\BC45\INCLUDE\conio.h 308: 
C:\Program\BC45\INCLUDE\conio.h 309: 
C:\Program\BC45\INCLUDE\conio.h 310: 
C:\Program\BC45\INCLUDE\conio.h 311: 
C:\Program\BC45\INCLUDE\conio.h 312: 
C:\Program\BC45\INCLUDE\conio.h 313: 
C:\Program\BC45\INCLUDE\conio.h 314: 
C:\Program\BC45\INCLUDE\conio.h 315: 
main.cpp 4: 
C:\Program\BC45\INCLUDE\dos.h 1: 
C:\Program\BC45\INCLUDE\dos.h 2: 
C:\Program\BC45\INCLUDE\dos.h 3: 
C:\Program\BC45\INCLUDE\dos.h 4: 
C:\Program\BC45\INCLUDE\dos.h 5: 
C:\Program\BC45\INCLUDE\dos.h 6: 
C:\Program\BC45\INCLUDE\dos.h 7: 
C:\Program\BC45\INCLUDE\dos.h 8: 
C:\Program\BC45\INCLUDE\dos.h 9: 
C:\Program\BC45\INCLUDE\dos.h 10: 
C:\Program\BC45\INCLUDE\dos.h 11: 
C:\Program\BC45\INCLUDE\dos.h 12: 
C:\Program\BC45\INCLUDE\dos.h 13: 
C:\Program\BC45\INCLUDE\dos.h 14: 
C:\Program\BC45\INCLUDE\dos.h 15: 
C:\Program\BC45\INCLUDE\dos.h 16: 
C:\Program\BC45\INCLUDE\dos.h 17: 
C:\Program\BC45\INCLUDE\dos.h 18: 
C:\Program\BC45\INCLUDE\dos.h 19: 
C:\Program\BC45\INCLUDE\dos.h 20: 
C:\Program\BC45\INCLUDE\dos.h 21: 
C:\Program\BC45\INCLUDE\dos.h 22: 
C:\Program\BC45\INCLUDE\dos.h 23: 
C:\Program\BC45\INCLUDE\dos.h 24: 
C:\Program\BC45\INCLUDE\dos.h 25: 
C:\Program\BC45\INCLUDE\dos.h 26: 
C:\Program\BC45\INCLUDE\dos.h 27: 
C:\Program\BC45\INCLUDE\dos.h 28: 
C:\Program\BC45\INCLUDE\dos.h 29: #pragma option -a-
C:\Program\BC45\INCLUDE\dos.h 30: 
C:\Program\BC45\INCLUDE\dos.h 31: 
C:\Program\BC45\INCLUDE\dos.h 32: 
C:\Program\BC45\INCLUDE\dos.h 33: 
C:\Program\BC45\INCLUDE\dos.h 34: 
C:\Program\BC45\INCLUDE\dos.h 35: extern "C" {
C:\Program\BC45\INCLUDE\dos.h 36: 
C:\Program\BC45\INCLUDE\dos.h 37: 
C:\Program\BC45\INCLUDE\dos.h 38: 
C:\Program\BC45\INCLUDE\dos.h 39: 
C:\Program\BC45\INCLUDE\dos.h 40: 
C:\Program\BC45\INCLUDE\dos.h 41: 
C:\Program\BC45\INCLUDE\dos.h 42: 
C:\Program\BC45\INCLUDE\dos.h 43: 
C:\Program\BC45\INCLUDE\dos.h 44: 
C:\Program\BC45\INCLUDE\dos.h 45: 
C:\Program\BC45\INCLUDE\dos.h 46: 
C:\Program\BC45\INCLUDE\dos.h 47: 
C:\Program\BC45\INCLUDE\dos.h 48: 
C:\Program\BC45\INCLUDE\dos.h 49: 
C:\Program\BC45\INCLUDE\dos.h 50: 
C:\Program\BC45\INCLUDE\dos.h 51: 
C:\Program\BC45\INCLUDE\dos.h 52: 
C:\Program\BC45\INCLUDE\dos.h 53: 
C:\Program\BC45\INCLUDE\dos.h 54: 
C:\Program\BC45\INCLUDE\dos.h 55: 
C:\Program\BC45\INCLUDE\dos.h 56: 
C:\Program\BC45\INCLUDE\dos.h 57: 
C:\Program\BC45\INCLUDE\dos.h 58: 
C:\Program\BC45\INCLUDE\dos.h 59: 
C:\Program\BC45\INCLUDE\dos.h 60: 
C:\Program\BC45\INCLUDE\dos.h 61: 
C:\Program\BC45\INCLUDE\dos.h 62: 
C:\Program\BC45\INCLUDE\dos.h 63: 
C:\Program\BC45\INCLUDE\dos.h 64: 
C:\Program\BC45\INCLUDE\dos.h 65: 
C:\Program\BC45\INCLUDE\dos.h 66: struct  dfree
C:\Program\BC45\INCLUDE\dos.h 67: {
C:\Program\BC45\INCLUDE\dos.h 68: unsigned df_avail;
C:\Program\BC45\INCLUDE\dos.h 69: unsigned df_total;
C:\Program\BC45\INCLUDE\dos.h 70: unsigned df_bsec;
C:\Program\BC45\INCLUDE\dos.h 71: unsigned df_sclus;
C:\Program\BC45\INCLUDE\dos.h 72: };
C:\Program\BC45\INCLUDE\dos.h 73: 
C:\Program\BC45\INCLUDE\dos.h 74: struct diskfree_t
C:\Program\BC45\INCLUDE\dos.h 75: {
C:\Program\BC45\INCLUDE\dos.h 76: unsigned total_clusters;
C:\Program\BC45\INCLUDE\dos.h 77: unsigned avail_clusters;
C:\Program\BC45\INCLUDE\dos.h 78: unsigned sectors_per_cluster;
C:\Program\BC45\INCLUDE\dos.h 79: unsigned bytes_per_sector;
C:\Program\BC45\INCLUDE\dos.h 80: };
C:\Program\BC45\INCLUDE\dos.h 81: 
C:\Program\BC45\INCLUDE\dos.h 82: struct time
C:\Program\BC45\INCLUDE\dos.h 83: {
C:\Program\BC45\INCLUDE\dos.h 84: unsigned char   ti_min;     
C:\Program\BC45\INCLUDE\dos.h 85: unsigned char   ti_hour;    
C:\Program\BC45\INCLUDE\dos.h 86: unsigned char   ti_hund;    
C:\Program\BC45\INCLUDE\dos.h 87: unsigned char   ti_sec;     
C:\Program\BC45\INCLUDE\dos.h 88: };
C:\Program\BC45\INCLUDE\dos.h 89: 
C:\Program\BC45\INCLUDE\dos.h 90: struct dostime_t
C:\Program\BC45\INCLUDE\dos.h 91: {
C:\Program\BC45\INCLUDE\dos.h 92: unsigned char hour;         
C:\Program\BC45\INCLUDE\dos.h 93: unsigned char minute;       
C:\Program\BC45\INCLUDE\dos.h 94: unsigned char second;       
C:\Program\BC45\INCLUDE\dos.h 95: unsigned char hsecond;      
C:\Program\BC45\INCLUDE\dos.h 96: };
C:\Program\BC45\INCLUDE\dos.h 97: 
C:\Program\BC45\INCLUDE\dos.h 98: struct date
C:\Program\BC45\INCLUDE\dos.h 99: {
C:\Program\BC45\INCLUDE\dos.h 100: int     da_year;        
C:\Program\BC45\INCLUDE\dos.h 101: char    da_day;     
C:\Program\BC45\INCLUDE\dos.h 102: char    da_mon;     
C:\Program\BC45\INCLUDE\dos.h 103: };
C:\Program\BC45\INCLUDE\dos.h 104: 
C:\Program\BC45\INCLUDE\dos.h 105: struct dosdate_t
C:\Program\BC45\INCLUDE\dos.h 106: {
C:\Program\BC45\INCLUDE\dos.h 107: unsigned char day;      
C:\Program\BC45\INCLUDE\dos.h 108: unsigned char month;    
C:\Program\BC45\INCLUDE\dos.h 109: unsigned int  year;     
C:\Program\BC45\INCLUDE\dos.h 110: unsigned char dayofweek;
C:\Program\BC45\INCLUDE\dos.h 111: };
C:\Program\BC45\INCLUDE\dos.h 112: 
C:\Program\BC45\INCLUDE\dos.h 113: 
C:\Program\BC45\INCLUDE\dos.h 114: 
C:\Program\BC45\INCLUDE\dos.h 115: 
C:\Program\BC45\INCLUDE\dos.h 116: 
C:\Program\BC45\INCLUDE\dos.h 117: 
C:\Program\BC45\INCLUDE\dos.h 118: 
C:\Program\BC45\INCLUDE\dos.h 119: 
C:\Program\BC45\INCLUDE\dos.h 120: 
C:\Program\BC45\INCLUDE\dos.h 121: 
C:\Program\BC45\INCLUDE\dos.h 122: 
C:\Program\BC45\INCLUDE\dos.h 123: 
C:\Program\BC45\INCLUDE\dos.h 124: 
C:\Program\BC45\INCLUDE\dos.h 125: 
C:\Program\BC45\INCLUDE\dos.h 126: 
C:\Program\BC45\INCLUDE\dos.h 127: 
C:\Program\BC45\INCLUDE\dos.h 128: 
C:\Program\BC45\INCLUDE\dos.h 129: 
C:\Program\BC45\INCLUDE\dos.h 130: 
C:\Program\BC45\INCLUDE\dos.h 131: 
C:\Program\BC45\INCLUDE\dos.h 132: 
C:\Program\BC45\INCLUDE\dos.h 133: 
C:\Program\BC45\INCLUDE\dos.h 134: 
C:\Program\BC45\INCLUDE\dos.h 135: 
C:\Program\BC45\INCLUDE\dos.h 136: 
C:\Program\BC45\INCLUDE\dos.h 137: 
C:\Program\BC45\INCLUDE\dos.h 138: 
C:\Program\BC45\INCLUDE\dos.h 139: 
C:\Program\BC45\INCLUDE\dos.h 140: 
C:\Program\BC45\INCLUDE\dos.h 141: struct ffblk
C:\Program\BC45\INCLUDE\dos.h 142: {
C:\Program\BC45\INCLUDE\dos.h 143: char        ff_reserved[21];
C:\Program\BC45\INCLUDE\dos.h 144: char        ff_attrib;
C:\Program\BC45\INCLUDE\dos.h 145: unsigned    ff_ftime;
C:\Program\BC45\INCLUDE\dos.h 146: unsigned    ff_fdate;
C:\Program\BC45\INCLUDE\dos.h 147: long        ff_fsize;
C:\Program\BC45\INCLUDE\dos.h 148: char        ff_name[13];
C:\Program\BC45\INCLUDE\dos.h 149: };
C:\Program\BC45\INCLUDE\dos.h 150: 
C:\Program\BC45\INCLUDE\dos.h 151: 
C:\Program\BC45\INCLUDE\dos.h 152: struct find_t
C:\Program\BC45\INCLUDE\dos.h 153: {
C:\Program\BC45\INCLUDE\dos.h 154: char     reserved[21];      
C:\Program\BC45\INCLUDE\dos.h 155: char     attrib;            
C:\Program\BC45\INCLUDE\dos.h 156: unsigned wr_time;           
C:\Program\BC45\INCLUDE\dos.h 157: unsigned wr_date;           
C:\Program\BC45\INCLUDE\dos.h 158: long     size;              
C:\Program\BC45\INCLUDE\dos.h 159: char     name[13];          
C:\Program\BC45\INCLUDE\dos.h 160: };
C:\Program\BC45\INCLUDE\dos.h 161: 
C:\Program\BC45\INCLUDE\dos.h 162: 
C:\Program\BC45\INCLUDE\dos.h 163: 
C:\Program\BC45\INCLUDE\dos.h 164: void                           __emit__(unsigned char __byte, ...);
C:\Program\BC45\INCLUDE\dos.h 165: void     __cdecl             __int__(int __interruptnum);
C:\Program\BC45\INCLUDE\dos.h 166: unsigned __cdecl   _dos_close(int __fd);
C:\Program\BC45\INCLUDE\dos.h 167: unsigned __cdecl   _dos_creat(const char  *__pathP, unsigned __attr,
C:\Program\BC45\INCLUDE\dos.h 168: int  *__fd);
C:\Program\BC45\INCLUDE\dos.h 169: unsigned __cdecl   _dos_creatnew(const char  *__pathP, unsigned __attr,
C:\Program\BC45\INCLUDE\dos.h 170: int  *__fd);
C:\Program\BC45\INCLUDE\dos.h 171: unsigned __cdecl   _dos_findfirst(const char  *__path,
C:\Program\BC45\INCLUDE\dos.h 172: unsigned __attrib,
C:\Program\BC45\INCLUDE\dos.h 173: struct find_t  *__finfo);
C:\Program\BC45\INCLUDE\dos.h 174: unsigned __cdecl   _dos_findnext(struct find_t  *__finfo);
C:\Program\BC45\INCLUDE\dos.h 175: void     __cdecl   _dos_getdate(struct dosdate_t  *__datep);
C:\Program\BC45\INCLUDE\dos.h 176: unsigned __cdecl   _dos_getdiskfree(unsigned __drive,
C:\Program\BC45\INCLUDE\dos.h 177: struct diskfree_t  *__dtable);
C:\Program\BC45\INCLUDE\dos.h 178: void     __cdecl   _dos_getdrive(unsigned  *__drive);
C:\Program\BC45\INCLUDE\dos.h 179: unsigned __cdecl   _dos_getfileattr(const char  *__filename,
C:\Program\BC45\INCLUDE\dos.h 180: unsigned  *__attrib);
C:\Program\BC45\INCLUDE\dos.h 181: unsigned __cdecl   _dos_getftime(int __fd, unsigned  *__date,
C:\Program\BC45\INCLUDE\dos.h 182: unsigned  *__time);
C:\Program\BC45\INCLUDE\dos.h 183: void     __cdecl   _dos_gettime(struct dostime_t  *__timep);
C:\Program\BC45\INCLUDE\dos.h 184: unsigned __cdecl   _dos_open(const char  *__pathP, unsigned __oflag,
C:\Program\BC45\INCLUDE\dos.h 185: int  *__fd);
C:\Program\BC45\INCLUDE\dos.h 186: unsigned __cdecl   _dos_setdate(struct dosdate_t  *__datep);
C:\Program\BC45\INCLUDE\dos.h 187: void     __cdecl   _dos_setdrive(unsigned __drive, unsigned  *__ndrives);
C:\Program\BC45\INCLUDE\dos.h 188: unsigned __cdecl   _dos_setfileattr(const char  *__filename,
C:\Program\BC45\INCLUDE\dos.h 189: unsigned  __attrib);
C:\Program\BC45\INCLUDE\dos.h 190: unsigned __cdecl   _dos_setftime(int __fd, unsigned __date, unsigned __time);
C:\Program\BC45\INCLUDE\dos.h 191: unsigned __cdecl   _dos_settime(struct dostime_t  *__timep);
C:\Program\BC45\INCLUDE\dos.h 192: void     __cdecl     disable(void);
C:\Program\BC45\INCLUDE\dos.h 193: long     __cdecl     dostounix(struct date  *__d, struct time  *__t);
C:\Program\BC45\INCLUDE\dos.h 194: void     __cdecl     enable(void);
C:\Program\BC45\INCLUDE\dos.h 195: void     __cdecl  getdate(struct date  *__datep);
C:\Program\BC45\INCLUDE\dos.h 196: void     __cdecl   getdfree(unsigned char __drive,
C:\Program\BC45\INCLUDE\dos.h 197: struct dfree  *__dtable);
C:\Program\BC45\INCLUDE\dos.h 198: int      __cdecl   _getdrive(void);
C:\Program\BC45\INCLUDE\dos.h 199: void     __cdecl  gettime(struct time  *__timep);
C:\Program\BC45\INCLUDE\dos.h 200: void     __cdecl   setdate(struct date  *__datep);
C:\Program\BC45\INCLUDE\dos.h 201: void     __cdecl   settime( struct time  *__timep);
C:\Program\BC45\INCLUDE\dos.h 202: void     __cdecl     unixtodos(long __time, struct date  *__d,
C:\Program\BC45\INCLUDE\dos.h 203: struct time  *__t);
C:\Program\BC45\INCLUDE\dos.h 204: int      __cdecl  unlink(const char  *__path);
C:\Program\BC45\INCLUDE\dos.h 205: 
C:\Program\BC45\INCLUDE\dos.h 206: 
C:\Program\BC45\INCLUDE\dos.h 207: 
C:\Program\BC45\INCLUDE\dos.h 208: 
C:\Program\BC45\INCLUDE\dos.h 209: 
C:\Program\BC45\INCLUDE\dos.h 210: 
C:\Program\BC45\INCLUDE\dos.h 211: 
C:\Program\BC45\INCLUDE\dos.h 212: 
C:\Program\BC45\INCLUDE\dos.h 213: unsigned __cdecl             _dos_read(int __fd, void __far *__buf, unsigned __len,
C:\Program\BC45\INCLUDE\dos.h 214: unsigned  *__nread);
C:\Program\BC45\INCLUDE\dos.h 215: unsigned __cdecl             _dos_write(int __fd, const void __far *__buf, unsigned __len,
C:\Program\BC45\INCLUDE\dos.h 216: unsigned  *__nread );
C:\Program\BC45\INCLUDE\dos.h 217: 
C:\Program\BC45\INCLUDE\dos.h 218: 
C:\Program\BC45\INCLUDE\dos.h 219: 
C:\Program\BC45\INCLUDE\dos.h 220: 
C:\Program\BC45\INCLUDE\dos.h 221: 
C:\Program\BC45\INCLUDE\dos.h 222: 
C:\Program\BC45\INCLUDE\dos.h 223: 
C:\Program\BC45\INCLUDE\dos.h 224: 
C:\Program\BC45\INCLUDE\dos.h 225: 
C:\Program\BC45\INCLUDE\dos.h 226:   
C:\Program\BC45\INCLUDE\dos.h 227: 
C:\Program\BC45\INCLUDE\dos.h 228: struct  fcb
C:\Program\BC45\INCLUDE\dos.h 229: {
C:\Program\BC45\INCLUDE\dos.h 230: char    fcb_drive;      
C:\Program\BC45\INCLUDE\dos.h 231: char    fcb_name[8];    
C:\Program\BC45\INCLUDE\dos.h 232: char    fcb_ext[3];     
C:\Program\BC45\INCLUDE\dos.h 233: short   fcb_curblk;     
C:\Program\BC45\INCLUDE\dos.h 234: short   fcb_recsize;    
C:\Program\BC45\INCLUDE\dos.h 235: long    fcb_filsize;    
C:\Program\BC45\INCLUDE\dos.h 236: short   fcb_date;       
C:\Program\BC45\INCLUDE\dos.h 237: char    fcb_resv[10];   
C:\Program\BC45\INCLUDE\dos.h 238: char    fcb_currec;     
C:\Program\BC45\INCLUDE\dos.h 239: long    fcb_random;     
C:\Program\BC45\INCLUDE\dos.h 240: };
C:\Program\BC45\INCLUDE\dos.h 241: 
C:\Program\BC45\INCLUDE\dos.h 242: struct  xfcb
C:\Program\BC45\INCLUDE\dos.h 243: {
C:\Program\BC45\INCLUDE\dos.h 244: char       xfcb_flag;    
C:\Program\BC45\INCLUDE\dos.h 245: char       xfcb_resv[5]; 
C:\Program\BC45\INCLUDE\dos.h 246: char       xfcb_attr;    
C:\Program\BC45\INCLUDE\dos.h 247: struct fcb xfcb_fcb;     
C:\Program\BC45\INCLUDE\dos.h 248: };
C:\Program\BC45\INCLUDE\dos.h 249: 
C:\Program\BC45\INCLUDE\dos.h 250:   
C:\Program\BC45\INCLUDE\dos.h 251: 
C:\Program\BC45\INCLUDE\dos.h 252: 
C:\Program\BC45\INCLUDE\dos.h 253: 
C:\Program\BC45\INCLUDE\dos.h 254: 
C:\Program\BC45\INCLUDE\dos.h 255: 
C:\Program\BC45\INCLUDE\dos.h 256: 
C:\Program\BC45\INCLUDE\dos.h 257: 
C:\Program\BC45\INCLUDE\dos.h 258: 
C:\Program\BC45\INCLUDE\dos.h 259: struct  DOSERROR
C:\Program\BC45\INCLUDE\dos.h 260: {
C:\Program\BC45\INCLUDE\dos.h 261: int     de_exterror;
C:\Program\BC45\INCLUDE\dos.h 262: char    de_class;
C:\Program\BC45\INCLUDE\dos.h 263: char    de_action;
C:\Program\BC45\INCLUDE\dos.h 264: char    de_locus;
C:\Program\BC45\INCLUDE\dos.h 265: };
C:\Program\BC45\INCLUDE\dos.h 266: 
C:\Program\BC45\INCLUDE\dos.h 267: 
C:\Program\BC45\INCLUDE\dos.h 268: struct fatinfo
C:\Program\BC45\INCLUDE\dos.h 269: {
C:\Program\BC45\INCLUDE\dos.h 270: char     fi_sclus;
C:\Program\BC45\INCLUDE\dos.h 271: char     fi_fatid;
C:\Program\BC45\INCLUDE\dos.h 272: unsigned fi_nclus;
C:\Program\BC45\INCLUDE\dos.h 273: int      fi_bysec;
C:\Program\BC45\INCLUDE\dos.h 274: };
C:\Program\BC45\INCLUDE\dos.h 275: 
C:\Program\BC45\INCLUDE\dos.h 276: 
C:\Program\BC45\INCLUDE\dos.h 277: 
C:\Program\BC45\INCLUDE\dos.h 278: 
C:\Program\BC45\INCLUDE\dos.h 279: 
C:\Program\BC45\INCLUDE\dos.h 280: 
C:\Program\BC45\INCLUDE\dos.h 281: 
C:\Program\BC45\INCLUDE\dos.h 282: 
C:\Program\BC45\INCLUDE\dos.h 283: 
C:\Program\BC45\INCLUDE\dos.h 284: 
C:\Program\BC45\INCLUDE\dos.h 285: 
C:\Program\BC45\INCLUDE\dos.h 286: 
C:\Program\BC45\INCLUDE\dos.h 287: 
C:\Program\BC45\INCLUDE\dos.h 288: 
C:\Program\BC45\INCLUDE\dos.h 289: 
C:\Program\BC45\INCLUDE\dos.h 290: 
C:\Program\BC45\INCLUDE\dos.h 291: 
C:\Program\BC45\INCLUDE\dos.h 292: 
C:\Program\BC45\INCLUDE\dos.h 293: 
C:\Program\BC45\INCLUDE\dos.h 294: 
C:\Program\BC45\INCLUDE\dos.h 295: 
C:\Program\BC45\INCLUDE\dos.h 296: 
C:\Program\BC45\INCLUDE\dos.h 297: 
C:\Program\BC45\INCLUDE\dos.h 298: 
C:\Program\BC45\INCLUDE\dos.h 299: 
C:\Program\BC45\INCLUDE\dos.h 300: 
C:\Program\BC45\INCLUDE\dos.h 301: struct WORDREGS
C:\Program\BC45\INCLUDE\dos.h 302: {
C:\Program\BC45\INCLUDE\dos.h 303: unsigned short ax; 
C:\Program\BC45\INCLUDE\dos.h 304: unsigned short bx; 
C:\Program\BC45\INCLUDE\dos.h 305: unsigned short cx; 
C:\Program\BC45\INCLUDE\dos.h 306: unsigned short dx; 
C:\Program\BC45\INCLUDE\dos.h 307: unsigned short si; 
C:\Program\BC45\INCLUDE\dos.h 308: unsigned short di; 
C:\Program\BC45\INCLUDE\dos.h 309: unsigned short cflag;
C:\Program\BC45\INCLUDE\dos.h 310: unsigned short flags;
C:\Program\BC45\INCLUDE\dos.h 311: };
C:\Program\BC45\INCLUDE\dos.h 312: 
C:\Program\BC45\INCLUDE\dos.h 313: struct BYTEREGS
C:\Program\BC45\INCLUDE\dos.h 314: {
C:\Program\BC45\INCLUDE\dos.h 315: unsigned char al;
C:\Program\BC45\INCLUDE\dos.h 316: unsigned char ah; 
C:\Program\BC45\INCLUDE\dos.h 317: unsigned char bl;
C:\Program\BC45\INCLUDE\dos.h 318: unsigned char bh; 
C:\Program\BC45\INCLUDE\dos.h 319: unsigned char cl;
C:\Program\BC45\INCLUDE\dos.h 320: unsigned char ch; 
C:\Program\BC45\INCLUDE\dos.h 321: unsigned char dl;
C:\Program\BC45\INCLUDE\dos.h 322: unsigned char dh; 
C:\Program\BC45\INCLUDE\dos.h 323: };
C:\Program\BC45\INCLUDE\dos.h 324: 
C:\Program\BC45\INCLUDE\dos.h 325: union REGS
C:\Program\BC45\INCLUDE\dos.h 326: {
C:\Program\BC45\INCLUDE\dos.h 327: 
C:\Program\BC45\INCLUDE\dos.h 328: 
C:\Program\BC45\INCLUDE\dos.h 329: 
C:\Program\BC45\INCLUDE\dos.h 330: struct  WORDREGS  x;
C:\Program\BC45\INCLUDE\dos.h 331: 
C:\Program\BC45\INCLUDE\dos.h 332: struct  WORDREGS  w;
C:\Program\BC45\INCLUDE\dos.h 333: struct  BYTEREGS  h;
C:\Program\BC45\INCLUDE\dos.h 334: };
C:\Program\BC45\INCLUDE\dos.h 335: 
C:\Program\BC45\INCLUDE\dos.h 336: struct SREGS
C:\Program\BC45\INCLUDE\dos.h 337: {
C:\Program\BC45\INCLUDE\dos.h 338: unsigned short es;
C:\Program\BC45\INCLUDE\dos.h 339: unsigned short cs;
C:\Program\BC45\INCLUDE\dos.h 340: unsigned short ss;
C:\Program\BC45\INCLUDE\dos.h 341: unsigned short ds;
C:\Program\BC45\INCLUDE\dos.h 342: 
C:\Program\BC45\INCLUDE\dos.h 343: 
C:\Program\BC45\INCLUDE\dos.h 344: 
C:\Program\BC45\INCLUDE\dos.h 345: 
C:\Program\BC45\INCLUDE\dos.h 346: 
C:\Program\BC45\INCLUDE\dos.h 347: };
C:\Program\BC45\INCLUDE\dos.h 348: 
C:\Program\BC45\INCLUDE\dos.h 349: 
C:\Program\BC45\INCLUDE\dos.h 350: struct REGPACK
C:\Program\BC45\INCLUDE\dos.h 351: {
C:\Program\BC45\INCLUDE\dos.h 352: unsigned    r_ax, r_bx, r_cx, r_dx;
C:\Program\BC45\INCLUDE\dos.h 353: unsigned    r_bp, r_si, r_di, r_ds, r_es, r_flags;
C:\Program\BC45\INCLUDE\dos.h 354: };
C:\Program\BC45\INCLUDE\dos.h 355: 
C:\Program\BC45\INCLUDE\dos.h 356: 
C:\Program\BC45\INCLUDE\dos.h 357: 
C:\Program\BC45\INCLUDE\dos.h 358: 
C:\Program\BC45\INCLUDE\dos.h 359: 
C:\Program\BC45\INCLUDE\dos.h 360: int           __cdecl    bdos(int __dosfun, unsigned __dosdx, unsigned __dosal);
C:\Program\BC45\INCLUDE\dos.h 361: int           __cdecl            bdosptr(int __dosfun, void  *__argument,
C:\Program\BC45\INCLUDE\dos.h 362: unsigned __dosal);
C:\Program\BC45\INCLUDE\dos.h 363: void          __cdecl             ctrlbrk(int __cdecl (*handler)(void));
C:\Program\BC45\INCLUDE\dos.h 364: unsigned      __cdecl             _dos_commit(int __fd);
C:\Program\BC45\INCLUDE\dos.h 365: int           __cdecl   dosexterr( struct DOSERROR  *__eblkp );
C:\Program\BC45\INCLUDE\dos.h 366: int           __cdecl             getcbrk(void);
C:\Program\BC45\INCLUDE\dos.h 367: void          __cdecl             getfat(unsigned char __drive,
C:\Program\BC45\INCLUDE\dos.h 368: struct fatinfo  *__dtable);
C:\Program\BC45\INCLUDE\dos.h 369: void          __cdecl             getfatd(struct fatinfo  *__dtable);
C:\Program\BC45\INCLUDE\dos.h 370: unsigned      __cdecl             getpsp(void);
C:\Program\BC45\INCLUDE\dos.h 371: char  *   __cdecl             parsfnm(const char  *__cmdline,
C:\Program\BC45\INCLUDE\dos.h 372: struct fcb  *__fcb, int __opt);
C:\Program\BC45\INCLUDE\dos.h 373: int           __cdecl             peek(unsigned __segment, unsigned __offset);
C:\Program\BC45\INCLUDE\dos.h 374: char          __cdecl             peekb(unsigned __segment, unsigned __offset);
C:\Program\BC45\INCLUDE\dos.h 375: void          __cdecl             poke(unsigned __segment, unsigned __offset, int __value);
C:\Program\BC45\INCLUDE\dos.h 376: void          __cdecl             pokeb(unsigned __segment, unsigned __offset, char __value);
C:\Program\BC45\INCLUDE\dos.h 377: void          __cdecl             segread(struct SREGS  *__segp);
C:\Program\BC45\INCLUDE\dos.h 378: int           __cdecl             setcbrk(int __cbrkvalue);
C:\Program\BC45\INCLUDE\dos.h 379: 
C:\Program\BC45\INCLUDE\dos.h 380: 
C:\Program\BC45\INCLUDE\dos.h 381: 
C:\Program\BC45\INCLUDE\dos.h 382: 
C:\Program\BC45\INCLUDE\dos.h 383: 
C:\Program\BC45\INCLUDE\dos.h 384: 
C:\Program\BC45\INCLUDE\dos.h 385: 
C:\Program\BC45\INCLUDE\dos.h 386: 
C:\Program\BC45\INCLUDE\dos.h 387: 
C:\Program\BC45\INCLUDE\dos.h 388: 
C:\Program\BC45\INCLUDE\dos.h 389: char __far *  __cdecl             getdta(void);
C:\Program\BC45\INCLUDE\dos.h 390: int           __cdecl             int86(int __intno, union REGS  *__inregs,
C:\Program\BC45\INCLUDE\dos.h 391: union REGS  *__outregs);
C:\Program\BC45\INCLUDE\dos.h 392: int           __cdecl             int86x(int __intno, union REGS  *__inregs,
C:\Program\BC45\INCLUDE\dos.h 393: union REGS  *__outregs,
C:\Program\BC45\INCLUDE\dos.h 394: struct SREGS  *__segregs );
C:\Program\BC45\INCLUDE\dos.h 395: int           __cdecl             intdos(union REGS  *__inregs,
C:\Program\BC45\INCLUDE\dos.h 396: union REGS  *__outregs );
C:\Program\BC45\INCLUDE\dos.h 397: int           __cdecl             intdosx(union REGS  *__inregs,
C:\Program\BC45\INCLUDE\dos.h 398: union REGS  *__outregs,
C:\Program\BC45\INCLUDE\dos.h 399: struct SREGS  *__segregs );
C:\Program\BC45\INCLUDE\dos.h 400: void          __cdecl             intr(int __intno, struct REGPACK  *__preg);
C:\Program\BC45\INCLUDE\dos.h 401: void          __cdecl             setdta(char __far *__dta);
C:\Program\BC45\INCLUDE\dos.h 402: 
C:\Program\BC45\INCLUDE\dos.h 403: 
C:\Program\BC45\INCLUDE\dos.h 404: 
C:\Program\BC45\INCLUDE\dos.h 405: 
C:\Program\BC45\INCLUDE\dos.h 406: 
C:\Program\BC45\INCLUDE\dos.h 407: 
C:\Program\BC45\INCLUDE\dos.h 408: 
C:\Program\BC45\INCLUDE\dos.h 409: 
C:\Program\BC45\INCLUDE\dos.h 410: 
C:\Program\BC45\INCLUDE\dos.h 411: 
C:\Program\BC45\INCLUDE\dos.h 412: 
C:\Program\BC45\INCLUDE\dos.h 413: 
C:\Program\BC45\INCLUDE\dos.h 414: 
C:\Program\BC45\INCLUDE\dos.h 415: 
C:\Program\BC45\INCLUDE\dos.h 416: 
C:\Program\BC45\INCLUDE\dos.h 417: 
C:\Program\BC45\INCLUDE\dos.h 418: 
C:\Program\BC45\INCLUDE\dos.h 419: 
C:\Program\BC45\INCLUDE\dos.h 420: 
C:\Program\BC45\INCLUDE\dos.h 421: 
C:\Program\BC45\INCLUDE\dos.h 422: 
C:\Program\BC45\INCLUDE\dos.h 423: 
C:\Program\BC45\INCLUDE\dos.h 424: 
C:\Program\BC45\INCLUDE\dos.h 425: 
C:\Program\BC45\INCLUDE\dos.h 426: 
C:\Program\BC45\INCLUDE\dos.h 427: 
C:\Program\BC45\INCLUDE\dos.h 428: 
C:\Program\BC45\INCLUDE\dos.h 429: 
C:\Program\BC45\INCLUDE\dos.h 430: 
C:\Program\BC45\INCLUDE\dos.h 431: 
C:\Program\BC45\INCLUDE\dos.h 432: 
C:\Program\BC45\INCLUDE\dos.h 433: 
C:\Program\BC45\INCLUDE\dos.h 434: 
C:\Program\BC45\INCLUDE\dos.h 435:   
C:\Program\BC45\INCLUDE\dos.h 436: 
C:\Program\BC45\INCLUDE\dos.h 437: struct  COUNTRY
C:\Program\BC45\INCLUDE\dos.h 438: {
C:\Program\BC45\INCLUDE\dos.h 439: short   co_date;
C:\Program\BC45\INCLUDE\dos.h 440: char    co_curr[5];
C:\Program\BC45\INCLUDE\dos.h 441: char    co_thsep[2];
C:\Program\BC45\INCLUDE\dos.h 442: char    co_desep[2];
C:\Program\BC45\INCLUDE\dos.h 443: char    co_dtsep[2];
C:\Program\BC45\INCLUDE\dos.h 444: char    co_tmsep[2];
C:\Program\BC45\INCLUDE\dos.h 445: char    co_currstyle;
C:\Program\BC45\INCLUDE\dos.h 446: char    co_digits;
C:\Program\BC45\INCLUDE\dos.h 447: char    co_time;
C:\Program\BC45\INCLUDE\dos.h 448: long    co_case;
C:\Program\BC45\INCLUDE\dos.h 449: char    co_dasep[2];
C:\Program\BC45\INCLUDE\dos.h 450: char    co_fill[10];
C:\Program\BC45\INCLUDE\dos.h 451: };
C:\Program\BC45\INCLUDE\dos.h 452: 
C:\Program\BC45\INCLUDE\dos.h 453: struct COUNTRY  * __cdecl  country(int __xcode,
C:\Program\BC45\INCLUDE\dos.h 454: struct COUNTRY  *__cp);
C:\Program\BC45\INCLUDE\dos.h 455: int                   __cdecl  getverify(void);
C:\Program\BC45\INCLUDE\dos.h 456: void                  __cdecl  setverify(int __value);
C:\Program\BC45\INCLUDE\dos.h 457: 
C:\Program\BC45\INCLUDE\dos.h 458: 
C:\Program\BC45\INCLUDE\dos.h 459: 
C:\Program\BC45\INCLUDE\dos.h 460: 
C:\Program\BC45\INCLUDE\dos.h 461:     
C:\Program\BC45\INCLUDE\dos.h 462: void __cdecl delay(unsigned __milliseconds);
C:\Program\BC45\INCLUDE\dos.h 463: void __cdecl  nosound(void);
C:\Program\BC45\INCLUDE\dos.h 464: void __cdecl  sound(unsigned __frequency);
C:\Program\BC45\INCLUDE\dos.h 465: 
C:\Program\BC45\INCLUDE\dos.h 466: 
C:\Program\BC45\INCLUDE\dos.h 467: 
C:\Program\BC45\INCLUDE\dos.h 468: 
C:\Program\BC45\INCLUDE\dos.h 469: 
C:\Program\BC45\INCLUDE\dos.h 470: struct  devhdr
C:\Program\BC45\INCLUDE\dos.h 471: {
C:\Program\BC45\INCLUDE\dos.h 472: long        dh_next;        
C:\Program\BC45\INCLUDE\dos.h 473: short       dh_attr;        
C:\Program\BC45\INCLUDE\dos.h 474: unsigned short  dh_strat;   
C:\Program\BC45\INCLUDE\dos.h 475: unsigned short  dh_inter;   
C:\Program\BC45\INCLUDE\dos.h 476: char        dh_name[8];     
C:\Program\BC45\INCLUDE\dos.h 477: };
C:\Program\BC45\INCLUDE\dos.h 478: 
C:\Program\BC45\INCLUDE\dos.h 479: typedef struct
C:\Program\BC45\INCLUDE\dos.h 480: {
C:\Program\BC45\INCLUDE\dos.h 481: char    ds_drive;          
C:\Program\BC45\INCLUDE\dos.h 482: char    ds_pattern [13];   
C:\Program\BC45\INCLUDE\dos.h 483: char    ds_reserved [7];   
C:\Program\BC45\INCLUDE\dos.h 484: char    ds_attrib;
C:\Program\BC45\INCLUDE\dos.h 485: short   ds_time;
C:\Program\BC45\INCLUDE\dos.h 486: short   ds_date;
C:\Program\BC45\INCLUDE\dos.h 487: long    ds_size;
C:\Program\BC45\INCLUDE\dos.h 488: char    ds_nameZ [13];     
C:\Program\BC45\INCLUDE\dos.h 489: }   dosSearchInfo;  
C:\Program\BC45\INCLUDE\dos.h 490: 
C:\Program\BC45\INCLUDE\dos.h 491: 
C:\Program\BC45\INCLUDE\dos.h 492: 
C:\Program\BC45\INCLUDE\dos.h 493: 
C:\Program\BC45\INCLUDE\dos.h 494: 
C:\Program\BC45\INCLUDE\dos.h 495: 
C:\Program\BC45\INCLUDE\dos.h 496: 
C:\Program\BC45\INCLUDE\dos.h 497: 
C:\Program\BC45\INCLUDE\dos.h 498: 
C:\Program\BC45\INCLUDE\dos.h 499: 
C:\Program\BC45\INCLUDE\dos.h 500: 
C:\Program\BC45\INCLUDE\dos.h 501: 
C:\Program\BC45\INCLUDE\dos.h 502: 
C:\Program\BC45\INCLUDE\dos.h 503: 
C:\Program\BC45\INCLUDE\dos.h 504: 
C:\Program\BC45\INCLUDE\dos.h 505: 
C:\Program\BC45\INCLUDE\dos.h 506: 
C:\Program\BC45\INCLUDE\dos.h 507: 
C:\Program\BC45\INCLUDE\dos.h 508: 
C:\Program\BC45\INCLUDE\dos.h 509: 
C:\Program\BC45\INCLUDE\dos.h 510: 
C:\Program\BC45\INCLUDE\dos.h 511: 
C:\Program\BC45\INCLUDE\dos.h 512: 
C:\Program\BC45\INCLUDE\dos.h 513: 
C:\Program\BC45\INCLUDE\dos.h 514: 
C:\Program\BC45\INCLUDE\dos.h 515: 
C:\Program\BC45\INCLUDE\dos.h 516: 
C:\Program\BC45\INCLUDE\dos.h 517: 
C:\Program\BC45\INCLUDE\dos.h 518: 
C:\Program\BC45\INCLUDE\dos.h 519: 
C:\Program\BC45\INCLUDE\dos.h 520: 
C:\Program\BC45\INCLUDE\dos.h 521: 
C:\Program\BC45\INCLUDE\dos.h 522: 
C:\Program\BC45\INCLUDE\dos.h 523: 
C:\Program\BC45\INCLUDE\dos.h 524: 
C:\Program\BC45\INCLUDE\dos.h 525: 
C:\Program\BC45\INCLUDE\dos.h 526: 
C:\Program\BC45\INCLUDE\dos.h 527: 
C:\Program\BC45\INCLUDE\dos.h 528: extern  int __cdecl  errno;
C:\Program\BC45\INCLUDE\dos.h 529: extern  int __cdecl  _doserrno;
C:\Program\BC45\INCLUDE\dos.h 530: 
C:\Program\BC45\INCLUDE\dos.h 531: 
C:\Program\BC45\INCLUDE\dos.h 532: 
C:\Program\BC45\INCLUDE\dos.h 533: 
C:\Program\BC45\INCLUDE\dos.h 534: 
C:\Program\BC45\INCLUDE\dos.h 535: 
C:\Program\BC45\INCLUDE\dos.h 536: 
C:\Program\BC45\INCLUDE\dos.h 537: 
C:\Program\BC45\INCLUDE\dos.h 538: 
C:\Program\BC45\INCLUDE\dos.h 539: 
C:\Program\BC45\INCLUDE\dos.h 540: 
C:\Program\BC45\INCLUDE\dos.h 541: extern  int           __cdecl _argc;
C:\Program\BC45\INCLUDE\dos.h 542: extern  char        **__cdecl _argv;
C:\Program\BC45\INCLUDE\dos.h 543: extern  unsigned      __cdecl _psp;
C:\Program\BC45\INCLUDE\dos.h 544: 
C:\Program\BC45\INCLUDE\dos.h 545: 
C:\Program\BC45\INCLUDE\dos.h 546: extern  int const     __cdecl _8087;
C:\Program\BC45\INCLUDE\dos.h 547: extern  char        **__cdecl _environ;
C:\Program\BC45\INCLUDE\dos.h 548: extern  unsigned      __cdecl _heaplen;
C:\Program\BC45\INCLUDE\dos.h 549: extern  unsigned char __cdecl _osmajor;
C:\Program\BC45\INCLUDE\dos.h 550: extern  unsigned char __cdecl _osminor;
C:\Program\BC45\INCLUDE\dos.h 551: extern  unsigned      __cdecl _stklen;
C:\Program\BC45\INCLUDE\dos.h 552: extern  unsigned      __cdecl _fpstklen;
C:\Program\BC45\INCLUDE\dos.h 553: extern  unsigned      __cdecl _version;
C:\Program\BC45\INCLUDE\dos.h 554: extern  unsigned      __cdecl _osversion;      
C:\Program\BC45\INCLUDE\dos.h 555: 
C:\Program\BC45\INCLUDE\dos.h 556: 
C:\Program\BC45\INCLUDE\dos.h 557: 
C:\Program\BC45\INCLUDE\dos.h 558: 
C:\Program\BC45\INCLUDE\dos.h 559: 
C:\Program\BC45\INCLUDE\dos.h 560: 
C:\Program\BC45\INCLUDE\dos.h 561: 
C:\Program\BC45\INCLUDE\dos.h 562: 
C:\Program\BC45\INCLUDE\dos.h 563: 
C:\Program\BC45\INCLUDE\dos.h 564:   
C:\Program\BC45\INCLUDE\dos.h 565: void     __cdecl  sleep(unsigned __seconds);
C:\Program\BC45\INCLUDE\dos.h 566: 
C:\Program\BC45\INCLUDE\dos.h 567: 
C:\Program\BC45\INCLUDE\dos.h 568: 
C:\Program\BC45\INCLUDE\dos.h 569: int      __cdecl  absread(int __drive, int __nsects, long __lsect,
C:\Program\BC45\INCLUDE\dos.h 570: void  *__buffer);
C:\Program\BC45\INCLUDE\dos.h 571: int      __cdecl  abswrite(int __drive, int __nsects, long __lsect,
C:\Program\BC45\INCLUDE\dos.h 572: void  *__buffer);
C:\Program\BC45\INCLUDE\dos.h 573: int      __cdecl  allocmem(unsigned __size, unsigned  *__segp);
C:\Program\BC45\INCLUDE\dos.h 574: unsigned __cdecl  _dos_allocmem(unsigned __size, unsigned  *__segp);
C:\Program\BC45\INCLUDE\dos.h 575: unsigned __cdecl  _dos_freemem(unsigned __segx);
C:\Program\BC45\INCLUDE\dos.h 576: void     __cdecl  _dos_keep(unsigned char __status, unsigned __size);
C:\Program\BC45\INCLUDE\dos.h 577: unsigned __cdecl  _dos_setblock(unsigned __size, unsigned __segx,
C:\Program\BC45\INCLUDE\dos.h 578: unsigned  *__maxp);
C:\Program\BC45\INCLUDE\dos.h 579: int      __cdecl  freemem(unsigned __segx);
C:\Program\BC45\INCLUDE\dos.h 580: void     __cdecl  keep(unsigned char __status, unsigned __size);
C:\Program\BC45\INCLUDE\dos.h 581: int      __cdecl  randbrd(struct fcb  *__fcb, int __rcnt);
C:\Program\BC45\INCLUDE\dos.h 582: int      __cdecl  randbwr(struct fcb  *__fcb, int __rcnt);
C:\Program\BC45\INCLUDE\dos.h 583: int      __cdecl  setblock(unsigned __segx, unsigned __newsize);
C:\Program\BC45\INCLUDE\dos.h 584: 
C:\Program\BC45\INCLUDE\dos.h 585: 
C:\Program\BC45\INCLUDE\dos.h 586: void     __cdecl  _harderr(void __cdecl (__far *__fptr)(unsigned __deverr,
C:\Program\BC45\INCLUDE\dos.h 587: unsigned __doserr, unsigned __far *__hdr));
C:\Program\BC45\INCLUDE\dos.h 588: 
C:\Program\BC45\INCLUDE\dos.h 589: 
C:\Program\BC45\INCLUDE\dos.h 590: 
C:\Program\BC45\INCLUDE\dos.h 591: 
C:\Program\BC45\INCLUDE\dos.h 592: void     __cdecl  _hardresume(int __axret);
C:\Program\BC45\INCLUDE\dos.h 593: void     __cdecl  _hardretn(int __retn);
C:\Program\BC45\INCLUDE\dos.h 594: 
C:\Program\BC45\INCLUDE\dos.h 595: 
C:\Program\BC45\INCLUDE\dos.h 596: void     __cdecl harderr(int __cdecl (*__handler)(int __errval, int __ax,
C:\Program\BC45\INCLUDE\dos.h 597: int __bp, int __si));
C:\Program\BC45\INCLUDE\dos.h 598: 
C:\Program\BC45\INCLUDE\dos.h 599: 
C:\Program\BC45\INCLUDE\dos.h 600: 
C:\Program\BC45\INCLUDE\dos.h 601: 
C:\Program\BC45\INCLUDE\dos.h 602: void     __cdecl hardresume(int __axret);
C:\Program\BC45\INCLUDE\dos.h 603: void     __cdecl hardretn(int __retn);
C:\Program\BC45\INCLUDE\dos.h 604: 
C:\Program\BC45\INCLUDE\dos.h 605: 
C:\Program\BC45\INCLUDE\dos.h 606: extern  unsigned    __cdecl  _ovrbuffer;
C:\Program\BC45\INCLUDE\dos.h 607: 
C:\Program\BC45\INCLUDE\dos.h 608: int      __cdecl __far _OvrInitEms(unsigned __emsHandle, unsigned __emsFirst,
C:\Program\BC45\INCLUDE\dos.h 609: unsigned __emsPages);
C:\Program\BC45\INCLUDE\dos.h 610: int      __cdecl __far _OvrInitExt(unsigned long __extStart,
C:\Program\BC45\INCLUDE\dos.h 611: unsigned long __extLength);
C:\Program\BC45\INCLUDE\dos.h 612: 
C:\Program\BC45\INCLUDE\dos.h 613: 
C:\Program\BC45\INCLUDE\dos.h 614: 
C:\Program\BC45\INCLUDE\dos.h 615: 
C:\Program\BC45\INCLUDE\dos.h 616: 
C:\Program\BC45\INCLUDE\dos.h 617: 
C:\Program\BC45\INCLUDE\dos.h 618: 
C:\Program\BC45\INCLUDE\dos.h 619: 
C:\Program\BC45\INCLUDE\dos.h 620: 
C:\Program\BC45\INCLUDE\dos.h 621: void __cdecl __cli__(void);
C:\Program\BC45\INCLUDE\dos.h 622: void __cdecl __sti__(void);
C:\Program\BC45\INCLUDE\dos.h 623: 
C:\Program\BC45\INCLUDE\dos.h 624: 
C:\Program\BC45\INCLUDE\dos.h 625: void        __cdecl _chain_intr(void __interrupt (__far *__target)(...));
C:\Program\BC45\INCLUDE\dos.h 626: void __interrupt (__far * __cdecl  _dos_getvect(unsigned __interruptno))(...);
C:\Program\BC45\INCLUDE\dos.h 627: void        __cdecl _dos_setvect(unsigned __interruptno,
C:\Program\BC45\INCLUDE\dos.h 628: void __interrupt(__far *__isr)(...));
C:\Program\BC45\INCLUDE\dos.h 629: void __interrupt (__far * __cdecl getvect(int __interruptno))(...);
C:\Program\BC45\INCLUDE\dos.h 630: void        __cdecl setvect(int __interruptno,
C:\Program\BC45\INCLUDE\dos.h 631: void __interrupt (__far *__isr)(...));
C:\Program\BC45\INCLUDE\dos.h 632: 
C:\Program\BC45\INCLUDE\dos.h 633: int  inline __cdecl  peek(unsigned __segment, unsigned __offset)
C:\Program\BC45\INCLUDE\dos.h 634: {
C:\Program\BC45\INCLUDE\dos.h 635: return (*((int __far *)((void __seg *)(__segment) + (void __near *)(__offset))));
C:\Program\BC45\INCLUDE\dos.h 636: }
C:\Program\BC45\INCLUDE\dos.h 637: 
C:\Program\BC45\INCLUDE\dos.h 638: char inline __cdecl  peekb(unsigned __segment, unsigned __offset)
C:\Program\BC45\INCLUDE\dos.h 639: {
C:\Program\BC45\INCLUDE\dos.h 640: return (*((char __far *)((void __seg *)(__segment) + (void __near *)(__offset))));
C:\Program\BC45\INCLUDE\dos.h 641: }
C:\Program\BC45\INCLUDE\dos.h 642: 
C:\Program\BC45\INCLUDE\dos.h 643: void inline __cdecl  poke(unsigned __segment, unsigned __offset, int __value)
C:\Program\BC45\INCLUDE\dos.h 644: {
C:\Program\BC45\INCLUDE\dos.h 645: (*((int __far *)((void __seg *)(__segment) + (void __near *)(__offset))) = __value);
C:\Program\BC45\INCLUDE\dos.h 646: }
C:\Program\BC45\INCLUDE\dos.h 647: 
C:\Program\BC45\INCLUDE\dos.h 648: void inline __cdecl  pokeb(unsigned __segment, unsigned __offset, char __value)
C:\Program\BC45\INCLUDE\dos.h 649: {
C:\Program\BC45\INCLUDE\dos.h 650: (*((char __far *)((void __seg *)(__segment) + (void __near *)(__offset))) = __value);
C:\Program\BC45\INCLUDE\dos.h 651: }
C:\Program\BC45\INCLUDE\dos.h 652: 
C:\Program\BC45\INCLUDE\dos.h 653: 
C:\Program\BC45\INCLUDE\dos.h 654: 
C:\Program\BC45\INCLUDE\dos.h 655: 
C:\Program\BC45\INCLUDE\dos.h 656: 
C:\Program\BC45\INCLUDE\dos.h 657: 
C:\Program\BC45\INCLUDE\dos.h 658: 
C:\Program\BC45\INCLUDE\dos.h 659: 
C:\Program\BC45\INCLUDE\dos.h 660: 
C:\Program\BC45\INCLUDE\dos.h 661: 
C:\Program\BC45\INCLUDE\dos.h 662: 
C:\Program\BC45\INCLUDE\dos.h 663: 
C:\Program\BC45\INCLUDE\dos.h 664: 
C:\Program\BC45\INCLUDE\dos.h 665: 
C:\Program\BC45\INCLUDE\dos.h 666: 
C:\Program\BC45\INCLUDE\dos.h 667: 
C:\Program\BC45\INCLUDE\dos.h 668: 
C:\Program\BC45\INCLUDE\dos.h 669: 
C:\Program\BC45\INCLUDE\dos.h 670: 
C:\Program\BC45\INCLUDE\dos.h 671: 
C:\Program\BC45\INCLUDE\dos.h 672: 
C:\Program\BC45\INCLUDE\dos.h 673: 
C:\Program\BC45\INCLUDE\dos.h 674: 
C:\Program\BC45\INCLUDE\dos.h 675: 
C:\Program\BC45\INCLUDE\dos.h 676: 
C:\Program\BC45\INCLUDE\dos.h 677: 
C:\Program\BC45\INCLUDE\dos.h 678: 
C:\Program\BC45\INCLUDE\dos.h 679: 
C:\Program\BC45\INCLUDE\dos.h 680: 
C:\Program\BC45\INCLUDE\dos.h 681: 
C:\Program\BC45\INCLUDE\dos.h 682: 
C:\Program\BC45\INCLUDE\dos.h 683: 
C:\Program\BC45\INCLUDE\dos.h 684: 
C:\Program\BC45\INCLUDE\dos.h 685: 
C:\Program\BC45\INCLUDE\dos.h 686: 
C:\Program\BC45\INCLUDE\dos.h 687: 
C:\Program\BC45\INCLUDE\dos.h 688: 
C:\Program\BC45\INCLUDE\dos.h 689: 
C:\Program\BC45\INCLUDE\dos.h 690: 
C:\Program\BC45\INCLUDE\dos.h 691: 
C:\Program\BC45\INCLUDE\dos.h 692: 
C:\Program\BC45\INCLUDE\dos.h 693: 
C:\Program\BC45\INCLUDE\dos.h 694: 
C:\Program\BC45\INCLUDE\dos.h 695: 
C:\Program\BC45\INCLUDE\dos.h 696: 
C:\Program\BC45\INCLUDE\dos.h 697: 
C:\Program\BC45\INCLUDE\dos.h 698: 
C:\Program\BC45\INCLUDE\dos.h 699: 
C:\Program\BC45\INCLUDE\dos.h 700: 
C:\Program\BC45\INCLUDE\dos.h 701: 
C:\Program\BC45\INCLUDE\dos.h 702: 
C:\Program\BC45\INCLUDE\dos.h 703: 
C:\Program\BC45\INCLUDE\dos.h 704: 
C:\Program\BC45\INCLUDE\dos.h 705: 
C:\Program\BC45\INCLUDE\dos.h 706: 
C:\Program\BC45\INCLUDE\dos.h 707: 
C:\Program\BC45\INCLUDE\dos.h 708: 
C:\Program\BC45\INCLUDE\dos.h 709: 
C:\Program\BC45\INCLUDE\dos.h 710: 
C:\Program\BC45\INCLUDE\dos.h 711: 
C:\Program\BC45\INCLUDE\dos.h 712: 
C:\Program\BC45\INCLUDE\dos.h 713: 
C:\Program\BC45\INCLUDE\dos.h 714: 
C:\Program\BC45\INCLUDE\dos.h 715: 
C:\Program\BC45\INCLUDE\dos.h 716: 
C:\Program\BC45\INCLUDE\dos.h 717: 
C:\Program\BC45\INCLUDE\dos.h 718: 
C:\Program\BC45\INCLUDE\dos.h 719: 
C:\Program\BC45\INCLUDE\dos.h 720: 
C:\Program\BC45\INCLUDE\dos.h 721: 
C:\Program\BC45\INCLUDE\dos.h 722: 
C:\Program\BC45\INCLUDE\dos.h 723: 
C:\Program\BC45\INCLUDE\dos.h 724: 
C:\Program\BC45\INCLUDE\dos.h 725: 
C:\Program\BC45\INCLUDE\dos.h 726: 
C:\Program\BC45\INCLUDE\dos.h 727: 
C:\Program\BC45\INCLUDE\dos.h 728: 
C:\Program\BC45\INCLUDE\dos.h 729: 
C:\Program\BC45\INCLUDE\dos.h 730: 
C:\Program\BC45\INCLUDE\dos.h 731: 
C:\Program\BC45\INCLUDE\dos.h 732: 
C:\Program\BC45\INCLUDE\dos.h 733: 
C:\Program\BC45\INCLUDE\dos.h 734: 
C:\Program\BC45\INCLUDE\dos.h 735: 
C:\Program\BC45\INCLUDE\dos.h 736: 
C:\Program\BC45\INCLUDE\dos.h 737: 
C:\Program\BC45\INCLUDE\dos.h 738: 
C:\Program\BC45\INCLUDE\dos.h 739: 
C:\Program\BC45\INCLUDE\dos.h 740: 
C:\Program\BC45\INCLUDE\dos.h 741: 
C:\Program\BC45\INCLUDE\dos.h 742: 
C:\Program\BC45\INCLUDE\dos.h 743: 
C:\Program\BC45\INCLUDE\dos.h 744: 
C:\Program\BC45\INCLUDE\dos.h 745: 
C:\Program\BC45\INCLUDE\dos.h 746: 
C:\Program\BC45\INCLUDE\dos.h 747: 
C:\Program\BC45\INCLUDE\dos.h 748: 
C:\Program\BC45\INCLUDE\dos.h 749: 
C:\Program\BC45\INCLUDE\dos.h 750: 
C:\Program\BC45\INCLUDE\dos.h 751: 
C:\Program\BC45\INCLUDE\dos.h 752: 
C:\Program\BC45\INCLUDE\dos.h 753: 
C:\Program\BC45\INCLUDE\dos.h 754: 
C:\Program\BC45\INCLUDE\dos.h 755: 
C:\Program\BC45\INCLUDE\dos.h 756: 
C:\Program\BC45\INCLUDE\dos.h 757: }
C:\Program\BC45\INCLUDE\dos.h 758: 
C:\Program\BC45\INCLUDE\dos.h 759: 
C:\Program\BC45\INCLUDE\dos.h 760: 
C:\Program\BC45\INCLUDE\dos.h 761: 
C:\Program\BC45\INCLUDE\dos.h 762: 
C:\Program\BC45\INCLUDE\dos.h 763: #pragma option -a. /* restore default packing */
C:\Program\BC45\INCLUDE\dos.h 764: 
C:\Program\BC45\INCLUDE\dos.h 765: 
C:\Program\BC45\INCLUDE\dos.h 766: 
C:\Program\BC45\INCLUDE\dos.h 767: 
C:\Program\BC45\INCLUDE\dos.h 768: 
C:\Program\BC45\INCLUDE\dos.h 769: 
C:\Program\BC45\INCLUDE\dos.h 770: 
C:\Program\BC45\INCLUDE\dos.h 771: 
C:\Program\BC45\INCLUDE\dos.h 772: 
C:\Program\BC45\INCLUDE\dos.h 773: 
C:\Program\BC45\INCLUDE\dos.h 774: 
main.cpp 5: 
main.cpp 6: void MakeArea();
main.cpp 7: void SetText();
main.cpp 8: void Play();
main.cpp 9: void Init();
main.cpp 10: void GameOver();
main.cpp 11: void Score(int score);
main.cpp 12: void InitGame();
main.cpp 13: 
main.cpp 14: Grafik g;
main.cpp 15: Mask m;
main.cpp 16: CDot dot;
main.cpp 17: 
main.cpp 18: int TotalScore=0;
main.cpp 19: 
main.cpp 20: void main()
main.cpp 21: {
main.cpp 22: char ch;
main.cpp 23: Init();
main.cpp 24: MakeArea();
main.cpp 25: InitGame();
main.cpp 26: Play();
main.cpp 27: g.Reset();
main.cpp 28: }
main.cpp 29: 
main.cpp 30: void Init()
main.cpp 31: {
main.cpp 32: g.Initialize();
main.cpp 33: m.SetLimits(2,2,g.GetMaxX()-170,g.GetMaxY()-1);
main.cpp 34: }
main.cpp 35: 
main.cpp 36: void InitGame()
main.cpp 37: {
main.cpp 38: m.Reset(g,20,2);
main.cpp 39: dot.RemoveDot(g);
main.cpp 40: TotalScore=0;
main.cpp 41: Score(0);
main.cpp 42: }
main.cpp 43: 
main.cpp 44: void MakeArea()
main.cpp 45: {
main.cpp 46: g.PaintLine(0,0,g.GetMaxX(),0);
main.cpp 47: g.PaintLine(0,g.GetMaxY(),g.GetMaxX(),g.GetMaxY());
main.cpp 48: g.PaintLine(0,0,0,g.GetMaxY());
main.cpp 49: g.PaintLine(g.GetMaxX(),0,g.GetMaxX(),g.GetMaxY());
main.cpp 50: g.PaintLine(g.GetMaxX()-170,0,g.GetMaxX()-170,g.GetMaxY());
main.cpp 51: g.PaintLine(g.GetMaxX()-170,g.GetMaxY()-130,g.GetMaxX(),g.GetMaxY()-130);
main.cpp 52: g.PaintLine(g.GetMaxX()-170,g.GetMaxY()-207,g.GetMaxX(),g.GetMaxY()-207);
main.cpp 53: SetText();
main.cpp 54: }
main.cpp 55: 
main.cpp 56: void SetText()
main.cpp 57: {
main.cpp 58: g.PrintText(g.GetMaxX()-160,7,"Score:");
main.cpp 59: 
main.cpp 60: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-200,"Keys");
main.cpp 61: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-187,"Arrows->Move Mask");
main.cpp 62: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-174,"R->Restart");
main.cpp 63: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-161,"P->Pause");
main.cpp 64: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-148,"Q->Quit");
main.cpp 65: 
main.cpp 66: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-123,"Return of the Mask!");
main.cpp 67: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-110,"(C) Viktor Gars and");
main.cpp 68: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-97,"Per Fingal 2001");
main.cpp 69: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-84,"Published by");
main.cpp 70: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-71,"VG Software");
main.cpp 71: g.PrintText(g.GetMaxX()-160,g.GetMaxY()-58,"www.vgsoftware.com");
main.cpp 72: }
main.cpp 73: 
main.cpp 74: void Play()
main.cpp 75: {
main.cpp 76: int direction(0);
main.cpp 77: char ch;
main.cpp 78: int MaxX=g.GetMaxX()-170;
main.cpp 79: int MaxY=g.GetMaxY()-1;
main.cpp 80: int RetVal(0);
main.cpp 81: int Speed(30);
main.cpp 82: char tmp;
main.cpp 83: getch();
main.cpp 84: g.PaintBox(50,100,5,100,9);
main.cpp 85: dot.PaintNewDot(g,MaxX,MaxY);
main.cpp 86: m.SetDot(dot);
main.cpp 87: do
main.cpp 88: {
main.cpp 89: while (!kbhit())
main.cpp 90: {
main.cpp 91: m.PaintMask(g);
main.cpp 92: delay(Speed);
main.cpp 93: RetVal=m.MoveMask(direction,g);
main.cpp 94: if(RetVal==1)
main.cpp 95: {
main.cpp 96: GameOver();
main.cpp 97: }
main.cpp 98: else if(RetVal==2)
main.cpp 99: {
main.cpp 100: dot.RemoveDot(g);
main.cpp 101: dot.PaintNewDot(g,MaxX,MaxY);
main.cpp 102: m.SetDot(dot);
main.cpp 103: m.AddMaskPart(15);
main.cpp 104: Score((125*m.GetNrMaskParts())/Speed);
main.cpp 105: Speed--;
main.cpp 106: }
main.cpp 107: };
main.cpp 108: ch=getch();
main.cpp 109: if(ch==72)
main.cpp 110: direction=1;
main.cpp 111: else if(ch==75)
main.cpp 112: direction=3;
main.cpp 113: else if(ch==77)
main.cpp 114: direction=2;
main.cpp 115: else if(ch==80)
main.cpp 116: direction=0;
main.cpp 117: else if(ch=='p'||ch=='P')
main.cpp 118: getch();
main.cpp 119: else if(ch=='r'||ch=='R')
main.cpp 120: {
main.cpp 121: g.ClearScreen();
main.cpp 122: InitGame();
main.cpp 123: MakeArea();
main.cpp 124: direction=2;
main.cpp 125: Speed=30;
main.cpp 126: dot.PaintNewDot(g,MaxX,MaxY);
main.cpp 127: m.SetDot(dot);
main.cpp 128: RetVal=0;
main.cpp 129: }
main.cpp 130: }while(ch!='q'&&RetVal!=1);
main.cpp 131: }
main.cpp 132: 
main.cpp 133: void GameOver()
main.cpp 134: {
main.cpp 135: g.ClearScreen();
main.cpp 136: g.PrintText(g.GetMaxX()/2,g.GetMaxY()/2-150,"Game Over!",12,1,0,4);
main.cpp 137: g.PrintText(g.GetMaxX()/2,g.GetMaxY()/2-50,"Press \"r\" to Restart!",12,1,0,2);
main.cpp 138: g.PrintText(g.GetMaxX()/2,g.GetMaxY()/2-25,"or",12,1,0,2);
main.cpp 139: g.PrintText(g.GetMaxX()/2,g.GetMaxY()/2,"Perss \"q\" to Quit!",12,1,0,2);
main.cpp 140: while (!kbhit())
main.cpp 141: {
main.cpp 142: };
main.cpp 143: }
main.cpp 144: 
main.cpp 145: void Score(int score)
main.cpp 146: {
main.cpp 147: char buffer[20];
main.cpp 148: TotalScore+=score;
main.cpp 149: g.PaintBox(g.GetMaxX()-100,6,90,10,0);
main.cpp 150: g.PrintText(g.GetMaxX()-40,7,itoa(TotalScore,buffer,10),14,2);
main.cpp 151: }
main.cpp 152: 
main.cpp 153: 
main.cpp 154: 
main.cpp 155: 
main.cpp 156: 
main.cpp 157: 