//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SaveEdit.rc
//
#define IDC_OK                          1
#define IDD_ABOUTBOX                    100
#define IDD_SAVEEDIT_FORM               101
#define ID_TEXT                         103
#define IDR_MAINFRAME                   128
#define IDR_SAVEEDTYPE                  129
#define IDD_MAN_DRIVER                  131
#define IDD_TEAMFINANCE                 133
#define IDD_WORK_ENGINEER               134
#define IDD_FILEINFO                    135
#define IDI_CLOSED                      137
#define IDI_OPEN                        138
#define IDI_TRACK                       139
#define IDI_DRIVER                      140
#define IDI_MECHANICS                   141
#define IDD_TRACK                       142
#define IDD_MAN_DESIGN                  143
#define IDD_MAN_ENGINEERING             144
#define IDD_MAN_COMMERCIAL              145
#define IDD_MAN_MECHANICS               146
#define IDI_COMMERCIAL                  147
#define IDD_MAIN                        148
#define IDC_INET                        149
#define IDI_DESIGN                      150
#define IDD_SPONSORS                    152
#define IDD_DEP_DESIGN                  155
#define IDD_DEP_ENGINEERING             156
#define IDD_DEP_MECHANICS               157
#define IDD_DEP_COMMERCIAL              159
#define IDD_LICENSING                   160
#define IDD_WORK_MECH                   162
#define IDD_WORK_DESIGN                 163
#define IDD_SPLATSH                     164
#define IDD_REGSCREEN                   165
#define IDI_ENGINEERING                 168
#define IDC_NAV_TREE                    1000
#define IDC_DRIVER_COMBO_COUNTRY        1000
#define IDC_INFO_PLAYER                 1001
#define IDC_DRIVER_EDIT_POINTS          1002
#define IDC_INFO_TEAM                   1002
#define IDC_DRIVER_COMBO_TEAM           1003
#define IDC_INFO_CURRENTYEAR            1003
#define IDC_INFO_CHPOINTS               1004
#define IDC_DRIVER_EDIT_SALARY          1005
#define IDC_INFO_CHPOS                  1005
#define IDC_INFO_NEXTRACE               1006
#define IDC_DRIVER_EDIT_SPEED           1006
#define IDC_INFO_SCORE                  1007
#define IDC_DRIVER_EDIT_SKILL           1007
#define IDC_INFO_SEASONS                1008
#define IDC_DRIVER_EDIT_OVERTAKING      1008
#define IDC_INFO_MODIFIED               1009
#define IDC_DRIVER_EDIT_WET             1009
#define IDC_INFO_CREATED                1010
#define IDC_DRIVER_EDIT_CONCENTRATION   1010
#define IDC_DRIVER_EDIT_EXPERIENCE      1011
#define IDC_TRACK_EDIT_LENGTH           1012
#define IDC_DRIVER_EDIT_STAMINA         1012
#define IDC_TRACK_EDIT_LAPS             1013
#define IDC_DRIVER_EDIT_MORALE          1013
#define IDC_DRIVER_EDIT_CH              1014
#define IDC_DRIVER_EDIT_AGE             1015
#define IDC_TRACK_EDIT_RECORD           1015
#define IDC_DRIVER_EDIT_RACEBONUS       1016
#define IDC_DRIVER_EDIT_CHBONUS         1017
#define IDC_DRIVER_EDIT_TOTALPOINTS     1018
#define IDC_TRACK_EDIT_YEAR             1018
#define IDC_DRIVER_EDIT_POINTFINISH     1019
#define IDC_TRACK_SPIN_LENGTH           1019
#define IDC_TRACK_SPIN_LAPS             1020
#define IDC_DRIVER_EDIT_WINS            1021
#define IDC_DRIVER_EDIT_FASTLAPS        1022
#define IDC_DRIVER_EDIT_POLE            1023
#define IDC_TRACK_COMBO_TEAM            1023
#define IDC_DRIVER_EDIT_RACES           1024
#define IDC_TRACK_COMBO_DRIVER          1024
#define IDC_TRACK_SPIN_YEAR             1025
#define IDC_DRIVER_SPIN_MORALE          1027
#define IDC_TEAMFINANCE_EDIT_VALUE1     1028
#define IDC_EDIT_PERFORMENCE_HYDRAULICS 1028
#define IDC_EDIT_FREEPRACTICE           1029
#define IDC_TEAMFINANCE_COMBO_TEAM      1030
#define IDC_TEAMFINANCE_COMBO_ENGINE    1031
#define IDC_TEAMFINANCE_COMBO_TYRE      1032
#define IDC_TEAMFINANCE_COMBO_FUEL      1033
#define IDC_TEAMFINANCE_COMBO_CASH1     1034
#define IDC_TEAMFINANCE_COMBO_CASH2     1035
#define IDC_SPIN_ACTIVESUSPENSION       1035
#define IDC_TEAMFINANCE_EDIT_VALUE2     1036
#define IDC_SPIN_CAR3WARE               1036
#define IDC_TEAMFINANCE_EDIT_VALUE3     1037
#define IDC_SPIN_PERFORMENCE_SUSPENSION 1037
#define IDC_TEAMFINANCE_EDIT_VALUE4     1038
#define IDC_SPIN_PERFORMENCE_THROTTLE   1038
#define IDC_TEAMFINANCE_EDIT_VALUE5     1039
#define IDC_SPIN_CAR4WARE               1039
#define IDC_DRIVER_SPIN_AGE             1040
#define IDC_TEAMFINANCE_EDIT_VALUE6     1040
#define IDC_SPIN_CAR2WARE               1040
#define IDC_DRIVER_SPIN_CH              1041
#define IDC_TEAMFINANCE_EDIT_VALUE7     1041
#define IDC_SPIN_CAR2DAMAGE             1041
#define IDC_TEAMFINANCE_EDIT_VALUE8     1042
#define IDC_SPIN_CAR1DAMAGE             1042
#define IDC_DRIVER_SPIN_FASTLAPS        1043
#define IDC_TEAMFINANCE_EDIT_VALUE9     1043
#define IDC_DRIVER_SPIN_POINTFINISH     1044
#define IDC_TEAMFINANCE_EDIT_VALUE10    1044
#define IDC_SPIN_RELIABILITY_THROTTLE   1044
#define IDC_DRIVER_SPIN_SKILL           1045
#define IDC_TEAMFINANCE_COMBO_CASH3     1045
#define IDC_SPIN_PERFORMENCE_GEARBOX    1045
#define IDC_DRIVER_SPIN_WET             1046
#define IDC_TEAMFINANCE_COMBO_CASH5     1046
#define IDC_SPIN_PERFORMENCE_ELECTRONICS 1046
#define IDC_DRIVER_SPIN_EXPERIENCE      1047
#define IDC_TEAMFINANCE_COMBO_CASH4     1047
#define IDC_SPIN_RELIABILITY_GEARBOX    1047
#define IDC_DRIVER_SPIN_SALARY          1048
#define IDC_TEAMFINANCE_COMBO_CASH6     1048
#define IDC_SPIN_RELIABILITY_ELECTRONICS 1048
#define IDC_DRIVER_SPIN_POLE            1049
#define IDC_SPIN_FREEPRACTICE           1049
#define IDC_SPIN_RELIABILITY_CLUTCH     1049
#define IDC_DRIVER_SPIN_POINTS          1050
#define IDC_SPIN_VALUE1                 1050
#define IDC_SPIN_CAR4DAMAGE             1050
#define IDC_DRIVER_SPIN_RACES           1051
#define IDC_SPIN_VALUE2                 1051
#define IDC_EDIT_FACTORY                1051
#define IDC_SPIN_PERFORMENCE_BREAKES    1051
#define IDC_DRIVER_SPIN_WINS            1052
#define IDC_SPIN_VALUE3                 1052
#define IDC_EDIT_CAM                    1052
#define IDC_SPIN_PERFORMENCE_CLUTCH     1052
#define IDC_DRIVER_SPIN_TOTALPOINTS     1053
#define IDC_SPIN_VALUE4                 1053
#define IDC_EDIT_TESTRIG                1053
#define IDC_SPIN_RELIABILITY_HYDRAULICS 1053
#define IDC_DRIVER_SPIN_RACEBONUS       1054
#define IDC_SPIN_VALUE5                 1054
#define IDC_EDIT_WINDTUNNEL             1054
#define IDC_SPIN_RELIABILITY_SUSPENSION 1054
#define IDC_DRIVER_SPIN_CHBONUS         1055
#define IDC_SPIN_VALUE6                 1055
#define IDC_SPIN_CAR3DAMAGE             1055
#define IDC_EDIT_WORKSHOP               1055
#define IDC_DRIVER_SPIN_SPEED           1056
#define IDC_SPIN_VALUE7                 1056
#define IDC_EDIT_CAD                    1056
#define IDC_SPIN_AUTOMATICGEARS         1056
#define IDC_DRIVER_SPIN_OVERTAKING      1057
#define IDC_SPIN_VALUE8                 1057
#define IDC_EDIT_SUPERCOMPUTER          1057
#define IDC_SPIN_RELIABILITY_BREAKES    1057
#define IDC_DRIVER_SPIN_CONCENTRATION   1058
#define IDC_SPIN_VALUE9                 1058
#define IDC_SPIN_FACTORY                1058
#define IDC_SPIN_PERFORMENCE_HYDRAULICS 1058
#define IDC_DRIVER_SPIN_STAMINA         1059
#define IDC_SPIN_VALUE10                1059
#define IDC_SPIN_CAM                    1059
#define IDC_SPIN_CAR1WARE               1059
#define IDC_SPIN_TESTRIG                1060
#define IDC_EDIT_SALARY                 1060
#define IDC_SPIN_POWERBREAKES           1060
#define IDC_SPIN_CAD                    1061
#define IDC_EDIT_ROYALTY                1061
#define IDC_SPIN_TRACTIONCONTROL        1061
#define IDC_SPIN_SUPERCOMPUTER          1062
#define IDC_EDIT_ABILITY                1062
#define IDC_SPIN_SPARES                 1062
#define IDC_SPIN_WINDTUNNEL             1063
#define IDC_EDIT_FINALSEASON            1063
#define IDC_SPIN_WORKSHOP               1064
#define IDC_EDIT_AGE                    1064
#define IDC_COMBO_TEAM                  1065
#define IDC_SPIN_SALARY                 1066
#define IDC_SPIN_ROYALTY                1067
#define IDC_SPIN_ABILITY                1068
#define IDC_SPIN_FINALSEASON            1069
#define IDC_SPIN_AGE                    1070
#define IDC_EDIT_STANDARD_EXCELLENT     1071
#define IDC_EDIT_STANDARD_VERYGOOD      1072
#define IDC_SPIN_BALANCE                1073
#define IDC_EDIT_STANDARD_GOOD          1073
#define IDC_EDIT_STANDARD_AVERAGE       1074
#define IDC_EDIT_STANDARD_TRAINEE       1075
#define IDC_EDIT_STARS_EXCELLENT        1076
#define IDC_EDIT_COST_MILE              1076
#define IDC_EDIT_BALANCE                1077
#define IDC_EDIT_STARS_VERYGOOD         1077
#define IDC_EDIT_STARS_GOOD             1078
#define IDC_EDIT_CAR2DAMAGE             1078
#define IDC_EDIT_STARS_AVERAGE          1079
#define IDC_EDIT_PERFORMENCE_ELECTRONICS 1079
#define IDC_EDIT_STARS_TRAINEE          1080
#define IDC_EDIT_RELIABILITY_SUSPENSION 1080
#define IDC_SPIN_STANDARD_TRAINEE       1081
#define IDC_EDIT_PERFORMENCE_BREAKES    1081
#define IDC_SPIN_STANDARD_AVERAGE       1082
#define IDC_EDIT_RELIABILITY_ELECTRONICS 1082
#define IDC_SPIN_STANDARD_VERYGOOD      1083
#define IDC_EDIT_MILES                  1083
#define IDC_SPIN_STANDARD_GOOD          1084
#define IDC_EDIT_CAR1DAMAGE             1084
#define IDC_SPIN_STANDARD_EXCELLENT     1085
#define IDC_EDIT_CAR3WARE               1085
#define IDC_SPIN_STARS_EXCELLENT        1086
#define IDC_EDIT_RELIABILITY_THROTTLE   1086
#define IDC_SPIN_STARS_TRAINEE          1087
#define IDC_SPIN_MILES                  1087
#define IDC_EDIT_RELIABILITY_CLUTCH     1087
#define IDC_SPIN_STARS_AVERAGE          1088
#define IDC_SPIN_COST_MILE              1088
#define IDC_EDIT_PERFORMENCE_SUSPENSION 1088
#define IDC_SPIN_STARS_GOOD             1089
#define IDC_EDIT_RELIABILITY_GEARBOX    1089
#define IDC_SPIN_STARS_VERYGOOD         1090
#define IDC_EDIT_POWERBREAKS            1090
#define IDC_EDIT_MORALE                 1091
#define IDC_EDIT_PERFORMENCE_THROTTLE   1091
#define IDC_EDIT_AVAILABLE              1092
#define IDC_SPIN_MORALE                 1093
#define IDC_EDIT_CAR1WARE               1093
#define IDC_SPIN_AVAILABLE              1094
#define IDC_EDIT_ACTIVESUSPENSION       1094
#define IDC_EDIT_DEMAND_CLOTHING        1095
#define IDC_EDIT_AUTOMATICGEARS         1095
#define IDC_EDIT_DEMAND_PUBLISHING      1096
#define IDC_EDIT_PERFORMENCE_CLUTCH     1096
#define IDC_EDIT_DEMAND_VIDEOGAMES      1097
#define IDC_EDIT_RELIABILITY_BREAKES    1097
#define IDC_EDIT_DEMAND_CHRONOMETERS    1098
#define IDC_EDIT_TRACTIONCONTROL        1098
#define IDC_EDIT_DEMAND_CARS            1099
#define IDC_EDIT_PERFORMENCE_GEARBOX    1099
#define IDC_EDIT_DEMAND_FANCLUB         1100
#define IDC_EDIT_RELIABILITY_HYDRAULICS 1100
#define IDC_CHECK_FANCLUB               1101
#define IDC_EDIT_SPARES                 1101
#define IDC_EDIT_COMPLETION_CLOTHING    1102
#define IDC_EDIT_CAR2WARE               1102
#define IDC_EDIT_COMPLETION_PUBLISHING  1103
#define IDC_EDIT_CAR3DAMAGE             1103
#define IDC_EDIT_COMPLETION_VIDEOGAMES  1104
#define IDC_EDIT_CAR4WARE               1104
#define IDC_EDIT_COMPLETION_CHRONOMETERS 1105
#define IDC_EDIT_CAR4DAMAGE             1105
#define IDC_EDIT_COMPLETION_CARS        1106
#define IDC_EDIT_COMPLETION_FANCLUB     1107
#define IDC_EDIT_CASH_CLOTHING          1108
#define IDC_EDIT_CASH_PUBLISHING        1109
#define IDC_EDIT_CASH_VIDEOGAMES        1110
#define IDC_EDIT_CASH_CHRONOMETERS      1111
#define IDC_EDIT_CASH_CARS              1112
#define IDC_EDIT_CASH_FANCLUB           1113
#define IDC_CHECK_CLOTHING              1114
#define IDC_CHECK_PUBLISHING            1115
#define IDC_CHECK_VIDEOGAMES            1116
#define IDC_CHECK_CHRONOMETERS          1117
#define IDC_CHECK_CARS                  1118
#define IDC_SPIN_DEMAND_FANCLUB         1119
#define IDC_SPIN_DEMAND_CLOTHING        1120
#define IDC_SPIN_DEMAND_PUBLISHING      1121
#define IDC_SPIN_DEMAND_VIDEOGAMES      1122
#define IDC_SPIN_DEMAND_CHRONOMETERS    1123
#define IDC_SPIN_DEMAND_CARS            1124
#define IDC_SPIN_COMPLETION_FANCLUB     1125
#define IDC_SPIN_COMPLETION_CLOTHING    1126
#define IDC_SPIN_COMPLETION_PUBLISHING  1127
#define IDC_SPIN_COMPLETION_VIDEOGAMES  1128
#define IDC_SPIN_COMPLETION_CHRONOMETERS 1129
#define IDC_SPIN_COMPLETION_CARS        1130
#define IDC_SPIN_CASH_FANCLUB           1131
#define IDC_SPIN_CASH_CLOTHING          1132
#define IDC_CHBONUS                     1132
#define IDC_SPIN_CASH_PUBLISHING        1133
#define IDC_DRIVERLOYALTY               1133
#define IDC_SPIN_CASH_VIDEOGAMES        1134
#define IDC_SPIN_CHBONUS                1134
#define IDC_SPIN_CASH_CHRONOMETERS      1135
#define IDC_EDIT_RACEBONUS              1135
#define IDC_SPIN_CASH_CARS              1136
#define IDC_SPIN_RACEBONUS              1136
#define IDC_THISCAR                     1137
#define IDC_NEXTCAR                     1138
#define IDC_CHASSIS                     1139
#define IDC_TECH                        1140
#define IDC_AIDS                        1141
#define IDC_SPARES                      1142
#define IDC_SPIN_THISCAR                1143
#define IDC_SPIN_NEXTCAR                1145
#define IDC_SPIN_CHASSIS                1146
#define IDC_DRIVER_COMBO_ROLE           1146
#define IDC_SPIN_TECH                   1147
#define IDC_DRIVER_COMBO_POS            1147
#define IDC_SPIN_AIDS                   1148
#define ID_EDIT_GPWDIRECTORY            32772
#define ID_EDIT_RUNGPW                  32778
#define ID_APP_HELP                     32779
#define ID_FILE_SAVEFILE                32782
#define ID_FILE_SAVEFILEAS              32783
#define ID_FILE_CLOSEFILE               32785
#define ID_EDIT_SAVEFILEDIRECTORY       32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
